// 拼读道场:按系统拼读顺序(易→难)排的 7 关。
// listen: 用词库里的词听音悟规律  practice: 拼词库词  transfer: 生词迁移考(没学过的词,靠规律拼出来才算过关)
// hl: 高亮规律部分的正则
const DOJO = [
{name:"短元音",icon:"1️⃣",tag:"一字一音",hl:"[aeiou]",
 desc:"fox · big · cop 这类三四个字母的短词",
 rule:"辅音+元音+辅音:每个字母发自己的音,中间的元音发短音——a/æ/ e/ɛ/ i/ɪ/ o/ɑ/ u/ʌ/。这是拼读的地基:先左到右把音连起来读。",
 listen:["fox","big","kid","win","cop","dad","mom","get","hit","tax"],
 practice:["big","cop","kid","get"],
 transfer:[{w:"hop",cn:"单脚跳",ch:["h","op"]},{w:"pet",cn:"宠物",ch:["p","et"]},{w:"sun",cn:"太阳",ch:["s","un"]}]},
{name:"辅音抱团",icon:"2️⃣",tag:"两个字母一个音",hl:"(tch|sh|ch|th|ck)",
 desc:"sh · ch · th · ck 永远绑在一起",
 rule:"sh 发 /ʃ/(嘘)、ch 发 /tʃ/、th 咬舌尖发 /θ·ð/、ck 就是 /k/。看到它们要当成一个整体,千万别拆开一个个念。",
 listen:["sheep","check","change","thing","think","thank","kick","snack","back","ticket"],
 practice:["check","thing","kick","snack"],
 transfer:[{w:"shop",cn:"商店",ch:["sh","op"]},{w:"chick",cn:"小鸡",ch:["ch","ick"]},{w:"math",cn:"数学",ch:["m","ath"]}]},
{name:"神奇 e",icon:"3️⃣",tag:"词尾e改元音",hl:"([aiou])(?=[bcdfghjklmnprstvz]e$)|e$",
 desc:"nine · home · face:结尾的 e 有魔法",
 rule:"词尾的 e 自己不发音,但它隔着一个辅音,把前面的元音变成字母本音:a→/eɪ/ i→/aɪ/ o→/oʊ/ u→/juː/。对比:hop(跳)→ hope(希望),kit → kite(风筝)。",
 listen:["nine","time","life","like","nice","ice","home","nose","face","place","take","safe"],
 practice:["nine","home","face","life"],
 transfer:[{w:"bike",cn:"自行车",ch:["b","ike"]},{w:"cake",cn:"蛋糕",ch:["c","ake"]},{w:"rope",cn:"绳子",ch:["r","ope"]}]},
{name:"元音抱团",icon:"4️⃣",tag:"两个元音手拉手",hl:"(ee|ea|ai|ay)",
 desc:"ee · ea · ai · ay 常发第一个的本音",
 rule:"两个元音在一起,通常发第一个元音的字母本音:ee·ea 发 /iː/,ai·ay 发 /eɪ/(ay 用在词尾)。例外要记:dead 里 ea 发 /ɛ/,great 里发 /eɪ/。",
 listen:["seed","street","need","dream","eat","peace","cheat","fail","day","way","play","away"],
 practice:["dream","street","fail","play"],
 transfer:[{w:"team",cn:"队伍",ch:["t","eam"]},{w:"rain",cn:"雨",ch:["r","ain"]},{w:"tray",cn:"托盘",ch:["tr","ay"]}]},
{name:"r 控制元音",icon:"5️⃣",tag:"r 会卷住元音",hl:"(ar|or|er|ir|ur)",
 desc:"ar · or · er · ir · ur:美音的卷舌味",
 rule:"元音后面跟着 r,音就被 r 卷住:ar /ɑːr/(farm)、or /ɔːr/(force)、er·ir·ur 都发 /ɜːr·ər/(officer·girl·return)。特例:w 后面的 or 发 /ɜːr/——world、work、worst。",
 listen:["farm","far","hard","carrot","force","before","officer","girl","first","return","herd"],
 practice:["farm","girl","first","officer"],
 transfer:[{w:"park",cn:"公园",ch:["p","ark"]},{w:"corn",cn:"玉米",ch:["c","orn"]},{w:"bird",cn:"鸟",ch:["b","ird"]}]},
{name:"特殊组合",icon:"6️⃣",tag:"igh·all·oi·ou·oo",hl:"(igh|all|oi|ou|ow|oo)",
 desc:"night · fall · join · proud · look",
 rule:"igh 发 /aɪ/(gh 不发音);all 发 /ɔːl/;oi 发 /ɔɪ/;ou·ow 发 /aʊ/(proud·cower)——但 ow 也常发 /oʊ/:know·show·window,两种都试试,像你听过的哪个词就读哪个;oo 有长短两种——room /uː/ 长、look·good /ʊ/ 短。",
 listen:["night","right","fall","wall","small","join","soil","point","proud","cower","know","room","look","good","foot"],
 practice:["night","small","join","proud"],
 transfer:[{w:"light",cn:"灯;光",ch:["l","igh","t"]},{w:"ball",cn:"球",ch:["b","all"]},{w:"coin",cn:"硬币",ch:["c","oin"]}]},
{name:"长词拆音节",icon:"7️⃣",tag:"大词=小块积木",hl:"",
 desc:"officer · predator:一拍一拍拼",
 rule:"长词不用怕:按节拍切成小块,每块用前 6 关的规律拼,再连起来。词缀是意义积木:un- = 不(unhappy),-er = 的人(hunter 猎人、farmer 农民)。",
 listen:["officer","predator","remember","criminal","academy","impossible","hunter","farmer"],
 practice:["predator","remember","criminal","impossible"],
 transfer:[{w:"basket",cn:"篮子",ch:["bas","ket"]},{w:"pumpkin",cn:"南瓜",ch:["pump","kin"]},{w:"unhappy",cn:"不开心的",ch:["un","hap","py"]}]},
];
