// 第七章 雨林区追逐 Rainforest District(台词 52:39-61:25)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch7.js
const WORDS = [
{w:"howler",ipa:"ˈhaʊlər",pos:"n.",cn:"嚎叫者",ch:["how","ler"],ph:"ow",tier:3,t:"52:41",en:"He just kept yelling about the Night Howlers.",zh:"他一个劲儿地喊“午夜嚎叫”。",note:"howl(嚎叫)+er;Night Howlers = 午夜嚎叫"},
{w:"yell",ipa:"jel",pos:"v.",cn:"大喊",ch:["y","ell"],ph:"CVC",tier:3,t:"52:41",en:"He just kept yelling about the Night Howlers.",zh:"他一个劲儿地喊“午夜嚎叫”。",note:"kept yelling = 一直喊个不停"},
{w:"clever",ipa:"ˈklevər",pos:"adj.",cn:"聪明的",ch:["cle","ver"],ph:"er",tier:1,t:"53:10",en:"Clever fox.",zh:"聪明的狐狸。"},
{w:"wrong",ipa:"rɔːŋ",pos:"adj.",cn:"不对劲的;错的",ch:["wr","ong"],ph:"wr",tier:1,t:"53:35",en:"- What is wrong with him?! - I don't know!",zh:"-他这是怎么了?!-我不知道!",note:"What's wrong with...? = …怎么了?"},
{w:"jump",ipa:"dʒʌmp",pos:"v.",cn:"跳",ch:["j","ump"],ph:"CVC",tier:1,t:"53:42",en:"Jump!",zh:"跳!"},
{w:"dispatch",ipa:"dɪˈspætʃ",pos:"n.",cn:"调度中心;派遣",ch:["dis","pa","tch"],ph:"tch",tier:3,t:"53:55",en:"Officer Hopps to dispatch!",zh:"霍普斯警官呼叫指挥中心!"},
{w:"angel",ipa:"ˈeɪndʒl",pos:"n.",cn:"天使",ch:["an","gel"],ph:"a-l",tier:3,t:"53:58",en:"Greatest singer of our lifetime. Angel with horns.",zh:"我们这辈子最伟大的歌手,长角的天使。"},
{w:"lifetime",ipa:"ˈlaɪftaɪm",pos:"n.",cn:"一生",ch:["life","time"],ph:"magic-e",tier:3,t:"53:58",en:"Greatest singer of our lifetime. Angel with horns.",zh:"我们这辈子最伟大的歌手,长角的天使。",note:"life+time"},
{w:"horn",ipa:"hɔːrn",pos:"n.",cn:"角;喇叭",ch:["h","orn"],ph:"or",tier:3,t:"53:58",en:"Greatest singer of our lifetime. Angel with horns.",zh:"我们这辈子最伟大的歌手,长角的天使。"},
{w:"hold",ipa:"hoʊld",pos:"v.",cn:"抓住;保持",ch:["h","old"],ph:"old",tier:2,t:"54:00",en:"Okay, hold on. Keep watching.",zh:"好,稍等,接着看。",note:"hold on = 稍等/坚持住"},
{w:"beside",ipa:"bɪˈsaɪd",pos:"prep.",cn:"在…旁边",ch:["be","side"],ph:"magic-e",tier:1,t:"54:02",en:"Who's that beside her? Who is it?",zh:"她旁边那个是谁?是谁呀?"},
{w:"hot",ipa:"hɑːt",pos:"adj.",cn:"热的;火辣的",ch:["h","ot"],ph:"CVC",tier:1,t:"54:03",en:"Wow,You are one hot dancer, Benjamin Clawhauser.",zh:"哇,你这舞跳得也太帅了,本杰明·洪金豹。",note:"hot dancer = 舞技火辣"},
{w:"app",ipa:"æp",pos:"n.",cn:"应用程序",ch:["app"],ph:"CVC",tier:2,t:"54:12",en:"It's not, it's just a new app.",zh:"不是啦,就是个新出的应用。",note:"application 的缩略"},
{w:"jaguar",ipa:"ˈdʒæɡwɑːr",pos:"n.",cn:"美洲豹",ch:["ja","gu","ar"],ph:"ar",tier:3,t:"54:17",en:"We have a 10-91! Jaguar gone savage!",zh:"这里有 10-91 警情!美洲豹发狂!",note:"gone savage = 变野了"},
{w:"backup",ipa:"ˈbækʌp",pos:"n.",cn:"支援",ch:["back","up"],ph:"ck",tier:3,t:"54:23",en:"Okay, we're sending backup!",zh:"收到,马上派增援!",note:"back+up"},
{w:"sky",ipa:"skaɪ",pos:"n.",cn:"天空",ch:["sk","y"],ph:"y-i",tier:2,t:"54:28",en:"Look, over there! Head for the sky-trams!",zh:"看,在那边!快去坐空中缆车!",note:"head for = 朝…去"},
{w:"tram",ipa:"træm",pos:"n.",cn:"缆车;有轨电车",ch:["tr","am"],ph:"CVC",tier:3,t:"54:28",en:"Look, over there! Head for the sky-trams!",zh:"看,在那边!快去坐空中缆车!"},
{w:"tense",ipa:"tens",pos:"adj.",cn:"紧绷的",ch:["ten","se"],ph:"e",tier:3,t:"54:55",en:"Now I can tell you're a little tense,",zh:"我看得出你现在有点紧张,",note:"I can tell = 我看得出"},
{w:"personal",ipa:"ˈpɜːrsənl",pos:"adj.",cn:"个人的",ch:["per","so","nal"],ph:"er-s",tier:2,t:"54:56",en:"so I'm just gonna give you a little personal space!",zh:"所以我就给你留点个人空间!",note:"personal space = 个人空间"},
{w:"whatever",ipa:"wʌtˈevər",pos:"pron.",cn:"无论什么",ch:["what","e","ver"],ph:"er",tier:2,t:"55:05",en:"Rabbit, whatever you do, do not let go!",zh:"兔子,不管发生什么,千万别松手!",note:"whatever you do = 千万(要/别)"},
{w:"let go",ipa:"",pos:"短语",cn:"松手",ch:["let","go"],ph:"",tier:1,type:"chunk",t:"55:05",en:"Rabbit, whatever you do, do not let go!",zh:"兔子,不管发生什么,千万别松手!",note:"和 let it go(想开点)不一样"},
{w:"stone",ipa:"stoʊn",pos:"n.",cn:"石头",ch:["st","one"],ph:"magic-e",tier:2,t:"55:56",en:"Savage? This isn't the stone age, Hopps.",zh:"发狂?现在又不是石器时代,霍普斯。",note:"the Stone Age = 石器时代"},
{w:"age",ipa:"eɪdʒ",pos:"n.",cn:"年龄;时代",ch:["age"],ph:"magic-e",tier:1,t:"55:56",en:"Savage? This isn't the stone age, Hopps.",zh:"发狂?现在又不是石器时代,霍普斯。"},
{w:"almost",ipa:"ˈɔːlmoʊst",pos:"adv.",cn:"几乎,差点",ch:["al","most"],ph:"al-o",tier:2,t:"56:11",en:"Sir, I know what I saw. He almost killed us!",zh:"长官,我亲眼所见,他差点杀了我们!"},
{w:"kill",ipa:"kɪl",pos:"v.",cn:"杀",ch:["k","ill"],ph:"i",tier:2,t:"56:11",en:"Sir, I know what I saw. He almost killed us!",zh:"长官,我亲眼所见,他差点杀了我们!"},
{w:"aggressive",ipa:"əˈɡresɪv",pos:"adj.",cn:"有攻击性的",ch:["ag","gres","sive"],ph:"e",tier:3,t:"56:13",en:"Or maybe any aggressive predator",zh:"也可能任何有攻击性的捕食动物",note:"attack(攻击)一家"},
{w:"clown",ipa:"klaʊn",pos:"n.",cn:"小丑",ch:["cl","own"],ph:"ow",tier:3,t:"57:00",en:"Look, you gave her a clown vest, and a three-wheeled joke-mobile.",zh:"听着,你给她一件小丑马甲、一辆三轮玩具车。"},
{w:"mobile",ipa:"ˈmoʊbl",pos:"adj.",cn:"可移动的;…车",ch:["mo","bile"],ph:"o",tier:2,t:"57:00",en:"Look, you gave her a clown vest, and a three-wheeled joke-mobile.",zh:"听着,你给她一件小丑马甲、一辆三轮玩具车。",note:"-mobile = …车(蝙蝠车 Batmobile)"},
{w:"wheel",ipa:"wiːl",pos:"n.",cn:"轮子",ch:["wh","eel"],ph:"ee",tier:2,t:"57:00",en:"Look, you gave her a clown vest, and a three-wheeled joke-mobile.",zh:"听着,你给她一件小丑马甲、一辆三轮玩具车。",note:"three-wheeled = 三个轮的"},
{w:"technically",ipa:"ˈteknɪkli",pos:"adv.",cn:"严格说来",ch:["tech","ni","cal","ly"],ph:"ch-k",tier:3,t:"57:15",en:"You gave her the 48 hours, so technically we still have...",zh:"是您给的48小时,所以按规矩算,我们还剩……",note:"口语=按规矩讲/理论上"},
{w:"follow",ipa:"ˈfɑːloʊ",pos:"v.",cn:"跟随;追查",ch:["fol","low"],ph:"ow-o",tier:2,t:"57:24",en:"we have a very big lead to follow and a case to crack.",zh:"我们还有大线索要追、大案子要破。",note:"follow a lead = 顺着线索查"},
{w:"junior",ipa:"ˈdʒuːniər",pos:"adj.",cn:"少年的;资历浅的",ch:["ju","nior"],ph:"u-l",tier:2,t:"58:25",en:"was join the Junior Ranger Scouts.",zh:"就是加入少年游侠童子军。"},
{w:"ranger",ipa:"ˈreɪndʒər",pos:"n.",cn:"游侠;护林员",ch:["ran","ger"],ph:"g-j",tier:3,t:"58:25",en:"was join the Junior Ranger Scouts.",zh:"就是加入少年游侠童子军。",note:"range(野外)+er:巡野外的人"},
{w:"scrape",ipa:"skreɪp",pos:"v.",cn:"刮;拼凑",ch:["scr","ape"],ph:"magic-e",tier:3,t:"58:28",en:"So my mom scraped together enough money",zh:"于是我妈妈东拼西凑攒够了钱",note:"scrape together = 一点点凑(钱)"},
{w:"brand",ipa:"brænd",pos:"adj.",cn:"品牌;(brand new)崭新",ch:["br","and"],ph:"CVC",tier:2,t:"58:31",en:"to buy me a brand new uniform.",zh:"给我买了一身崭新的制服。",note:"brand new = 崭新的"},
{w:"uniform",ipa:"ˈjuːnɪfɔːrm",pos:"n.",cn:"制服",ch:["u","ni","form"],ph:"u-l",tier:2,t:"58:31",en:"to buy me a brand new uniform.",zh:"给我买了一身崭新的制服。",note:"uni(统一)+form(样式)"},
{w:"fit in",ipa:"",pos:"短语",cn:"融入,合群",ch:["fit","in"],ph:"",tier:1,type:"chunk",t:"58:33",en:"Because, by god, I was gonna fit in.",zh:"因为我发誓,这回我要融入他们。"},
{w:"fit",ipa:"fɪt",pos:"v.",cn:"合身;融入",ch:["f","it"],ph:"CVC",tier:2,t:"58:33",en:"Because, by god, I was gonna fit in.",zh:"因为我发誓,这回我要融入他们。"},
{w:"troop",ipa:"truːp",pos:"n.",cn:"小队",ch:["tr","oop"],ph:"oo",tier:3,t:"58:36",en:"Even if I was the only predator in the troop, the only fox.",zh:"哪怕全队只有我一个捕食动物,唯一的狐狸。"},
{w:"initiation",ipa:"ɪˌnɪʃiˈeɪʃn",pos:"n.",cn:"入会仪式",ch:["i","ni","ti","a","tion"],ph:"tion",tier:3,t:"58:43",en:"- Ready for initiation? - Yeah. Pretty much born ready.",zh:"-准备好入会仪式了吗?-嗯,生下来就准备好了。",note:"born ready = 天生就绪(超有底气)"},
{w:"raise",ipa:"reɪz",pos:"v.",cn:"举起;抚养",ch:["r","ai","se"],ph:"ai",tier:2,t:"58:52",en:"Okay. Now raise your right paw, and deliver the oath.",zh:"好。现在举起右爪,宣誓。",note:"raise your paw/hand = 举手"},
{w:"deliver",ipa:"dɪˈlɪvər",pos:"v.",cn:"递送;宣(誓)",ch:["de","li","ver"],ph:"er",tier:3,t:"58:52",en:"Okay. Now raise your right paw, and deliver the oath.",zh:"好。现在举起右爪,宣誓。",note:"名词 delivery(第三章)"},
{w:"oath",ipa:"oʊθ",pos:"n.",cn:"誓言",ch:["oa","th"],ph:"oa",tier:3,t:"58:52",en:"Okay. Now raise your right paw, and deliver the oath.",zh:"好。现在举起右爪,宣誓。",note:"deliver the oath = 宣誓"},
{w:"promise",ipa:"ˈprɑːmɪs",pos:"v.",cn:"承诺",ch:["pro","mise"],ph:"i",tier:2,t:"58:56",en:"I, Nicholas Wilde, promise to be brave,",zh:"我,尼古拉斯·王尔德,承诺做到勇敢、",note:"promise to do = 保证做到"},
{w:"brave",ipa:"breɪv",pos:"adj.",cn:"勇敢的",ch:["br","ave"],ph:"magic-e",tier:2,t:"58:56",en:"I, Nicholas Wilde, promise to be brave,",zh:"我,尼古拉斯·王尔德,承诺做到勇敢、"},
{w:"loyal",ipa:"ˈlɔɪəl",pos:"adj.",cn:"忠诚的",ch:["loy","al"],ph:"oy",tier:3,t:"58:59",en:"loyal, helpful and trustworthy.",zh:"忠诚、乐于助人、值得信赖。"},
{w:"helpful",ipa:"ˈhelpfl",pos:"adj.",cn:"乐于助人的",ch:["help","ful"],ph:"CVC",tier:1,t:"58:59",en:"loyal, helpful and trustworthy.",zh:"忠诚、乐于助人、值得信赖。",note:"help+ful"},
{w:"trustworthy",ipa:"ˈtrʌstwɜːrði",pos:"adj.",cn:"值得信赖的",ch:["trust","wor","thy"],ph:"or",tier:3,t:"58:59",en:"loyal, helpful and trustworthy.",zh:"忠诚、乐于助人、值得信赖。",note:"trust(信任)+worthy(值得)"},
{w:"muzzle",ipa:"ˈmʌzl",pos:"n.",cn:"口套",ch:["muz","zle"],ph:"zz",tier:3,t:"59:18",en:"If you thought we would ever trust a fox without a muzzle?",zh:"你以为不戴口套,我们会信一只狐狸?",note:"也指动物的口鼻部"},
{w:"learn",ipa:"lɜːrn",pos:"v.",cn:"学会;明白",ch:["l","ear","n"],ph:"ear-er",tier:1,t:"59:43",en:"I learned two things that day.",zh:"那天我明白了两件事。",note:"过去式 learned"},
{w:"central",ipa:"ˈsentrəl",pos:"adj.",cn:"中心的",ch:["cen","tral"],ph:"c-s",tier:2,t:"60:13",en:"How about we go up to Chuck in traffic central?",zh:"不如连线交通中心的恰克?",note:"traffic central = 交通中心"},
{w:"jam",ipa:"dʒæm",pos:"n.",cn:"堵塞;果酱",ch:["j","am"],ph:"CVC",tier:3,t:"60:15",en:"Chuck, how are things looking on the jam cams?",zh:"恰克,路况摄像头那边看着怎么样?",note:"traffic jam = 堵车"},
{w:"glad",ipa:"ɡlæd",pos:"adj.",cn:"高兴的",ch:["gl","ad"],ph:"CVC",tier:2,t:"60:18",en:"Nick, I'm glad you told me.",zh:"尼克,我很高兴你告诉了我。",note:"I'm glad... = 我很高兴…"},
{w:"seriously",ipa:"ˈsɪriəsli",pos:"adv.",cn:"说真的",ch:["se","ri","ous","ly"],ph:"ly",tier:2,t:"60:22",en:"- Seriously, it's okay. - No, no no!",zh:"-真的,没事了。-不不不!",note:"serious(认真)+ly"},
{w:"camera",ipa:"ˈkæmərə",pos:"n.",cn:"摄像头,相机",ch:["ca","me","ra"],ph:"CVC",tier:2,t:"60:25",en:"There are traffic cameras everywhere. All over the canopy!",zh:"到处都有交通摄像头,整个树冠层全覆盖!"},
{w:"everywhere",ipa:"ˈevriwer",pos:"adv.",cn:"到处",ch:["e","very","where"],ph:"e",tier:2,t:"60:25",en:"There are traffic cameras everywhere. All over the canopy!",zh:"到处都有交通摄像头,整个树冠层全覆盖!",note:"every+where"},
{w:"canopy",ipa:"ˈkænəpi",pos:"n.",cn:"树冠层",ch:["ca","no","py"],ph:"y",tier:3,t:"60:25",en:"There are traffic cameras everywhere. All over the canopy!",zh:"到处都有交通摄像头,整个树冠层全覆盖!",note:"雨林区头顶的“绿天篷”"},
{w:"bingo",ipa:"ˈbɪŋɡoʊ",pos:"int.",cn:"中了!对喽!",ch:["bin","go"],ph:"o",tier:3,t:"60:33",en:"- Bingo! - Ho-ho! Pretty sneaky, slick!",zh:"-有了!-嚯,够鸡贼啊,滑头!",note:"宾果游戏喊的那声,引申=猜中了"},
{w:"sneaky",ipa:"ˈsniːki",pos:"adj.",cn:"鬼鬼祟祟的",ch:["snea","ky"],ph:"ea",tier:3,t:"60:33",en:"- Bingo! - Ho-ho! Pretty sneaky, slick!",zh:"-有了!-嚯,够鸡贼啊,滑头!",note:"sneak(偷偷溜)+y"},
{w:"access",ipa:"ˈækses",pos:"n.",cn:"进入权,访问",ch:["ac","cess"],ph:"cc",tier:3,t:"60:36",en:"However, if you didn't have access to the system before,",zh:"不过,你以前都进不了系统,",note:"have access to = 能进/能用"},
{w:"however",ipa:"haʊˈevər",pos:"adv.",cn:"然而",ch:["how","e","ver"],ph:"ow",tier:2,t:"60:36",en:"However, if you didn't have access to the system before,",zh:"不过,你以前都进不了系统,"},
{w:"doubt",ipa:"daʊt",pos:"v.",cn:"怀疑",ch:["dou","bt"],ph:"bt",tier:2,t:"60:39",en:"I doubt chief Buffalo Butt is gonna let you into it now.",zh:"我看水牛屁股局长现在也不会放你进去了。",note:"I doubt... = 我看悬"},
{w:"review",ipa:"rɪˈvjuː",pos:"v.",cn:"审阅;复习",ch:["re","view"],ph:"ew",tier:2,t:"60:49",en:"Sir, if we could just review these very important billings.",zh:"先生,我们还得过一遍这些重要账单。",note:"re(再)+view(看)"},
{w:"clear",ipa:"klɪr",pos:"v.",cn:"清空;晴朗",ch:["cl","ear"],ph:"ear",tier:2,t:"60:58",en:"Please. And clear my afternoon, I'm going out.",zh:"拜托了。把我下午的安排清掉,我要出门。",note:"clear my afternoon = 空出下午"},
{w:"afternoon",ipa:"ˌæftərˈnuːn",pos:"n.",cn:"下午",ch:["af","ter","noon"],ph:"oo",tier:1,t:"60:58",en:"Please. And clear my afternoon, I'm going out.",zh:"拜托了。把我下午的安排清掉,我要出门。",note:"noon(正午)之后"},
{w:"mutton",ipa:"ˈmʌtn",pos:"n.",cn:"羊肉",ch:["mut","ton"],ph:"CVC",tier:3,t:"61:07",en:"Oh, mutton chops.",zh:"哦,我的羊排呀。",note:"羊的口头感叹,像“我的妈呀”;也指连鬓胡"},
{w:"office",ipa:"ˈɔːfɪs",pos:"n.",cn:"办公室",ch:["of","fice"],ph:"c-s",tier:2,t:"61:13",en:"Office of the assistant mayor.",zh:"副市长办公室。"},
{w:"database",ipa:"ˈdeɪtəbeɪs",pos:"n.",cn:"数据库",ch:["da","ta","base"],ph:"a-l",tier:3,t:"61:14",en:"we just need to get into the traffic cam database.",zh:"我们只是需要进一下交通摄像头数据库。",note:"data(数据)+base(库)"},
];
