// 第一章「兔窝镇 Bunnyburrow」词卡数据 (01:01 - 09:55)
// 字段: w=单词 ipa=音标 pos=词性 cn=中文(贴合电影语境) ch=拼读音块 ph=拼读规律
//       tier: 1=基础词 2=核心词 3=进阶/彩蛋词  t=台词时间 en/zh=台词原句/翻译 note=讲解
const WORDS = [
{w:"fear",ipa:"fɪr",pos:"n./v.",cn:"恐惧;害怕",ch:["f","ear"],ph:"ear",tier:2,t:"08:29",en:"The only thing we have to fear is fear itself.",zh:"我们唯一需要恐惧的,就是恐惧本身。",fun:"彩蛋:这是美国总统罗斯福的名言,兔爸爸拿来用了"},
{w:"treachery",ipa:"ˈtretʃəri",pos:"n.",cn:"背叛",ch:["treach","er","y"],ph:"ch",tier:3,t:"01:01",en:"Fear, treachery, blood lust.",zh:"恐惧、背叛、嗜血。",fun:"全片第一句!小 Judy 舞台剧的开场白,故意用了很吓人的大词"},
{w:"blood",ipa:"blʌd",pos:"n.",cn:"血",ch:["bl","ood"],ph:"oo-x",tier:1,t:"01:25",en:"Blood! Blood! Blood!",zh:"血!血!血!",},
{w:"lust",ipa:"lʌst",pos:"n.",cn:"强烈的欲望",ch:["l","ust"],ph:"CVC",tier:3,t:"01:01",en:"Fear, treachery, blood lust.",zh:"恐惧、背叛、嗜血。",note:"blood lust = 嗜血欲"},
{w:"thousand",ipa:"ˈθaʊznd",pos:"num.",cn:"千",ch:["thou","sand"],ph:"ou",tier:1,t:"01:06",en:"Thousands of years ago these were the forces that ruled our world.",zh:"几千年前,是这些力量统治着我们的世界。",note:"thousands of = 成千上万的"},
{w:"ago",ipa:"əˈɡoʊ",pos:"adv.",cn:"……以前",ch:["a","go"],ph:"o",tier:1,t:"01:06",en:"Thousands of years ago these were the forces that ruled our world.",zh:"几千年前,是这些力量统治着我们的世界。"},
{w:"force",ipa:"fɔːrs",pos:"n.",cn:"力量",ch:["f","or","ce"],ph:"or",tier:2,t:"01:06",en:"Thousands of years ago these were the forces that ruled our world.",zh:"几千年前,是这些力量统治着我们的世界。"},
{w:"rule",ipa:"ruːl",pos:"v.",cn:"统治",ch:["r","ule"],ph:"magic-e",tier:2,t:"01:06",en:"These were the forces that ruled our world.",zh:"是这些力量统治着我们的世界。"},
{w:"world",ipa:"wɜːrld",pos:"n.",cn:"世界",ch:["w","orld"],ph:"or",tier:1,t:"01:06",en:"These were the forces that ruled our world.",zh:"是这些力量统治着我们的世界。",},
{w:"prey",ipa:"preɪ",pos:"n.",cn:"猎物;食草动物",ch:["pr","ey"],ph:"ey",tier:2,t:"01:11",en:"A world where prey were scared of predators.",zh:"那个世界里,食草动物害怕食肉动物。",note:"和 predator(捕食者)是一对"},
{w:"scared",ipa:"skerd",pos:"adj.",cn:"害怕的",ch:["sc","are","d"],ph:"are",tier:1,t:"04:55",en:"Scared now?",zh:"现在怕了吧?",note:"be scared of... = 害怕……"},
{w:"predator",ipa:"ˈpredətər",pos:"n.",cn:"捕食者;食肉动物",ch:["pred","a","tor"],ph:"or-er",tier:2,t:"01:11",en:"A world where prey were scared of predators.",zh:"那个世界里,食草动物害怕食肉动物。",note:"和 prey(猎物)是一对"},
{w:"uncontrollable",ipa:"ˌʌnkənˈtroʊləbl",pos:"adj.",cn:"无法控制的",ch:["un","con","troll","a","ble"],ph:"le",tier:2,t:"01:15",en:"And predators had an uncontrollable biological urge.",zh:"而食肉动物有一种无法控制的生物本能冲动。",note:"拆词:un(不)+ control(控制)+ lable(能……的)"},
{w:"biological",ipa:"ˌbaɪəˈlɑːdʒɪkl",pos:"adj.",cn:"生物(本能)的",ch:["bi","o","log","i","cal"],ph:"i",tier:3,t:"01:18",en:"An uncontrollable biological urge to maim, and maul.",zh:"一种无法控制的、想撕咬猎杀的生物本能。"},
{w:"urge",ipa:"ɜːrdʒ",pos:"n.",cn:"冲动",ch:["urge"],ph:"ur",tier:3,t:"01:18",en:"An uncontrollable biological urge to maim, and maul.",zh:"一种无法控制的、想撕咬猎杀的本能冲动。"},
{w:"maim",ipa:"meɪm",pos:"v.",cn:"使残废;残害",ch:["m","ai","m"],ph:"ai",tier:3,t:"01:18",en:"Biological urge to maim, and maul.",zh:"撕咬、残害的本能冲动。",fun:"彩蛋词:小 Judy 故意用血腥大词吓观众,和 maul 连用"},
{w:"maul",ipa:"mɔːl",pos:"v.",cn:"(猛兽)撕咬",ch:["m","aul"],ph:"au",tier:3,t:"01:18",en:"Biological urge to maim, and maul.",zh:"撕咬、残害的本能冲动。"},
{w:"death",ipa:"deθ",pos:"n.",cn:"死亡",ch:["d","ea","th"],ph:"ea-e",tier:2,t:"01:34",en:"And... Death!",zh:"还有……死亡!",},
{w:"divide",ipa:"dɪˈvaɪd",pos:"v.",cn:"划分",ch:["di","vide"],ph:"magic-e",tier:2,t:"01:42",en:"Back then, the world was divided in two.",zh:"那时候,世界被一分为二。"},
{w:"vicious",ipa:"ˈvɪʃəs",pos:"adj.",cn:"凶残的",ch:["vi","cious"],ph:"cious",tier:3,t:"01:46",en:"Vicious predator, or meek prey.",zh:"凶残的捕食者,或温顺的猎物。"},
{w:"meek",ipa:"miːk",pos:"adj.",cn:"温顺胆小的",ch:["m","ee","k"],ph:"ee",tier:3,t:"01:46",en:"Vicious predator, or meek prey.",zh:"凶残的捕食者,或温顺的猎物。"},
{w:"evolve",ipa:"ɪˈvɑːlv",pos:"v.",cn:"进化",ch:["e","volve"],ph:"magic-e",tier:2,t:"01:53",en:"But over time, we evolved.",zh:"但随着时间推移,我们进化了。",note:"over time = 随着时间推移"},
{w:"beyond",ipa:"bɪˈjɑːnd",pos:"prep.",cn:"超越,越过",ch:["be","yond"],ph:"CVC",tier:2,t:"01:56",en:"And moved beyond our primitive savage ways.",zh:"摆脱了我们原始野蛮的生活方式。"},
{w:"primitive",ipa:"ˈprɪmətɪv",pos:"adj.",cn:"原始的",ch:["prim","i","tive"],ph:"i",tier:3,t:"01:56",en:"And moved beyond our primitive savage ways.",zh:"摆脱了我们原始野蛮的生活方式。"},
{w:"savage",ipa:"ˈsævɪdʒ",pos:"adj.",cn:"野蛮的",ch:["sav","age"],ph:"age",tier:3,t:"01:56",en:"And moved beyond our primitive savage ways.",zh:"摆脱了我们原始野蛮的生活方式。"},
{w:"way",ipa:"weɪ",pos:"n.",cn:"方式;方法",ch:["w","ay"],ph:"ay",tier:1,t:"03:50",en:"No better way to do it than becoming a carrot farmer.",zh:"没有比当个胡萝卜农民更好的方式了。"},
{w:"harmony",ipa:"ˈhɑːrməni",pos:"n.",cn:"和谐",ch:["har","mo","ny"],ph:"ar",tier:2,t:"01:59",en:"Now predator and prey live in harmony.",zh:"如今食肉动物和食草动物和谐共处。",note:"in harmony = 和谐地"},
{w:"live",ipa:"lɪv",pos:"v.",cn:"生活",ch:["l","i","ve"],ph:"i",tier:1,t:"01:59",en:"Now predator and prey live in harmony.",zh:"如今食肉动物和食草动物和谐共处。"},
{w:"young",ipa:"jʌŋ",pos:"adj.",cn:"年轻的,幼小的",ch:["y","oung"],ph:"ou-x",tier:1,t:"02:04",en:"And every young mammal has multitudinous opportunities.",zh:"每一只年幼的哺乳动物都有数不清的机会。"},
{w:"mammal",ipa:"ˈmæml",pos:"n.",cn:"哺乳动物",ch:["mam","mal"],ph:"CVC",tier:2,t:"02:04",en:"And every young mammal has multitudinous opportunities.",zh:"每一只年幼的哺乳动物都有数不清的机会。"},
{w:"multitudinous",ipa:"ˌmʌltɪˈtuːdɪnəs",pos:"adj.",cn:"数不清的",ch:["mul","ti","tu","di","nous"],ph:"u-l",tier:3,t:"02:04",en:"Every young mammal has multitudinous opportunities.",zh:"每只年幼的哺乳动物都有数不清的机会。",fun:"炫词彩蛋:连很多美国人都不常用!小 Judy 演讲故意用大词,学会它可以惊呆你的英语老师"},
{w:"opportunity",ipa:"ˌɑːpərˈtuːnəti",pos:"n.",cn:"机会",ch:["op","por","tu","ni","ty"],ph:"or-er",tier:2,t:"02:04",en:"Every young mammal has multitudinous opportunities.",zh:"每只年幼的哺乳动物都有数不清的机会。"},
{w:"cower",ipa:"ˈkaʊər",pos:"v.",cn:"(害怕地)缩成一团",ch:["cow","er"],ph:"ow",tier:3,t:"02:09",en:"I don't have to cower in a herd anymore.",zh:"我再也不用缩在羊群里发抖了。"},
{w:"herd",ipa:"hɜːrd",pos:"n.",cn:"兽群,牧群",ch:["h","erd"],ph:"er-s",tier:2,t:"02:09",en:"I don't have to cower in a herd anymore.",zh:"我再也不用缩在羊群里发抖了。"},
{w:"anymore",ipa:"ˌeniˈmɔːr",pos:"adv.",cn:"(不)再",ch:["an","y","more"],ph:"or",tier:1,t:"02:09",en:"I don't have to cower in a herd anymore.",zh:"我再也不用缩在羊群里发抖了。",note:"用在否定句:not...anymore = 再也不……"},
{w:"instead",ipa:"ɪnˈsted",pos:"adv.",cn:"取而代之,反而",ch:["in","st","ea","d"],ph:"ea-e",tier:2,t:"02:13",en:"Instead, I can be an astronaut.",zh:"相反,我可以去当宇航员。"},
{w:"astronaut",ipa:"ˈæstrənɔːt",pos:"n.",cn:"宇航员",ch:["as","tro","naut"],ph:"au",tier:2,t:"02:13",en:"Instead, I can be an astronaut.",zh:"相反,我可以去当宇航员。",note:"astro = 星星(词根),宇航员就是'去星星那儿的人'"},
{w:"lonely",ipa:"ˈloʊnli",pos:"adj.",cn:"孤独的",ch:["lone","ly"],ph:"magic-e",tier:1,t:"02:19",en:"I don't have to be a lonely hunter anymore.",zh:"我再也不用当孤独的猎手了。"},
{w:"hunt",ipa:"hʌnt",pos:"v.",cn:"打猎;搜寻",ch:["h","unt"],ph:"CVC",tier:1,t:"02:22",en:"Today I can hunt for tax exemptions.",zh:"如今我可以去'捕猎'……免税额。",note:"hunter = 猎人"},
{w:"tax",ipa:"tæks",pos:"n.",cn:"税",ch:["t","ax"],ph:"CVC",tier:2,t:"02:22",en:"Today I can hunt for tax exemptions.",zh:"如今我可以去搜寻免税额。"},
{w:"exemption",ipa:"ɪɡˈzempʃn",pos:"n.",cn:"免除(额)",ch:["ex","emp","tion"],ph:"tion",tier:3,t:"02:22",en:"Today I can hunt for tax exemptions.",zh:"如今我可以去搜寻免税额。",note:"tax exemption = 免税额"},
{w:"actuary",ipa:"ˈæktʃueri",pos:"n.",cn:"精算师",ch:["ac","tu","ar","y"],ph:"y",tier:3,t:"02:25",en:"I'm gonna be an actuary.",zh:"我要当一名精算师。",note:"精算师:整天和数字打交道的职业"},
{w:"place",ipa:"pleɪs",pos:"n.",cn:"地方",ch:["pl","ace"],ph:"magic-e",tier:1,t:"02:29",en:"And I can make the world a better place.",zh:"而我,可以让世界变得更美好。"},
{w:"police",ipa:"pəˈliːs",pos:"n.",cn:"警察",ch:["po","lice"],ph:"magic-e",tier:1,t:"02:36",en:"A police officer!",zh:"一名警察!"},
{w:"officer",ipa:"ˈɔːfɪsər",pos:"n.",cn:"警官",ch:["of","fi","cer"],ph:"er",tier:1,t:"02:36",en:"A police officer!",zh:"一名警察!",note:"Officer Hopps = 霍普斯警官,对警察的称呼"},
{w:"cop",ipa:"kɑːp",pos:"n.",cn:"(口语)警察",ch:["c","op"],ph:"CVC",tier:1,t:"02:40",en:"Bunny cop? That is the most stupidest thing I ever heard!",zh:"兔子警察?这是我听过的最最愚蠢的事!",note:"police officer 是正式说法,cop 是口语"},
{w:"bunny",ipa:"ˈbʌni",pos:"n.",cn:"(口语)兔兔",ch:["bun","ny"],ph:"y",tier:1,t:"03:34",en:"There's never been a bunny cop.",zh:"从来没有过兔子警察。",note:"rabbit 是正式说法,bunny 更像'兔兔',全片都这么叫 Judy"},
{w:"stupid",ipa:"ˈstuːpɪd",pos:"adj.",cn:"愚蠢的",ch:["stu","pid"],ph:"u-l",tier:1,t:"02:40",en:"That is the most stupidest thing I ever heard!",zh:"这是我听过的最最愚蠢的事!",note:"most stupidest 是故意的语法错误(双重最高级),正确说法是 the stupidest"},
{w:"ever",ipa:"ˈevər",pos:"adv.",cn:"曾经;究竟",ch:["ev","er"],ph:"er",tier:1,t:"02:40",en:"That is the most stupidest thing I ever heard!",zh:"这是我听过的最愚蠢的事!"},
{w:"hear",ipa:"hɪr",pos:"v.",cn:"听见(过去式 heard)",ch:["h","ear"],ph:"ear",tier:1,t:"04:26",en:"You heard her. Cut it out.",zh:"你听见她说的了,住手。"},
{w:"seem",ipa:"siːm",pos:"v.",cn:"看起来,似乎",ch:["s","ee","m"],ph:"ee",tier:1,t:"02:44",en:"It may seem impossible to small minds.",zh:"在目光短浅的人看来,这也许不可能。"},
{w:"impossible",ipa:"ɪmˈpɑːsəbl",pos:"adj.",cn:"不可能的",ch:["im","pos","si","ble"],ph:"le",tier:1,t:"02:44",en:"It may seem impossible to small minds.",zh:"在目光短浅的人看来,这也许不可能。",note:"拆词:im(不)+ possible(可能的)"},
{w:"mind",ipa:"maɪnd",pos:"n.",cn:"头脑,心智",ch:["m","ind"],ph:"ind",tier:1,t:"02:44",en:"It may seem impossible to small minds.",zh:"在目光短浅的人看来,这也许不可能。",note:"small minds = 目光短浅的人"},
{w:"mile",ipa:"maɪl",pos:"n.",cn:"英里(约1.6公里)",ch:["m","ile"],ph:"magic-e",tier:1,t:"02:50",en:"But just 211 miles away, stands the great city of Zootopia.",zh:"但就在211英里之外,矗立着伟大的动物城。"},
{w:"stand",ipa:"stænd",pos:"v.",cn:"矗立;站",ch:["st","and"],ph:"st",tier:1,t:"02:50",en:"Just 211 miles away stands the great city of Zootopia.",zh:"就在211英里外,矗立着伟大的动物城。"},
{w:"great",ipa:"ɡreɪt",pos:"adj.",cn:"伟大的;极好的",ch:["gr","ea","t"],ph:"ea-a",tier:1,t:"02:50",en:"Stands the great city of Zootopia.",zh:"矗立着伟大的动物城。",},
{w:"city",ipa:"ˈsɪti",pos:"n.",cn:"城市",ch:["cit","y"],ph:"y",tier:1,t:"02:50",en:"Stands the great city of Zootopia.",zh:"矗立着伟大的动物城。",note:"c 在 i/e/y 前发 /s/:city, center, nice"},
{w:"ancestor",ipa:"ˈænsestər",pos:"n.",cn:"祖先",ch:["an","ces","tor"],ph:"or-er",tier:2,t:"02:57",en:"Where our ancestors first joined together in peace.",zh:"在那里,我们的祖先第一次和平地走到了一起。"},
{w:"join",ipa:"dʒɔɪn",pos:"v.",cn:"联合;加入",ch:["j","oi","n"],ph:"oi",tier:1,t:"02:57",en:"Where our ancestors first joined together in peace.",zh:"我们的祖先第一次和平地走到了一起。"},
{w:"peace",ipa:"piːs",pos:"n.",cn:"和平",ch:["p","ea","ce"],ph:"ea",tier:1,t:"02:57",en:"Our ancestors first joined together in peace.",zh:"我们的祖先第一次和平地走到了一起。",note:"in peace = 和平地"},
{w:"declare",ipa:"dɪˈkler",pos:"v.",cn:"宣告",ch:["de","clare"],ph:"are",tier:2,t:"03:00",en:"And declared that anyone can be anything!",zh:"并宣告:任何人都能成为任何想成为的样子!",fun:"这句是全片的灵魂台词!"},
{w:"anyone",ipa:"ˈeniwʌn",pos:"pron.",cn:"任何人",ch:["an","y","one"],ph:"y",tier:1,t:"03:00",en:"Anyone can be anything!",zh:"任何人都能成为任何想成为的样子!"},
{w:"anything",ipa:"ˈeniθɪŋ",pos:"pron.",cn:"任何事物",ch:["an","y","thing"],ph:"th",tier:1,t:"03:00",en:"Anyone can be anything!",zh:"任何人都能成为任何想成为的样子!"},
{w:"wonder",ipa:"ˈwʌndər",pos:"v.",cn:"想知道,好奇",ch:["won","der"],ph:"er",tier:2,t:"03:09",en:"Judy, you ever wonder how your mom and me got to be so darn happy?",zh:"朱迪,你想没想过,你妈和我怎么会这么幸福?"},
{w:"darn",ipa:"dɑːrn",pos:"adv.",cn:"(口语)特别,非常",ch:["d","arn"],ph:"ar",tier:3,t:"03:13",en:"How your mom and me got to be so darn happy?",zh:"你妈和我怎么会这么幸福?",note:"口语加强词,类似中文的'贼幸福'"},
{w:"nope",ipa:"noʊp",pos:"int.",cn:"(口语)不,没有",ch:["n","ope"],ph:"magic-e",tier:2,t:"03:15",en:"Nope.",zh:"没有。",note:"no 的俏皮说法"},
{w:"dream",ipa:"driːm",pos:"n.",cn:"梦想",ch:["dr","ea","m"],ph:"ea",tier:1,t:"04:07",en:"It's great to have dreams.",zh:"有梦想是好事。"},
{w:"settle",ipa:"ˈsetl",pos:"v.",cn:"安顿下来;将就",ch:["set","tle"],ph:"le",tier:2,t:"03:16",en:"We gave up on our dreams, and we settled.",zh:"我们放弃了梦想,安于现状了。",note:"核心讽刺词:爸妈把'认命'说得理直气壮,电影在反着说"},
{w:"hard",ipa:"hɑːrd",pos:"adv.",cn:"狠狠地;努力地",ch:["h","ar","d"],ph:"ar",tier:1,t:"03:19",en:"We settled hard.",zh:"我们可是彻底安顿下来了。"},
{w:"beauty",ipa:"ˈbjuːti",pos:"n.",cn:"美;妙处",ch:["beau","ty"],ph:"y",tier:2,t:"03:21",en:"That's the beauty of complacency, Jude.",zh:"这就是安于现状的妙处,朱迪。",note:"the beauty of... = ……的妙处"},
{w:"complacency",ipa:"kəmˈpleɪsnsi",pos:"n.",cn:"自满,安于现状",ch:["com","pla","cen","cy"],ph:"cy",tier:3,t:"03:21",en:"That's the beauty of complacency, Jude.",zh:"这就是安于现状的妙处。",fun:"彩蛋大词:爸爸用高级词说泄气话,反差笑点"},
{w:"try",ipa:"traɪ",pos:"v.",cn:"尝试",ch:["tr","y"],ph:"y-i",tier:1,t:"03:25",en:"If you don't try anything new, you'll never fail.",zh:"只要你不尝试新东西,就永远不会失败。",},
{w:"fail",ipa:"feɪl",pos:"v.",cn:"失败",ch:["f","ai","l"],ph:"ai",tier:1,t:"03:25",en:"If you don't try anything new, you'll never fail.",zh:"只要你不尝试新东西,就永远不会失败。"},
{w:"actually",ipa:"ˈæktʃuəli",pos:"adv.",cn:"其实,实际上",ch:["ac","tu","al","ly"],ph:"ly",tier:2,t:"03:27",en:"I like trying, actually.",zh:"其实,我喜欢尝试。",note:"美国人口头禅,一天能说八百遍"},
{w:"mean",ipa:"miːn",pos:"v.",cn:"意思是",ch:["m","ea","n"],ph:"ea",tier:1,t:"03:29",en:"What your father means, hon...",zh:"你爸爸的意思是,宝贝……",note:"I mean... = 我是说……(口头禅)"},
{w:"difficult",ipa:"ˈdɪfɪkəlt",pos:"adj.",cn:"困难的",ch:["dif","fi","cult"],ph:"i",tier:1,t:"03:30",en:"It's gonna be difficult, impossible even, for you to become a police officer.",zh:"你想当警察会很难,甚至不可能。"},
{w:"become",ipa:"bɪˈkʌm",pos:"v.",cn:"成为",ch:["be","come"],ph:"o-u2",tier:1,t:"03:30",en:"For you to become a police officer.",zh:"你想成为一名警察。"},
{w:"guess",ipa:"ɡes",pos:"v.",cn:"猜",ch:["gu","ess"],ph:"gu",tier:1,t:"03:38",en:"Then I guess I'll have to be the first one.",zh:"那我猜,我只好当第一个了。",note:"I guess = 我猜/那好吧"},
{w:"first",ipa:"fɜːrst",pos:"adj.",cn:"第一个",ch:["f","ir","st"],ph:"ir",tier:1,t:"03:38",en:"I'll have to be the first one.",zh:"我只好当第一个了。"},
{w:"heck",ipa:"hek",pos:"int.",cn:"(口语)见鬼,搞什么",ch:["h","eck"],ph:"ck",tier:3,t:"04:14",en:"Where the heck'd she go?",zh:"她到底跑哪儿去了?",note:"语气词:the heck 加在疑问词后表示'到底/究竟'"},
{w:"talk",ipa:"tɔːk",pos:"v.",cn:"谈论",ch:["t","al","k"],ph:"al",tier:1,t:"03:48",en:"You wanna talk about making the world a better place?",zh:"你想谈谈怎么让世界更美好?",},
{w:"farmer",ipa:"ˈfɑːrmər",pos:"n.",cn:"农民(farm=农场)",ch:["far","mer"],ph:"ar",tier:1,t:"03:50",en:"No better way to do it than becoming a carrot farmer.",zh:"没有比当个胡萝卜农民更好的方式了。"},
{w:"carrot",ipa:"ˈkærət",pos:"n.",cn:"胡萝卜",ch:["car","rot"],ph:"CVC",tier:1,t:"03:58",en:"One carrot at a time.",zh:"一次一根胡萝卜。",note:"one ... at a time = 一次一个,慢慢来"},
{w:"brother",ipa:"ˈbrʌðər",pos:"n.",cn:"兄弟",ch:["bro","ther"],ph:"th",tier:1,t:"03:52",en:"Your dad, me, your 275 brothers and sisters.",zh:"你爸、我,还有你的275个兄弟姐妹。",fun:"兔子家庭真的很能生……"},
{w:"sister",ipa:"ˈsɪstər",pos:"n.",cn:"姐妹",ch:["sis","ter"],ph:"er",tier:1,t:"03:52",en:"Your 275 brothers and sisters.",zh:"你的275个兄弟姐妹。"},
{w:"change",ipa:"tʃeɪndʒ",pos:"v.",cn:"改变",ch:["ch","ange"],ph:"ch",tier:1,t:"03:56",en:"We're changing the world.",zh:"我们正在改变世界。"},
{w:"noble",ipa:"ˈnoʊbl",pos:"adj.",cn:"高尚的",ch:["no","ble"],ph:"le",tier:2,t:"04:00",en:"Carrot farming is a noble profession.",zh:"种胡萝卜是一份高尚的职业。"},
{w:"profession",ipa:"prəˈfeʃn",pos:"n.",cn:"职业",ch:["pro","fes","sion"],ph:"sion",tier:2,t:"04:00",en:"Carrot farming is a noble profession.",zh:"种胡萝卜是一份高尚的职业。"},
{w:"pull",ipa:"pʊl",pos:"v.",cn:"拔;拉",ch:["p","ull"],ph:"u",tier:1,t:"04:03",en:"Just pulling their seeds out.",zh:"把种子从土里拔出来。"},
{w:"seed",ipa:"siːd",pos:"n.",cn:"种子",ch:["s","ee","d"],ph:"ee",tier:1,t:"04:03",en:"Just pulling their seeds out.",zh:"把种子从土里拔出来。"},
{w:"soil",ipa:"sɔɪl",pos:"n.",cn:"土壤",ch:["s","oi","l"],ph:"oi",tier:2,t:"04:04",en:"And one with the soil...",zh:"与土地融为一体……",note:"one with... = 与……合一"},
{w:"honey",ipa:"ˈhʌni",pos:"n.",cn:"宝贝(称呼);蜂蜜",ch:["hon","ey"],ph:"ey-i",tier:1,t:"04:07",en:"You get it, honey?",zh:"你明白吗,宝贝?",note:"hon 是 honey 的简称,爸妈叫孩子、夫妻互称都用它"},
{w:"believe",ipa:"bɪˈliːv",pos:"v.",cn:"相信",ch:["be","lieve"],ph:"ie",tier:1,t:"04:09",en:"Just as long as you don't believe in them too much.",zh:"只要你别太当真就行。",note:"believe in your dreams = 相信你的梦想"},
{w:"ticket",ipa:"ˈtɪkɪt",pos:"n.",cn:"票",ch:["tick","et"],ph:"ck",tier:1,t:"04:16",en:"Give me your tickets right now!",zh:"立刻把你们的票给我!"},
{w:"kick",ipa:"kɪk",pos:"v.",cn:"踢",ch:["k","ick"],ph:"ck",tier:1,t:"04:18",en:"Or I'm gonna kick your meek little sheep butt.",zh:"不然我就踢你这胆小的小羊屁股。"},
{w:"sheep",ipa:"ʃiːp",pos:"n.",cn:"绵羊",ch:["sh","ee","p"],ph:"sh",tier:1,t:"04:18",en:"Your meek little sheep butt.",zh:"你这胆小的小羊屁股。",note:"单复数同形:one sheep, two sheep"},
{w:"butt",ipa:"bʌt",pos:"n.",cn:"(口语)屁股",ch:["b","utt"],ph:"CVC",tier:2,t:"06:39",en:"You're dead, fluff butt.",zh:"你死定了,毛绒屁股。",fun:"电影里全是屁股梗:sheep butt、fluff butt"},
{w:"cry",ipa:"kraɪ",pos:"v.",cn:"哭",ch:["cr","y"],ph:"y-i",tier:1,t:"04:22",en:"What are you gonna do, cry?",zh:"你能怎么办,哭鼻子吗?"},
{w:"costume",ipa:"ˈkɑːstuːm",pos:"n.",cn:"戏服,演出服",ch:["cos","tume"],ph:"magic-e",tier:2,t:"04:26",en:"Nice costume, loser.",zh:"戏服不错嘛,废物。"},
{w:"loser",ipa:"ˈluːzər",pos:"n.",cn:"失败者,废物",ch:["los","er"],ph:"er",tier:2,t:"04:26",en:"Nice costume, loser.",zh:"戏服不错嘛,废物。",note:"lose(输)+ er(的人)。骂人词,听得懂就行,别学着用"},
{w:"crazy",ipa:"ˈkreɪzi",pos:"adj.",cn:"疯狂的",ch:["cra","zy"],ph:"y",tier:1,t:"04:30",en:"What crazy world are you living in?",zh:"你活在哪个疯狂世界里?"},
{w:"kindly",ipa:"ˈkaɪndli",pos:"adv.",cn:"请,劳驾(很客气)",ch:["kind","ly"],ph:"ind",tier:2,t:"04:35",en:"Kindly return my friend's tickets.",zh:"请把我朋友的票还回来。",fun:"小 Judy 对坏蛋都这么有礼貌,反差感拉满"},
{w:"return",ipa:"rɪˈtɜːrn",pos:"v.",cn:"归还;返回",ch:["re","turn"],ph:"ur",tier:1,t:"04:35",en:"Kindly return my friend's tickets.",zh:"请把我朋友的票还回来。"},
{w:"friend",ipa:"frend",pos:"n.",cn:"朋友",ch:["fr","ie","nd"],ph:"ie-e",tier:1,t:"04:35",en:"Kindly return my friend's tickets.",zh:"请把我朋友的票还回来。"},
{w:"fox",ipa:"fɑːks",pos:"n.",cn:"狐狸",ch:["f","ox"],ph:"CVC",tier:1,t:"04:39",en:"Cause I'm a fox.",zh:"因为我是狐狸嘛。"},
{w:"dumb",ipa:"dʌm",pos:"adj.",cn:"愚蠢的",ch:["d","umb"],ph:"mb",tier:2,t:"04:40",en:"Like you said in your dumb little stage play.",zh:"就像你在你那愚蠢的小舞台剧里说的。",},
{w:"stage",ipa:"steɪdʒ",pos:"n.",cn:"舞台",ch:["st","age"],ph:"age",tier:2,t:"04:40",en:"Your dumb little stage play.",zh:"你那愚蠢的小舞台剧。",note:"stage play = 舞台剧"},
{w:"eat",ipa:"iːt",pos:"v.",cn:"吃",ch:["ea","t"],ph:"ea",tier:1,t:"04:42",en:"Us predators used to eat prey.",zh:"我们食肉动物过去是吃猎物的。"},
{w:"killer",ipa:"ˈkɪlər",pos:"n.",cn:"杀手",ch:["kill","er"],ph:"er",tier:2,t:"04:45",en:"That killer instinct's still in our DNA.",zh:"那种杀手本能还留在我们的DNA里。"},
{w:"instinct",ipa:"ˈɪnstɪŋkt",pos:"n.",cn:"本能",ch:["in","stinct"],ph:"st",tier:2,t:"04:45",en:"That killer instinct's still in our DNA.",zh:"那种杀手本能还留在我们的DNA里。"},
{w:"DNA",ipa:"ˌdiːenˈeɪ",pos:"n.",cn:"DNA(遗传物质)",ch:["D","N","A"],ph:"",tier:2,t:"04:47",en:"I'm pretty much sure it's pronounced DNA.",zh:"我很确定,那个词读作DNA。",fun:"笑点:Gideon 把 DNA 说成了 DANA,被小伙伴当场纠正"},
{w:"pronounce",ipa:"prəˈnaʊns",pos:"v.",cn:"发音",ch:["pro","nounce"],ph:"ou",tier:2,t:"04:47",en:"I'm pretty much sure it's pronounced DNA.",zh:"我很确定,那个词读作DNA。"},
{w:"scare",ipa:"sker",pos:"v.",cn:"吓唬",ch:["sc","are"],ph:"are",tier:1,t:"04:51",en:"You don't scare me, Gideon.",zh:"你吓不到我,吉迪恩。",note:"scare(吓唬别人)→ scared(自己被吓到)"},
{w:"nose",ipa:"noʊz",pos:"n.",cn:"鼻子",ch:["n","ose"],ph:"magic-e",tier:1,t:"04:56",en:"Look at her nose twitch, she is scared.",zh:"看她的鼻子在抽动,她害怕了。"},
{w:"twitch",ipa:"twɪtʃ",pos:"v.",cn:"抽动",ch:["tw","itch"],ph:"tch",tier:3,t:"04:56",en:"Look at her nose twitch.",zh:"看她的鼻子在抽动。",fun:"兔子紧张时鼻子会抖——观察得很准的动物细节"},
{w:"quit",ipa:"kwɪt",pos:"v.",cn:"放弃,认输",ch:["qu","it"],ph:"qu",tier:2,t:"05:46",en:"I don't know when to quit.",zh:"我从来不知道什么叫放弃。",fun:"全章灵魂台词!Gideon 骂她'不知道什么时候该认输',Judy 把它变成自己的座右铭"},
{w:"remember",ipa:"rɪˈmembər",pos:"v.",cn:"记住",ch:["re","mem","ber"],ph:"er",tier:1,t:"05:14",en:"I want you to remember this moment.",zh:"我要你记住这一刻。"},
{w:"moment",ipa:"ˈmoʊmənt",pos:"n.",cn:"时刻",ch:["mo","ment"],ph:"o",tier:1,t:"05:14",en:"I want you to remember this moment.",zh:"我要你记住这一刻。"},
{w:"next",ipa:"nekst",pos:"adj.",cn:"下一个",ch:["n","ext"],ph:"x",tier:1,t:"05:16",en:"The next time you think you will ever be anything more...",zh:"下次你再幻想自己能有什么出息的时候……"},
{w:"bad",ipa:"bæd",pos:"adj.",cn:"糟糕的",ch:["b","ad"],ph:"CVC",tier:1,t:"05:27",en:"That looks bad.",zh:"伤得不轻啊。"},
{w:"awesome",ipa:"ˈɔːsəm",pos:"adj.",cn:"(口语)棒极了",ch:["awe","some"],ph:"aw",tier:2,t:"05:34",en:"You're awesome, Judy.",zh:"你太棒了,朱迪!",note:"美国孩子的万能夸奖词"},
{w:"right",ipa:"raɪt",pos:"adj.",cn:"对的;右边",ch:["r","igh","t"],ph:"igh",tier:1,t:"05:41",en:"Well, he was right about one thing.",zh:"不过,有一件事他说对了。",},
{w:"listen",ipa:"ˈlɪsn",pos:"v.",cn:"听",ch:["lis","ten"],ph:"st-t",tier:1,t:"05:50",en:"Listen up, cadets.",zh:"都听好了,学员们!",note:"Listen up = 都听着(教官口气)"},
{w:"cadet",ipa:"kəˈdet",pos:"n.",cn:"(警校/军校)学员",ch:["ca","det"],ph:"e",tier:3,t:"05:50",en:"Listen up, cadets.",zh:"都听好了,学员们!",fun:"你在这个 App 里的起始警衔就是它"},
{w:"unique",ipa:"juˈniːk",pos:"adj.",cn:"独一无二的",ch:["u","nique"],ph:"que",tier:2,t:"05:52",en:"Zootopia has 12 unique ecosystems within its city limits.",zh:"动物城的市区内有12个独特的生态区。",},
{w:"ecosystem",ipa:"ˈiːkoʊsɪstəm",pos:"n.",cn:"生态系统",ch:["e","co","sys","tem"],ph:"y-i2",tier:2,t:"05:52",en:"Zootopia has 12 unique ecosystems within its city limits.",zh:"动物城的市区内有12个独特的生态区。",note:"eco(生态)+ system(系统)"},
{w:"within",ipa:"wɪˈðɪn",pos:"prep.",cn:"在……之内",ch:["with","in"],ph:"th",tier:2,t:"05:52",en:"Within its city limits.",zh:"在它的市区范围之内。"},
{w:"limit",ipa:"ˈlɪmɪt",pos:"n.",cn:"界限,范围",ch:["lim","it"],ph:"i",tier:2,t:"05:52",en:"Within its city limits.",zh:"在它的市区范围之内。",note:"city limits = 市区边界"},
{w:"district",ipa:"ˈdɪstrɪkt",pos:"n.",cn:"城区,区域",ch:["dis","trict"],ph:"st",tier:2,t:"05:56",en:"Tundratown, Sahara Square, Rainforest District, to name a few.",zh:"冰川镇、撒哈拉广场、雨林区,随便举几个。"},
{w:"master",ipa:"ˈmæstər",pos:"v.",cn:"掌握,精通",ch:["mas","ter"],ph:"er",tier:2,t:"06:02",en:"You're gonna have to master all of them before you hit the streets.",zh:"上街执勤之前,你们必须掌握所有这些环境。"},
{w:"street",ipa:"striːt",pos:"n.",cn:"街道",ch:["str","ee","t"],ph:"ee",tier:1,t:"06:02",en:"Before you hit the streets.",zh:"在你们上街执勤之前。",note:"hit the streets = 上街(执勤),口语搭配"},
{w:"dead",ipa:"ded",pos:"adj.",cn:"死的",ch:["d","ea","d"],ph:"ea-e",tier:1,t:"06:04",en:"Or guess what? You'll be dead!",zh:"不然怎样?你就死定了!",note:"You're dead 这里是吓唬人的夸张说法,不是真'死了'"},
{w:"scorching",ipa:"ˈskɔːrtʃɪŋ",pos:"adj.",cn:"灼热的",ch:["scorch","ing"],ph:"or",tier:3,t:"06:09",en:"Scorching sandstorm.",zh:"灼热的沙尘暴。"},
{w:"sandstorm",ipa:"ˈsændstɔːrm",pos:"n.",cn:"沙尘暴",ch:["sand","storm"],ph:"or",tier:2,t:"06:09",en:"Scorching sandstorm.",zh:"灼热的沙尘暴。",note:"sand(沙)+ storm(风暴),合成词"},
{w:"bumpkin",ipa:"ˈbʌmpkɪn",pos:"n.",cn:"乡巴佬",ch:["bump","kin"],ph:"CVC",tier:3,t:"06:13",en:"You're dead, bunny bumpkin.",zh:"你死定了,兔子乡巴佬。",note:"骂人词,听得懂就行,别学着用"},
{w:"foot",ipa:"fʊt",pos:"n.",cn:"英尺;脚",ch:["f","oo","t"],ph:"oo-u",tier:1,t:"06:15",en:"One thousand foot fall.",zh:"一千英尺高空坠落。",},
{w:"fall",ipa:"fɔːl",pos:"n./v.",cn:"坠落",ch:["f","all"],ph:"all",tier:1,t:"06:15",en:"One thousand foot fall.",zh:"一千英尺高空坠落。"},
{w:"face",ipa:"feɪs",pos:"n.",cn:"脸",ch:["f","ace"],ph:"magic-e",tier:1,t:"06:18",en:"You're dead, carrot face.",zh:"你死了,胡萝卜脸。"},
{w:"frigid",ipa:"ˈfrɪdʒɪd",pos:"adj.",cn:"严寒的",ch:["frig","id"],ph:"i",tier:3,t:"06:21",en:"Frigid ice wall.",zh:"冰冷刺骨的冰墙。"},
{w:"ice",ipa:"aɪs",pos:"n.",cn:"冰",ch:["ice"],ph:"magic-e",tier:1,t:"06:21",en:"Frigid ice wall.",zh:"冰冷刺骨的冰墙。"},
{w:"wall",ipa:"wɔːl",pos:"n.",cn:"墙",ch:["w","all"],ph:"all",tier:1,t:"06:21",en:"Frigid ice wall.",zh:"冰冷刺骨的冰墙。"},
{w:"farm",ipa:"fɑːrm",pos:"n.",cn:"农场",ch:["f","ar","m"],ph:"ar",tier:1,t:"06:24",en:"You're dead, farm girl.",zh:"你死了,农场丫头。"},
{w:"enormous",ipa:"ɪˈnɔːrməs",pos:"adj.",cn:"巨大的",ch:["e","nor","mous"],ph:"or",tier:2,t:"06:26",en:"Enormous criminal. You're dead.",zh:"巨型罪犯。你死了。"},
{w:"criminal",ipa:"ˈkrɪmɪnl",pos:"n.",cn:"罪犯",ch:["crim","i","nal"],ph:"i",tier:2,t:"06:26",en:"Enormous criminal. You're dead.",zh:"巨型罪犯。你死了。",note:"crime(犯罪)+ inal(的人)"},
{w:"filthy",ipa:"ˈfɪlθi",pos:"adj.",cn:"极脏的",ch:["filth","y"],ph:"th",tier:3,t:"06:39",en:"Filthy toilet. You're dead, fluff butt.",zh:"脏兮兮的马桶。你死了,毛绒屁股。",note:"比 dirty 更脏一个等级"},
{w:"toilet",ipa:"ˈtɔɪlət",pos:"n.",cn:"马桶;厕所",ch:["toi","let"],ph:"oi",tier:1,t:"06:39",en:"Filthy toilet.",zh:"脏兮兮的马桶。"},
{w:"fluff",ipa:"flʌf",pos:"n.",cn:"绒毛",ch:["fl","uff"],ph:"ff",tier:3,t:"06:39",en:"You're dead, fluff butt.",zh:"你死了,毛绒屁股。",note:"fluffy = 毛茸茸的"},
{w:"fuzzy",ipa:"ˈfʌzi",pos:"adj.",cn:"毛茸茸的",ch:["fuzz","y"],ph:"zz",tier:3,t:"06:42",en:"Just quit and go home, fuzzy bunny.",zh:"认输回家吧,毛毛兔。"},
{w:"home",ipa:"hoʊm",pos:"n.",cn:"家",ch:["h","ome"],ph:"magic-e",tier:1,t:"06:42",en:"Just quit and go home, fuzzy bunny.",zh:"认输回家吧,毛毛兔。"},
{w:"mayor",ipa:"ˈmeɪər",pos:"n.",cn:"市长",ch:["may","or"],ph:"ay",tier:2,t:"07:17",en:"As mayor of Zootopia, I am proud to announce...",zh:"作为动物城市长,我很自豪地宣布……"},
{w:"proud",ipa:"praʊd",pos:"adj.",cn:"自豪的",ch:["pr","ou","d"],ph:"ou",tier:1,t:"08:13",en:"We're real proud of you, Judy.",zh:"我们真为你骄傲,朱迪。",note:"be proud of... = 为……自豪"},
{w:"announce",ipa:"əˈnaʊns",pos:"v.",cn:"宣布",ch:["an","nounce"],ph:"ou",tier:2,t:"07:18",en:"I am proud to announce that my mammal inclusion initiative has produced its first police academy graduate.",zh:"我自豪地宣布,我的'哺乳动物包容计划'培养出了第一位警校毕业生。"},
{w:"inclusion",ipa:"ɪnˈkluːʒn",pos:"n.",cn:"包容",ch:["in","clu","sion"],ph:"sion",tier:3,t:"07:18",en:"My mammal inclusion initiative.",zh:"我的'哺乳动物包容计划'。",note:"include(包括)的名词"},
{w:"initiative",ipa:"ɪˈnɪʃətɪv",pos:"n.",cn:"倡议,计划",ch:["in","i","tia","tive"],ph:"tia",tier:3,t:"07:18",en:"My mammal inclusion initiative.",zh:"我的'哺乳动物包容计划'。"},
{w:"produce",ipa:"prəˈduːs",pos:"v.",cn:"产出;培养出",ch:["pro","duce"],ph:"magic-e",tier:2,t:"07:23",en:"Has produced its first police academy graduate.",zh:"培养出了它的第一位警校毕业生。"},
{w:"academy",ipa:"əˈkædəmi",pos:"n.",cn:"学院;警校",ch:["a","cad","e","my"],ph:"y",tier:2,t:"07:23",en:"Its first police academy graduate.",zh:"第一位警校毕业生。",note:"police academy = 警察学院"},
{w:"graduate",ipa:"ˈɡrædʒuət",pos:"n.",cn:"毕业生",ch:["grad","u","ate"],ph:"CVC",tier:2,t:"07:23",en:"Its first police academy graduate.",zh:"第一位警校毕业生。",note:"毕业典礼 = graduation"},
{w:"valedictorian",ipa:"ˌvælədɪkˈtɔːriən",pos:"n.",cn:"毕业生第一名(致告别辞的人)",ch:["val","e","dic","to","ri","an"],ph:"or",tier:3,t:"07:26",en:"Valedictorian of her class, ZPD's very first rabbit officer, Judy Hopps.",zh:"她那一届的第一名,动物城警局史上第一位兔子警官——朱迪·霍普斯。",note:"美国毕业典礼上全年级第一名要上台演讲,那个人就叫 valedictorian"},
{w:"rabbit",ipa:"ˈræbɪt",pos:"n.",cn:"兔子(正式)",ch:["rab","bit"],ph:"CVC",tier:1,t:"07:26",en:"ZPD's very first rabbit officer.",zh:"动物城警局史上第一位兔子警官。",note:"rabbit 正式,bunny 是昵称'兔兔'"},
{w:"assistant",ipa:"əˈsɪstənt",pos:"adj./n.",cn:"副的;助理",ch:["as","sis","tant"],ph:"st",tier:2,t:"07:38",en:"Assistant Mayor Bellwether, her badge.",zh:"副市长羊咩咩,请为她授徽。",note:"assist(帮助)+ ant(的人)"},
{w:"badge",ipa:"bædʒ",pos:"n.",cn:"警徽,徽章",ch:["b","adge"],ph:"dge",tier:2,t:"07:38",en:"Assistant Mayor Bellwether, her badge.",zh:"副市长羊咩咩,请为她授徽。",fun:"你每通一章,也会得到一枚 badge"},
{w:"bellwether",ipa:"ˈbelweðər",pos:"n.",cn:"领头羊",ch:["bell","weth","er"],ph:"th",tier:3,t:"07:38",en:"Assistant Mayor Bellwether, her badge.",zh:"副市长羊咩咩,请为她授徽。",fun:"超级彩蛋:副市长的名字 Bellwether 本身就是个单词——'挂铃铛的领头羊'。看完全片你会发现这名字取得多妙"},
{w:"privilege",ipa:"ˈprɪvəlɪdʒ",pos:"n.",cn:"荣幸;特权",ch:["priv","i","lege"],ph:"i",tier:3,t:"07:43",en:"Judy, it is my great privilege to officially assign you to the heart of Zootopia.",zh:"朱迪,我万分荣幸地正式派你前往动物城的核心地带。",note:"It is my privilege to... = 我很荣幸……(隆重场合用语)"},
{w:"officially",ipa:"əˈfɪʃəli",pos:"adv.",cn:"正式地",ch:["of","fi","cial","ly"],ph:"cial",tier:2,t:"07:46",en:"To officially assign you to the heart of Zootopia.",zh:"正式派你前往动物城的核心地带。"},
{w:"assign",ipa:"əˈsaɪn",pos:"v.",cn:"分派,委派",ch:["as","sign"],ph:"ign",tier:3,t:"07:46",en:"To officially assign you to the heart of Zootopia.",zh:"正式派你前往动物城的核心地带。",},
{w:"heart",ipa:"hɑːrt",pos:"n.",cn:"核心;心脏",ch:["h","ear","t"],ph:"ear-ar",tier:1,t:"07:46",en:"The heart of Zootopia.",zh:"动物城的心脏地带。",},
{w:"precinct",ipa:"ˈpriːsɪŋkt",pos:"n.",cn:"警区",ch:["pre","cinct"],ph:"pre",tier:3,t:"07:50",en:"Precinct One. City Center.",zh:"第一警区,市中心。",note:"美国警察剧高频词,Precinct One 是最核心的警区"},
{w:"center",ipa:"ˈsentər",pos:"n.",cn:"中心",ch:["cen","ter"],ph:"er",tier:1,t:"07:50",en:"Precinct One. City Center.",zh:"第一警区,市中心。"},
{w:"congratulations",ipa:"kənˌɡrætʃəˈleɪʃnz",pos:"n.",cn:"祝贺!",ch:["con","grat","u","la","tions"],ph:"tion",tier:2,t:"07:55",en:"Congratulations, Officer Hopps.",zh:"祝贺你,霍普斯警官。",note:"口语常缩成 Congrats!"},
{w:"kid",ipa:"kɪd",pos:"n.",cn:"小孩",ch:["k","id"],ph:"CVC",tier:1,t:"07:58",en:"This has been my dream since I was a kid.",zh:"这是我从小到大的梦想。",note:"since I was a kid = 从我小时候起"},
{w:"real",ipa:"ˈriːəl",pos:"adv.",cn:"(口语)真的,非常",ch:["r","ea","l"],ph:"ea",tier:1,t:"08:00",en:"It's a real proud day for us little guys.",zh:"对我们小个子来说,今天真是自豪的一天。"},
{w:"guy",ipa:"ɡaɪ",pos:"n.",cn:"(口语)家伙;guys=大伙儿",ch:["g","uy"],ph:"uy",tier:1,t:"08:22",en:"Guys, I've been working for this my whole life.",zh:"爸妈,我为这一天努力了一辈子。",note:"美国人喊一群人就用 guys,不分男女"},
{w:"room",ipa:"ruːm",pos:"n.",cn:"空间;房间",ch:["r","oo","m"],ph:"oo",tier:1,t:"08:03",en:"Bellwether, make room, will you?",zh:"羊咩咩,让让地方好吗?",note:"make room = 腾地方(不是'做房间'!)"},
{w:"teeth",ipa:"tiːθ",pos:"n.",cn:"牙齿(tooth的复数)",ch:["t","ee","th"],ph:"ee",tier:1,t:"08:05",en:"Let's see those teeth!",zh:"笑一个,露出牙齿!",note:"拍照喊的话,相当于'茄子!'"},
{w:"whole",ipa:"hoʊl",pos:"adj.",cn:"整个的",ch:["wh","ole"],ph:"wh",tier:1,t:"08:22",en:"I've been working for this my whole life.",zh:"我为这一天努力了一辈子。",note:"和 hole(洞)同音"},
{w:"work",ipa:"wɜːrk",pos:"v.",cn:"努力;工作",ch:["w","ork"],ph:"or",tier:1,t:"08:22",en:"I've been working for this my whole life.",zh:"我为这一天努力了一辈子。",note:"work for... = 为……而努力"},
{w:"excited",ipa:"ɪkˈsaɪtɪd",pos:"adj.",cn:"兴奋的",ch:["ex","cit","ed"],ph:"magic-e",tier:1,t:"08:25",en:"We're just a little excited for you, but terrified.",zh:"我们为你高兴,但也吓得不轻。"},
{w:"terrified",ipa:"ˈterɪfaɪd",pos:"adj.",cn:"吓坏了的",ch:["ter","ri","fied"],ph:"ied",tier:2,t:"08:25",en:"We're just a little excited for you, but terrified.",zh:"我们为你高兴,但也吓得不轻。",note:"比 scared 害怕程度深得多:scared < terrified"},
{w:"bear",ipa:"ber",pos:"n.",cn:"熊",ch:["b","ear"],ph:"ear-air",tier:1,t:"08:32",en:"We have bears to fear, too.",zh:"我们还得怕熊呢。",},
{w:"lion",ipa:"ˈlaɪən",pos:"n.",cn:"狮子",ch:["li","on"],ph:"i",tier:1,t:"08:34",en:"Say nothing on lions, and wolves.",zh:"更别提狮子和狼了。"},
{w:"wolf",ipa:"wʊlf",pos:"n.",cn:"狼(复数wolves)",ch:["w","olf"],ph:"o-u",tier:1,t:"08:34",en:"Say nothing on lions, and wolves.",zh:"更别提狮子和狼了。",note:"f 结尾变复数:wolf→wolves, leaf→leaves"},
{w:"weasel",ipa:"ˈwiːzl",pos:"n.",cn:"黄鼠狼",ch:["wea","sel"],ph:"ea",tier:2,t:"08:37",en:"You played cribbage with a weasel once?",zh:"你不是和一只黄鼠狼打过牌吗?",note:"英语里 weasel 也指'狡猾的人'"},
{w:"cribbage",ipa:"ˈkrɪbɪdʒ",pos:"n.",cn:"克里比奇纸牌游戏",ch:["crib","bage"],ph:"age",tier:3,t:"08:37",en:"You played cribbage with a weasel once?",zh:"你不是和一只黄鼠狼玩过克里比奇牌吗?",note:"一种美国老年人爱玩的纸牌游戏,用木板计分"},
{w:"cheat",ipa:"tʃiːt",pos:"v.",cn:"作弊,耍赖",ch:["ch","ea","t"],ph:"ea",tier:2,t:"08:38",en:"Yeah, he cheats like there's no tomorrow.",zh:"是啊,他耍起赖来没完没了。",note:"like there's no tomorrow = 疯狂地、没有节制地(好像没有明天一样)"},
{w:"tomorrow",ipa:"təˈmɑːroʊ",pos:"n.",cn:"明天",ch:["to","mor","row"],ph:"ow-o",tier:1,t:"08:38",en:"He cheats like there's no tomorrow.",zh:"他耍起赖来没完没了。"},
{w:"pretty",ipa:"ˈprɪti",pos:"adv.",cn:"(口语)相当,挺",ch:["pret","ty"],ph:"y",tier:1,t:"08:40",en:"You know what? Pretty much all predators.",zh:"这么说吧,差不多所有食肉动物都挺可怕。",note:"pretty much = 差不多、基本上(超高频口语)"},
{w:"full",ipa:"fʊl",pos:"adj.",cn:"充满的",ch:["f","ull"],ph:"u",tier:1,t:"08:42",en:"And Zootopia is full of them.",zh:"而动物城里全是他们。",note:"be full of... = 满是……"},
{w:"worst",ipa:"wɜːrst",pos:"adj.",cn:"最坏的",ch:["w","orst"],ph:"or",tier:1,t:"08:44",en:"And foxes are the worst.",zh:"而狐狸是最坏的。",note:"bad→worse→worst"},
{w:"point",ipa:"pɔɪnt",pos:"n.",cn:"道理;要点",ch:["p","oi","nt"],ph:"oi",tier:1,t:"08:46",en:"Your father does have a point there.",zh:"你爸爸说得还真有点道理。",note:"have a point = 说得有道理"},
{w:"biology",ipa:"baɪˈɑːlədʒi",pos:"n.",cn:"生物学;天性",ch:["bi","ol","o","gy"],ph:"y",tier:2,t:"08:48",en:"It's in their biology.",zh:"这是他们的天性。",note:"这里意思是'刻在生物基因里的'"},
{w:"happen",ipa:"ˈhæpən",pos:"v.",cn:"发生;碰巧",ch:["hap","pen"],ph:"CVC",tier:1,t:"08:48",en:"Remember what happened with Gideon Grey?",zh:"还记得吉迪恩·格雷那件事吗?"},
{w:"jerk",ipa:"dʒɜːrk",pos:"n.",cn:"(口语)混蛋,讨厌鬼",ch:["j","erk"],ph:"er-s",tier:2,t:"08:51",en:"Gideon Grey was a jerk who happens to be a fox.",zh:"吉迪恩是个混蛋,只是恰好是只狐狸而已。",note:"happen to be = 恰好是"},
{w:"nine",ipa:"naɪn",pos:"num.",cn:"九",ch:["n","ine"],ph:"magic-e",tier:1,t:"08:51",en:"When I was nine.",zh:"那时我才九岁。"},
{w:"plenty",ipa:"ˈplenti",pos:"n.",cn:"大量,很多",ch:["plen","ty"],ph:"y",tier:2,t:"08:56",en:"I know plenty of bunnies who are jerks.",zh:"我认识的兔子里混蛋也多着呢。",note:"plenty of = 很多(比 a lot of 更口语)"},
{w:"absolutely",ipa:"ˈæbsəluːtli",pos:"adv.",cn:"绝对地,当然",ch:["ab","so","lute","ly"],ph:"magic-e",tier:2,t:"08:58",en:"Sure, yeah, we all do, absolutely.",zh:"当然当然,我们都认识,绝对的。",note:"单独说 Absolutely! = 当然!(强烈同意)"},
{w:"case",ipa:"keɪs",pos:"n.",cn:"情况;案件",ch:["c","ase"],ph:"magic-e",tier:1,t:"08:58",en:"But just in case...",zh:"不过嘛,以防万一……",note:"just in case = 以防万一。case 还有'案件'的意思,破案就是 crack the case"},
{w:"package",ipa:"ˈpækɪdʒ",pos:"n.",cn:"包裹",ch:["pack","age"],ph:"age",tier:1,t:"09:01",en:"We made you a little care package to take with you.",zh:"我们给你准备了一个随身带的爱心包裹。",note:"care package = 爱心包裹(给远行家人装吃的用的)"},
{w:"snack",ipa:"snæk",pos:"n.",cn:"零食",ch:["sn","ack"],ph:"ck",tier:1,t:"09:03",en:"I put some snacks in there.",zh:"我在里面放了些零食。"},
{w:"deterrent",ipa:"dɪˈtɜːrənt",pos:"n.",cn:"威慑物;驱吓剂",ch:["de","ter","rent"],ph:"er-s",tier:3,t:"09:03",en:"This is fox deterrent.",zh:"这是驱狐剂。",fun:"彩蛋:爸爸的恐狐三件套之一——deterrent(驱吓)、repellant(驱避)、taser(电击)层层升级"},
{w:"goodness",ipa:"ˈɡʊdnəs",pos:"int.",cn:"天哪",ch:["good","ness"],ph:"oo-u",tier:2,t:"09:03",en:"Oh, for goodness sake!",zh:"哦,老天爷啊!",note:"for goodness' sake = 老天爷啊(无奈/惊讶),比说 God 更礼貌"},
{w:"safe",ipa:"seɪf",pos:"adj.",cn:"安全的",ch:["s","afe"],ph:"magic-e",tier:1,t:"09:05",en:"Yeah, it's safe to have that.",zh:"嗯,带着那个稳妥。"},
{w:"repellant",ipa:"rɪˈpelənt",pos:"n.",cn:"驱避剂",ch:["re","pel","lant"],ph:"e",tier:3,t:"09:05",en:"This is fox repellant.",zh:"这是驱狐喷雾。",note:"字幕拼的是 repellant,标准拼写是 repellent,两种都有人用"},
{w:"taser",ipa:"ˈteɪzər",pos:"n.",cn:"电击枪",ch:["ta","ser"],ph:"er",tier:3,t:"09:11",en:"She has no need for a fox taser, Stu.",zh:"她用不着驱狐电击枪,斯图。"},
{w:"need",ipa:"niːd",pos:"n./v.",cn:"需要",ch:["n","ee","d"],ph:"ee",tier:1,t:"09:11",en:"She has no need for a fox taser.",zh:"她用不着驱狐电击枪。",note:"have no need for = 用不着"},
{w:"terrific",ipa:"təˈrɪfɪk",pos:"adj.",cn:"好极了",ch:["ter","rif","ic"],ph:"i",tier:2,t:"09:16",en:"Terrific! Everyone wins!",zh:"'好极了',皆大欢喜!",note:"注意 Judy 是无奈地反着说的——学英语也要听懂'阴阳怪气'。长得像 terrified(吓坏)但意思相反!"},
{w:"win",ipa:"wɪn",pos:"v.",cn:"赢",ch:["w","in"],ph:"CVC",tier:1,t:"09:16",en:"Terrific! Everyone wins!",zh:"好极了,人人都赢!"},
{w:"arrive",ipa:"əˈraɪv",pos:"v.",cn:"到达",ch:["ar","rive"],ph:"magic-e",tier:1,t:"09:20",en:"Arriving, Zootopia Express.",zh:"动物城特快,即将进站。"},
{w:"express",ipa:"ɪkˈspres",pos:"n.",cn:"特快列车;快递",ch:["ex","press"],ph:"x",tier:2,t:"09:20",en:"Arriving, Zootopia Express.",zh:"动物城特快,即将进站。",note:"顺丰'速运'、特快列车都是 express——'快'的意思"},
{w:"everybody",ipa:"ˈevribɑːdi",pos:"pron.",cn:"每个人,大家",ch:["ev","er","y","bod","y"],ph:"y",tier:1,t:"09:45",en:"Bye everybody!",zh:"大家再见!",note:"everybody = everyone,一个意思"},
{w:"waterworks",ipa:"ˈwɔːtərwɜːrks",pos:"n.",cn:"(口语)眼泪汪汪;本义:自来水厂",ch:["wa","ter","works"],ph:"or",tier:3,t:"09:41",en:"Oh, cripes, here come the waterworks.",zh:"哎呀,眼泪又要决堤了。",note:"哭个没完被比作'自来水厂'——waterworks 口语里就指'眼泪'"},
{w:"love",ipa:"lʌv",pos:"v.",cn:"爱",ch:["l","ove"],ph:"o-u2",tier:1,t:"09:36",en:"I love you, guys.",zh:"我爱你们。"},
// ------- 基础词补卡(按"全部当作不认识"原则,一个不落) -------
{w:"year",ipa:"jɪr",pos:"n.",cn:"年",ch:["y","ear"],ph:"ear",tier:1,t:"01:06",en:"Thousands of years ago these were the forces that ruled our world.",zh:"几千年前,是这些力量统治着我们的世界。"},
{w:"back",ipa:"bæk",pos:"adv.",cn:"回到;向后",ch:["b","ack"],ph:"ck",tier:1,t:"01:42",en:"Back then, the world was divided in two.",zh:"那时候,世界被一分为二。",note:"back then = 那时候,回忆往事的开场白"},
{w:"move",ipa:"muːv",pos:"v.",cn:"移动;摆脱",ch:["m","ove"],ph:"",tier:1,t:"01:56",en:"And moved beyond our primitive savage ways.",zh:"摆脱了我们原始野蛮的生活方式。",note:"ove 在这里发 /uːv/,move 是个例外词"},
{w:"time",ipa:"taɪm",pos:"n.",cn:"时间;次",ch:["t","ime"],ph:"magic-e",tier:1,t:"01:53",en:"But over time, we evolved.",zh:"但随着时间推移,我们进化了。",note:"over time = 随着时间推移;one at a time = 一次一个"},
{w:"every",ipa:"ˈevri",pos:"adj.",cn:"每一个",ch:["ev","er","y"],ph:"y",tier:1,t:"02:04",en:"And every young mammal has multitudinous opportunities.",zh:"每一只年幼的哺乳动物都有数不清的机会。"},
{w:"hunter",ipa:"ˈhʌntər",pos:"n.",cn:"猎人",ch:["hunt","er"],ph:"er",tier:1,t:"02:19",en:"I don't have to be a lonely hunter anymore.",zh:"我再也不用当孤独的猎手了。",note:"hunt(打猎)+ er(的人)= 猎人"},
{w:"today",ipa:"təˈdeɪ",pos:"adv.",cn:"今天;如今",ch:["to","day"],ph:"ay",tier:1,t:"02:22",en:"Today I can hunt for tax exemptions.",zh:"如今我可以去搜寻免税额。"},
{w:"small",ipa:"smɔːl",pos:"adj.",cn:"小的",ch:["sm","all"],ph:"all",tier:1,t:"02:44",en:"It may seem impossible to small minds.",zh:"在目光短浅的人看来,这也许不可能。"},
{w:"away",ipa:"əˈweɪ",pos:"adv.",cn:"远离;在……之外",ch:["a","way"],ph:"ay",tier:1,t:"02:50",en:"But just 211 miles away, stands the great city of Zootopia.",zh:"但就在211英里之外,矗立着伟大的动物城。"},
{w:"good",ipa:"ɡʊd",pos:"adj.",cn:"好的",ch:["g","ood"],ph:"oo-u",tier:1,t:"03:09",en:"Thank you and good night.",zh:"谢谢大家,晚安。",note:"good night = 晚安(道别);对比 good evening = 晚上好(见面)"},
{w:"night",ipa:"naɪt",pos:"n.",cn:"夜晚",ch:["n","igh","t"],ph:"igh",tier:1,t:"03:09",en:"Thank you and good night.",zh:"谢谢大家,晚安。"},
{w:"thank",ipa:"θæŋk",pos:"v.",cn:"感谢",ch:["th","ank"],ph:"th",tier:1,t:"03:09",en:"Thank you and good night.",zh:"谢谢大家,晚安。"},
{w:"mom",ipa:"mɑːm",pos:"n.",cn:"妈妈",ch:["m","om"],ph:"CVC",tier:1,t:"03:13",en:"How your mom and me got to be so darn happy?",zh:"你妈和我怎么会这么幸福?",note:"美式 mom,英式 mum"},
{w:"happy",ipa:"ˈhæpi",pos:"adj.",cn:"幸福的,快乐的",ch:["hap","py"],ph:"y",tier:1,t:"03:13",en:"How your mom and me got to be so darn happy?",zh:"你妈和我怎么会这么幸福?"},
{w:"never",ipa:"ˈnevər",pos:"adv.",cn:"从不,永不",ch:["nev","er"],ph:"er",tier:1,t:"03:25",en:"If you don't try anything new, you'll never fail.",zh:"只要你不尝试新东西,就永远不会失败。",note:"There's never been a... = 从来没有过……"},
{w:"new",ipa:"nuː",pos:"adj.",cn:"新的",ch:["n","ew"],ph:"",tier:1,t:"03:25",en:"If you don't try anything new, you'll never fail.",zh:"只要你不尝试新东西,就永远不会失败。",note:"ew 发 /uː/:new, grew, flew"},
{w:"father",ipa:"ˈfɑːðər",pos:"n.",cn:"父亲",ch:["fa","ther"],ph:"th",tier:1,t:"03:29",en:"What your father means, hon...",zh:"你爸爸的意思是,宝贝……",note:"father 正式,dad 口语,daddy 更亲昵"},
{w:"see",ipa:"siː",pos:"v.",cn:"看见;明白",ch:["s","ee"],ph:"ee",tier:1,t:"03:21",en:"You see, that's the beauty of complacency, Jude.",zh:"你瞧,这就是安于现状的妙处。",note:"You see... = 你瞧/你懂吧(解释事情的开场)"},
{w:"dad",ipa:"dæd",pos:"n.",cn:"爸爸",ch:["d","ad"],ph:"CVC",tier:1,t:"03:52",en:"Your dad, me, your 275 brothers and sisters.",zh:"你爸、我,还有你的275个兄弟姐妹。"},
{w:"even",ipa:"ˈiːvn",pos:"adv.",cn:"甚至",ch:["e","ven"],ph:"",tier:1,t:"03:30",en:"It's gonna be difficult, impossible even.",zh:"会很难,甚至不可能。"},
{w:"get",ipa:"ɡet",pos:"v.",cn:"明白;得到",ch:["g","et"],ph:"CVC",tier:1,t:"04:07",en:"You get it, honey?",zh:"你明白吗,宝贝?",note:"get 是万能动词:get it=明白;get them=拿到它们。过去式 got"},
{w:"go",ipa:"ɡoʊ",pos:"v.",cn:"去",ch:["g","o"],ph:"o",tier:1,t:"04:14",en:"Where the heck'd she go?",zh:"她到底跑哪儿去了?"},
{w:"come",ipa:"kʌm",pos:"v.",cn:"来",ch:["c","ome"],ph:"o-u2",tier:1,t:"04:37",en:"Come and get them. But watch out.",zh:"来拿呀,不过你可当心点。",note:"Come on! = 来吧/拜托(全片高频)"},
{w:"cause",ipa:"kəz",pos:"conj.",cn:"(口语)因为(=because)",ch:["c","ause"],ph:"au",tier:1,t:"04:39",en:"Cause I'm a fox.",zh:"因为我是狐狸嘛。",note:"口语里 because 常吞成 'cause,发音像 cuz"},
{w:"nice",ipa:"naɪs",pos:"adj.",cn:"好的,不错的",ch:["n","ice"],ph:"magic-e",tier:1,t:"04:26",en:"Nice costume, loser.",zh:"戏服不错嘛,废物。",note:"这里是嘲讽语气——同一个词,语气不同意思相反"},
{w:"play",ipa:"pleɪ",pos:"v./n.",cn:"玩;戏剧",ch:["pl","ay"],ph:"ay",tier:1,t:"08:37",en:"You played cribbage with a weasel once?",zh:"你不是和一只黄鼠狼打过牌吗?",note:"stage play 里的 play 是名词'戏剧'"},
{w:"tell",ipa:"tel",pos:"v.",cn:"告诉",ch:["t","ell"],ph:"CVC",tier:1,t:"04:51",en:"Don't tell me what I know, Travis.",zh:"用不着你告诉我,特拉维斯。"},
{w:"know",ipa:"noʊ",pos:"v.",cn:"知道",ch:["kn","ow"],ph:"ow-o",tier:1,t:"05:46",en:"I don't know when to quit.",zh:"我从来不知道什么叫放弃。",note:"kn 里的 k 不发音:know, knee, knock"},
{w:"baby",ipa:"ˈbeɪbi",pos:"n.",cn:"宝宝,婴儿",ch:["ba","by"],ph:"y",tier:1,t:"04:58",en:"Cry, little baby bunny! Cry...",zh:"哭吧,小兔子宝宝!",note:"开音节 a 发字母音 /eɪ/:baby, lady"},
{w:"want",ipa:"wɑːnt",pos:"v.",cn:"想要",ch:["w","ant"],ph:"",tier:1,t:"05:14",en:"I want you to remember this moment.",zh:"我要你记住这一刻。",note:"a 跟在 w 后常变音:want, watch, was"},
{w:"think",ipa:"θɪŋk",pos:"v.",cn:"认为,想",ch:["th","ink"],ph:"th",tier:1,t:"05:16",en:"The next time you think you will ever be anything more...",zh:"下次你再幻想自己能有什么出息的时候……"},
{w:"look",ipa:"lʊk",pos:"v.",cn:"看",ch:["l","ook"],ph:"oo-u",tier:1,t:"04:56",en:"Look at her nose twitch, she is scared.",zh:"看她的鼻子在抽动,她害怕了。",note:"look at = 看……;looks bad = 看起来很糟"},
{w:"before",ipa:"bɪˈfɔːr",pos:"prep.",cn:"在……之前",ch:["be","fore"],ph:"or",tier:1,t:"06:02",en:"Master all of them before you hit the streets.",zh:"上街执勤之前必须掌握所有这些环境。"},
{w:"hit",ipa:"hɪt",pos:"v.",cn:"到达;打",ch:["h","it"],ph:"CVC",tier:1,t:"06:02",en:"Before you hit the streets.",zh:"在你们上街执勤之前。",note:"hit the streets 字面'砸向街道',实际是'上街开工'"},
{w:"girl",ipa:"ɡɜːrl",pos:"n.",cn:"女孩",ch:["g","irl"],ph:"ir",tier:1,t:"06:24",en:"You're dead, farm girl.",zh:"你死了,农场丫头。"},
{w:"square",ipa:"skwer",pos:"n.",cn:"广场;正方形",ch:["squ","are"],ph:"are",tier:1,t:"05:56",en:"Tundratown, Sahara Square, Rainforest District, to name a few.",zh:"冰川镇、撒哈拉广场、雨林区,随便举几个。",note:"天安门广场 = Tian'anmen Square"},
{w:"rainforest",ipa:"ˈreɪnfɔːrɪst",pos:"n.",cn:"雨林",ch:["rain","for","est"],ph:"ai",tier:1,t:"05:56",en:"Tundratown, Sahara Square, Rainforest District, to name a few.",zh:"冰川镇、撒哈拉广场、雨林区,随便举几个。",note:"rain(雨)+ forest(森林),合成词"},
{w:"class",ipa:"klæs",pos:"n.",cn:"班级;届",ch:["cl","ass"],ph:"",tier:1,t:"07:26",en:"Valedictorian of her class.",zh:"她那一届的第一名。"},
{w:"since",ipa:"sɪns",pos:"prep.",cn:"自从",ch:["s","ince"],ph:"",tier:1,t:"07:58",en:"This has been my dream since I was a kid.",zh:"这是我从小到大的梦想。",note:"since I was a kid = 打我小时候起"},
{w:"day",ipa:"deɪ",pos:"n.",cn:"日子,一天",ch:["d","ay"],ph:"ay",tier:1,t:"08:00",en:"It's a real proud day for us little guys.",zh:"对我们小个子来说,今天真是自豪的一天。"},
{w:"little",ipa:"ˈlɪtl",pos:"adj.",cn:"小的",ch:["lit","tle"],ph:"le",tier:1,t:"08:00",en:"It's a real proud day for us little guys.",zh:"对我们小个子来说,今天真是自豪的一天。",note:"little 带感情(小小的、可爱的/可怜的),small 只说尺寸"},
{w:"life",ipa:"laɪf",pos:"n.",cn:"一生;生活",ch:["l","ife"],ph:"magic-e",tier:1,t:"08:22",en:"I've been working for this my whole life.",zh:"我为这一天努力了一辈子。",note:"my whole life = 我这一辈子"},
{w:"far",ipa:"fɑːr",pos:"adv.",cn:"远",ch:["f","ar"],ph:"ar",tier:1,t:"08:18",en:"So far away, such a big city.",zh:"那么远,那么大的城市。"},
{w:"big",ipa:"bɪɡ",pos:"adj.",cn:"大的",ch:["b","ig"],ph:"CVC",tier:1,t:"08:18",en:"So far away, such a big city.",zh:"那么远,那么大的城市。"},
{w:"really",ipa:"ˈriːəli",pos:"adv.",cn:"真的,确实",ch:["real","ly"],ph:"ea",tier:1,t:"08:16",en:"Really, it's kind of a proud-scared combo.",zh:"说真的,是那种骄傲加害怕的混合体。"},
{w:"combo",ipa:"ˈkɑːmboʊ",pos:"n.",cn:"(口语)组合,混合体",ch:["com","bo"],ph:"o",tier:3,t:"08:16",en:"It's kind of a proud-scared combo.",zh:"是那种骄傲加害怕的混合体。",note:"combination 的口语缩写。点套餐的'套餐'也叫 combo"},
{w:"thing",ipa:"θɪŋ",pos:"n.",cn:"事情;东西",ch:["th","ing"],ph:"th",tier:1,t:"08:29",en:"The only thing we have to fear is fear itself.",zh:"我们唯一需要恐惧的,就是恐惧本身。"},
{w:"also",ipa:"ˈɔːlsoʊ",pos:"adv.",cn:"也,还",ch:["al","so"],ph:"",tier:1,t:"08:32",en:"And also bears. We have bears to fear, too.",zh:"还有熊,我们还得怕熊呢。",note:"also/too 都是'也':also 放句中,too 放句尾——这句台词俩都用了!"},
{w:"say",ipa:"seɪ",pos:"v.",cn:"说(过去式 said)",ch:["s","ay"],ph:"ay",tier:1,t:"08:34",en:"Say nothing on lions, and wolves.",zh:"更别提狮子和狼了。",note:"say nothing on... = ……就更别提了"},
{w:"nothing",ipa:"ˈnʌθɪŋ",pos:"pron.",cn:"什么也没有",ch:["no","thing"],ph:"th",tier:1,t:"08:34",en:"Say nothing on lions, and wolves.",zh:"更别提狮子和狼了。",note:"no(没)+ thing(东西)"},
{w:"like",ipa:"laɪk",pos:"prep./v.",cn:"像;喜欢",ch:["l","ike"],ph:"magic-e",tier:1,t:"08:38",en:"He cheats like there's no tomorrow.",zh:"他耍起赖来没完没了。",note:"这里是'像……一样';I like trying 里是'喜欢'"},
{w:"still",ipa:"stɪl",pos:"adv.",cn:"仍然,还",ch:["st","ill"],ph:"st",tier:1,t:"04:45",en:"That killer instinct's still in our DNA.",zh:"那种杀手本能还留在我们的DNA里。"},
{w:"sure",ipa:"ʃʊr",pos:"adj.",cn:"确定的;当然",ch:["s","ure"],ph:"",tier:1,t:"04:47",en:"I'm pretty much sure it's pronounced DNA.",zh:"我很确定,那个词读作DNA。",note:"这里 s 发 /ʃ/,是例外词:sure, sugar。单独回答 Sure! = 当然行!"},
{w:"everyone",ipa:"ˈevriwʌn",pos:"pron.",cn:"每个人",ch:["ev","er","y","one"],ph:"y",tier:1,t:"09:16",en:"Terrific! Everyone wins!",zh:"好极了,人人都赢!",note:"everyone = everybody,一个意思"},
{w:"care",ipa:"ker",pos:"n./v.",cn:"关心,照顾",ch:["c","are"],ph:"are",tier:1,t:"09:01",en:"We made you a little care package to take with you.",zh:"我们给你准备了一个随身带的爱心包裹。",note:"take care = 保重(道别常用)"},
{w:"take",ipa:"teɪk",pos:"v.",cn:"带走,拿",ch:["t","ake"],ph:"magic-e",tier:1,t:"09:01",en:"A little care package to take with you.",zh:"一个随身带着的爱心包裹。",note:"take with you = 随身带上"},
{w:"put",ipa:"pʊt",pos:"v.",cn:"放",ch:["p","ut"],ph:"u",tier:1,t:"09:03",en:"I put some snacks in there.",zh:"我在里面放了些零食。"},
{w:"check",ipa:"tʃek",pos:"v.",cn:"查看",ch:["ch","eck"],ph:"ch",tier:1,t:"09:03",en:"Check this out!",zh:"看看这个!",note:"Check this out! = 快看这个!(想给人看好东西时喊)"},
{w:"stop",ipa:"stɑːp",pos:"v.",cn:"停止",ch:["st","op"],ph:"st",tier:1,t:"09:16",en:"I will take this... to make you stop talking.",zh:"我收下这个……只求你别再说了。",note:"stop doing = 停止做某事"},
{w:"bye",ipa:"baɪ",pos:"int.",cn:"再见",ch:["b","ye"],ph:"",tier:1,t:"09:25",en:"Okay, gotta go. Bye!",zh:"好了,我得走了,再见!",note:"goodbye 的简说;gotta go = 我得走了"},
// ------- 短语卡(语块):整块记,张口就能用 -------
{w:"make the world a better place",ipa:"",pos:"短语",cn:"让世界变得更美好",ch:["make","the","world","a","better","place"],ph:"",tier:1,type:"chunk",t:"02:29",en:"And I can make the world a better place.",zh:"而我,可以让世界变得更美好。",note:"美国演讲高频句"},
{w:"give up",ipa:"",pos:"短语",cn:"放弃",ch:["give","up"],ph:"",tier:1,type:"chunk",t:"03:16",en:"Well, we gave up on our dreams, and we settled.",zh:"我们放弃了梦想,安于现状了。",note:"give up on sth = 对某事死心"},
{w:"cut it out",ipa:"",pos:"短语",cn:"住手!别闹了!",ch:["cut","it","out"],ph:"",tier:1,type:"chunk",t:"04:21",en:"Cut it out, Gideon!",zh:"住手,吉迪恩!",note:"美国小孩吵架必备句"},
{w:"watch out",ipa:"",pos:"短语",cn:"小心!当心!",ch:["watch","out"],ph:"",tier:1,type:"chunk",t:"04:37",en:"Come and get them. But watch out.",zh:"来拿呀,不过你可当心点。"},
{w:"used to",ipa:"",pos:"短语",cn:"过去常常(现在不了)",ch:["used","to"],ph:"",tier:1,type:"chunk",t:"04:42",en:"Us predators used to eat prey.",zh:"我们食肉动物过去是吃猎物的。",note:"used to 专指'以前是,现在不是了'"},
{w:"as long as",ipa:"",pos:"短语",cn:"只要",ch:["as","long","as"],ph:"",tier:1,type:"chunk",t:"04:09",en:"Just as long as you don't believe in them too much.",zh:"只要你别太当真就行。"},
{w:"to name a few",ipa:"",pos:"短语",cn:"随便举几个例子",ch:["to","name","a","few"],ph:"",tier:2,type:"chunk",t:"05:56",en:"Tundratown, Sahara Square, Rainforest District, to name a few.",zh:"冰川镇、撒哈拉广场、雨林区,随便举几个。",note:"列举完加一句,立刻高级感拉满"},
{w:"let you down",ipa:"",pos:"短语",cn:"让你失望",ch:["let","you","down"],ph:"",tier:1,type:"chunk",t:"07:57",en:"I won't let you down.",zh:"我不会让您失望的。",note:"let sb down = 让某人失望。表决心必备句"},
{w:"kind of",ipa:"",pos:"短语",cn:"(口语)有点儿",ch:["kind","of"],ph:"",tier:1,type:"chunk",t:"08:16",en:"Really, it's kind of a proud-scared combo.",zh:"说真的,是那种骄傲加害怕的混合体。",note:"口语里读作 kinda"},
{w:"pretty much",ipa:"",pos:"短语",cn:"(口语)差不多,基本上",ch:["pretty","much"],ph:"",tier:1,type:"chunk",t:"08:40",en:"Pretty much all predators.",zh:"差不多所有食肉动物。"},
{w:"just in case",ipa:"",pos:"短语",cn:"以防万一",ch:["just","in","case"],ph:"",tier:1,type:"chunk",t:"08:58",en:"But just in case, we made you a little care package.",zh:"不过以防万一,我们给你准备了个爱心包裹。"},
{w:"pull it together",ipa:"",pos:"短语",cn:"打起精神,振作起来",ch:["pull","it","together"],ph:"",tier:2,type:"chunk",t:"09:43",en:"Oh, Stu. Pull it together.",zh:"哦,斯图,振作一点。",note:"对快哭的人/慌乱的人说"},
];
