// 第八章 悬崖疗养院 Cliffside(台词 61:25-70:09)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch8.js
const WORDS = [
{w:"fluffy",ipa:"ˈflʌfi",pos:"adj.",cn:"毛茸茸的",ch:["fluf","fy"],ph:"y",tier:3,t:"61:25",en:"So fluffy!",zh:"好软好蓬!",note:"fluff(绒毛,第一章)+y"},
{w:"close",ipa:"kloʊs",pos:"adj.",cn:"近的",ch:["cl","ose"],ph:"magic-e",tier:1,t:"61:28",en:"Sheep never let me get this close!",zh:"羊从来不让我凑这么近!",note:"形容词读 /kloʊs/;“关门”的 close 读 /kloʊz/"},
{w:"wool",ipa:"wʊl",pos:"n.",cn:"羊毛",ch:["w","ool"],ph:"oo-u",tier:3,t:"61:29",en:"You can't just touch a sheep's wool!",zh:"你不能随便摸羊毛的!",note:"oo 这里读短音 /ʊ/"},
{w:"candy",ipa:"ˈkændi",pos:"n.",cn:"糖果",ch:["can","dy"],ph:"y",tier:1,t:"61:31",en:"- It's like cotton candy. - Stop it!",zh:"-跟棉花糖似的。-住手!",note:"cotton candy = 棉花糖"},
{w:"cotton",ipa:"ˈkɑːtn",pos:"n.",cn:"棉花",ch:["cot","ton"],ph:"CVC",tier:2,t:"61:31",en:"- It's like cotton candy. - Stop it!",zh:"-跟棉花糖似的。-住手!",note:"cottontail(第三章)的 cotton"},
{w:"secretary",ipa:"ˈsekrəteri",pos:"n.",cn:"秘书",ch:["se","cre","ta","ry"],ph:"e",tier:3,t:"61:47",en:"I'm more of a glorified secretary.",zh:"我其实就是个说好听点的秘书。",note:"glorified+职位 = 名头好听的…"},
{w:"vote",ipa:"voʊt",pos:"n.",cn:"选票;投票",ch:["v","ote"],ph:"magic-e",tier:2,t:"61:49",en:"I think Mayor Lionheart just wanted the sheep vote.",zh:"我看狮市长只是想要羊群的选票。"},
{w:"mug",ipa:"mʌɡ",pos:"n.",cn:"马克杯",ch:["m","ug"],ph:"CVC",tier:3,t:"61:52",en:"But he did give me that nice mug.",zh:"不过他确实送了我这个不错的杯子。"},
{w:"cancel",ipa:"ˈkænsl",pos:"v.",cn:"取消",ch:["can","cel"],ph:"c-s",tier:2,t:"62:06",en:"- Yes, sir. - I thought you were gonna cancel my afternoon.",zh:"-是,先生。-我不是让你把我下午的安排取消吗。"},
{w:"dear",ipa:"dɪr",pos:"int.",cn:"天哪;亲爱的",ch:["d","ear"],ph:"ear",tier:1,t:"62:09",en:"Oh, dear. I better go. Let me know what you find.",zh:"哎呀,我得走了。有发现随时告诉我。",note:"Oh, dear. = 哎呀"},
{w:"while",ipa:"waɪl",pos:"conj.",cn:"趁着;一会儿",ch:["wh","ile"],ph:"wh",tier:2,t:"62:15",en:"While we're young, Smellwether.",zh:"别磨蹭啦,臭味羊,趁我们还年轻。",note:"While we're young! = 快点,别耗着"},
{w:"sleep",ipa:"sliːp",pos:"v.",cn:"睡觉",ch:["sl","eep"],ph:"ee",tier:1,t:"62:19",en:"You think when she goes to sleep she counts herself?",zh:"你说她睡觉的时候,是不是数自己?",note:"英语数羊助眠(count sheep),她本人就是羊"},
{w:"bet",ipa:"bet",pos:"v.",cn:"打赌",ch:["b","et"],ph:"CVC",tier:2,t:"62:42",en:"Bet you a nickel one of them's gonna howl.",zh:"赌五分钱,他们里头准有一个要嚎。",note:"I bet... = 我敢说"},
{w:"howl",ipa:"haʊl",pos:"v.",cn:"嚎叫",ch:["h","owl"],ph:"ow",tier:2,t:"62:42",en:"Bet you a nickel one of them's gonna howl.",zh:"赌五分钱,他们里头准有一个要嚎。",note:"Night Howlers 里的 howl"},
{w:"nickel",ipa:"ˈnɪkl",pos:"n.",cn:"五分镍币",ch:["ni","ckel"],ph:"ck",tier:3,t:"62:42",en:"Bet you a nickel one of them's gonna howl.",zh:"赌五分钱,他们里头准有一个要嚎。",note:"镍做的 5 美分硬币"},
{w:"afraid",ipa:"əˈfreɪd",pos:"adj.",cn:"害怕的",ch:["a","fraid"],ph:"ai",tier:2,t:"62:51",en:"That's what Manchas was afraid of,",zh:"这就是曼查斯当时害怕的东西,",note:"be afraid of = 害怕…"},
{w:"avoid",ipa:"əˈvɔɪd",pos:"v.",cn:"避开",ch:["a","void"],ph:"oi",tier:2,t:"63:09",en:"if I wanted to avoid surveillance because I was doing something illegal,",zh:"假如我想避开监控去干点违法的事,"},
{w:"surveillance",ipa:"sərˈveɪləns",pos:"n.",cn:"监控",ch:["sur","veil","lance"],ph:"c-s",tier:3,t:"63:09",en:"if I wanted to avoid surveillance because I was doing something illegal,",zh:"假如我想避开监控去干点违法的事,",note:"under surveillance = 被监控"},
{w:"illegal",ipa:"ɪˈliːɡl",pos:"adj.",cn:"非法的",ch:["il","le","gal"],ph:"i",tier:3,t:"63:09",en:"if I wanted to avoid surveillance because I was doing something illegal,",zh:"假如我想避开监控去干点违法的事,",note:"il(不)+legal(合法的)"},
{w:"maintenance",ipa:"ˈmeɪntənəns",pos:"n.",cn:"维护,检修",ch:["main","te","nance"],ph:"ai",tier:3,t:"63:13",en:"which I never have, I would use the maintenance tunnel 6B.",zh:"当然我从没干过——我会走 6B 检修隧道。",note:"maintenance tunnel = 检修隧道"},
{w:"tunnel",ipa:"ˈtʌnl",pos:"n.",cn:"隧道",ch:["tun","nel"],ph:"CVC",tier:3,t:"63:13",en:"which I never have, I would use the maintenance tunnel 6B.",zh:"当然我从没干过——我会走 6B 检修隧道。"},
{w:"dare",ipa:"der",pos:"v.",cn:"竟敢",ch:["d","are"],ph:"are",tier:2,t:"63:28",en:"How dare you.",zh:"你好大的胆子。",note:"How dare you! = 你竟敢!"},
{w:"alley",ipa:"ˈæli",pos:"n.",cn:"小巷",ch:["al","ley"],ph:"ey-i",tier:3,t:"63:30",en:"Acacia Alley. Ficus Underpass.",zh:"金合欢巷,榕树地下道。"},
{w:"underpass",ipa:"ˈʌndərpæs",pos:"n.",cn:"地下通道",ch:["un","der","pass"],ph:"er",tier:3,t:"63:30",en:"Acacia Alley. Ficus Underpass.",zh:"金合欢巷,榕树地下道。",note:"under(下)+pass(通道)"},
{w:"canyon",ipa:"ˈkænjən",pos:"n.",cn:"峡谷",ch:["can","yon"],ph:"CVC",tier:3,t:"63:32",en:"South canyon.",zh:"南峡谷。"},
{w:"south",ipa:"saʊθ",pos:"n.",cn:"南",ch:["s","outh"],ph:"ou",tier:2,t:"63:32",en:"South canyon.",zh:"南峡谷。",note:"东南西北:east·south·west·north"},
{w:"hospital",ipa:"ˈhɑːspɪtl",pos:"n.",cn:"医院",ch:["hos","pi","tal"],ph:"i",tier:1,t:"65:00",en:"It looks like this was a hospital.",zh:"看起来这儿原来是家医院。"},
{w:"after",ipa:"ˈæftər",pos:"prep.",cn:"在…之后",ch:["af","ter"],ph:"er",tier:1,t:"65:16",en:"You know, after you, you're the cop.",zh:"这样吧,您先请,你才是警察。",note:"After you. = 您先请"},
{w:"equipment",ipa:"ɪˈkwɪpmənt",pos:"n.",cn:"设备",ch:["e","quip","ment"],ph:"qu",tier:3,t:"65:34",en:"All this equipment is brand new.",zh:"这些设备全是崭新的。",note:"equip(装备)+ment,不可数"},
{w:"huge",ipa:"hjuːdʒ",pos:"adj.",cn:"巨大的",ch:["h","uge"],ph:"g-j",tier:2,t:"65:43",en:"Yeah, huge, huge claw marks. What kind of...",zh:"对,巨大无比的爪痕。会是什么……"},
{w:"wife",ipa:"waɪf",pos:"n.",cn:"妻子",ch:["w","ife"],ph:"magic-e",tier:2,t:"66:24",en:"Your wife sent me to find you.",zh:"是您太太派我来找您的。",note:"husband(第四章)的另一半"},
{w:"missus",ipa:"ˈmɪsəz",pos:"n.",cn:"(口语)太太",ch:["mis","sus"],ph:"i",tier:3,t:"66:30",en:"Guess he's in no rush to get home to the missus.",zh:"看来他不怎么急着回家见太太。",note:"Mrs. 按读音写出来"},
{w:"include",ipa:"ɪnˈkluːd",pos:"v.",cn:"包括",ch:["in","clude"],ph:"magic-e",tier:2,t:"66:35",en:"Not including Manchas, it's... it's fourteen.",zh:"不算曼查斯的话,是……是十四个。",note:"not including = 不算…"},
{w:"hand out",ipa:"",pos:"短语",cn:"分发",ch:["hand","out"],ph:"",tier:2,type:"chunk",t:"66:38",en:"Chief Bogo handed out 14 missing mammal files.",zh:"博戈局长分发了14份哺乳动物失踪档案。",note:"用手(hand)递出去(out)"},
{w:"doctor",ipa:"ˈdɑːktər",pos:"n.",cn:"医生",ch:["doc","tor"],ph:"or-er",tier:1,t:"66:53",en:"I don't want excuses, doctor, I want answers.",zh:"我不要借口,医生,我要答案。"},
{w:"rail",ipa:"reɪl",pos:"n.",cn:"铁轨",ch:["r","ai","l"],ph:"ai",tier:3,t:"67:02",en:"who've gone off the rails crazy,",zh:"一个个疯得脱了缰,",note:"off the rails = 出轨了,失控"},
{w:"awfully",ipa:"ˈɔːfli",pos:"adv.",cn:"非常;糟糕地",ch:["aw","ful","ly"],ph:"aw",tier:3,t:"67:06",en:"Now I'd call that awfully far from doing everything!",zh:"这我可得说,离“尽全力”差得远呢!",note:"awful(糟糕)+ly,口语当“非常”用"},
{w:"consider",ipa:"kənˈsɪdər",pos:"v.",cn:"考虑",ch:["con","si","der"],ph:"er",tier:2,t:"67:08",en:"Sir, it may be time to consider their biology.",zh:"先生,也许该考虑一下它们的生物本性了。"},
{w:"biology",ipa:"baɪˈɑːlədʒi",pos:"n.",cn:"生物本性;生物学",ch:["bi","o","lo","gy"],ph:"g-j",tier:3,t:"67:08",en:"Sir, it may be time to consider their biology.",zh:"先生,也许该考虑一下它们的生物本性了。",note:"biological(第一章)的名词"},
{w:"secret",ipa:"ˈsiːkrət",pos:"n.",cn:"秘密",ch:["se","cret"],ph:"e-l",tier:2,t:"67:16",en:"We cannot keep it a secret. We need to come forward.",zh:"这事瞒不住的,我们得公开。",note:"keep it a secret = 保密"},
{w:"come forward",ipa:"",pos:"短语",cn:"站出来,公开",ch:["come","forward"],ph:"",tier:2,type:"chunk",t:"67:16",en:"We cannot keep it a secret. We need to come forward.",zh:"这事瞒不住的,我们得公开。"},
{w:"public",ipa:"ˈpʌblɪk",pos:"n.",cn:"公众",ch:["pub","lic"],ph:"CVC",tier:2,t:"67:20",en:"Hm, great idea. Tell the public.",zh:"哼,好主意啊,告诉公众。",note:"the public = 老百姓"},
{w:"ruin",ipa:"ˈruːɪn",pos:"v.",cn:"毁掉",ch:["ru","in"],ph:"ui",tier:3,t:"67:28",en:"- I'll be ruined! - Well, what does Chief Bogo say?",zh:"-我就全完了!-那博戈局长怎么说?",note:"I'll be ruined! = 我就完了!"},
{w:"security",ipa:"sɪˈkjʊrəti",pos:"n.",cn:"安保",ch:["se","cu","ri","ty"],ph:"c-s",tier:3,t:"67:40",en:"Security, sweep the area.",zh:"保安,把这片区搜一遍。",note:"喊 Security! = 叫保安"},
{w:"sweep",ipa:"swiːp",pos:"v.",cn:"清扫;排查",ch:["sw","eep"],ph:"ee",tier:2,t:"67:40",en:"Security, sweep the area.",zh:"保安,把这片区搜一遍。",note:"sweep the area = 地毯式搜查"},
{w:"area",ipa:"ˈeriə",pos:"n.",cn:"区域",ch:["a","re","a"],ph:"are",tier:2,t:"67:40",en:"Security, sweep the area.",zh:"保安,把这片区搜一遍。"},
{w:"swim",ipa:"swɪm",pos:"v.",cn:"游泳",ch:["sw","im"],ph:"CVC",tier:2,t:"67:55",en:"- Can you swim? - What?",zh:"-你会游泳吗?-什么?",note:"过去式 swam"},
{w:"impress",ipa:"ɪmˈpres",pos:"v.",cn:"使佩服",ch:["im","press"],ph:"e",tier:2,t:"68:53",en:"Wow, I'm impressed.",zh:"哇,我服了,真有你的。",note:"I'm impressed. = 我真服了(夸)"},
{w:"remain",ipa:"rɪˈmeɪn",pos:"v.",cn:"保持;剩下",ch:["re","main"],ph:"ai",tier:2,t:"68:59",en:"you have the right to remain silent. Anything you...",zh:"你有权保持沉默。你所说的一切……",note:"remain silent = 保持沉默"},
{w:"silent",ipa:"ˈsaɪlənt",pos:"adj.",cn:"沉默的",ch:["si","lent"],ph:"i-l",tier:2,t:"68:59",en:"you have the right to remain silent. Anything you...",zh:"你有权保持沉默。你所说的一切……",note:"这句是著名的“米兰达警告”"},
{w:"understand",ipa:"ˌʌndərˈstænd",pos:"v.",cn:"理解",ch:["un","der","stand"],ph:"st",tier:2,t:"69:00",en:"You don't understand, I was trying to protect the city!",zh:"你们不明白,我是为了保护这座城!",note:"过去式 understood"},
{w:"protect",ipa:"prəˈtekt",pos:"v.",cn:"保护",ch:["pro","tect"],ph:"e",tier:2,t:"69:00",en:"You don't understand, I was trying to protect the city!",zh:"你们不明白,我是为了保护这座城!"},
{w:"destroy",ipa:"dɪˈstrɔɪ",pos:"v.",cn:"摧毁",ch:["de","stroy"],ph:"oy",tier:3,t:"69:09",en:"It could destroy Zootopia.",zh:"它可能会毁掉整个动物城。"},
{w:"conference",ipa:"ˈkɑːnfərəns",pos:"n.",cn:"发布会;会议",ch:["con","fe","rence"],ph:"c-s",tier:3,t:"69:32",en:"- I'm so nervous. - Okay, press conference 101.",zh:"-我好紧张。-没事,发布会入门第一课。",note:"press conference = 记者发布会"},
{w:"nervous",ipa:"ˈnɜːrvəs",pos:"adj.",cn:"紧张的",ch:["ner","vous"],ph:"er-s",tier:2,t:"69:32",en:"- I'm so nervous. - Okay, press conference 101.",zh:"-我好紧张。-没事,发布会入门第一课。",note:"课程 101 = 入门课"},
{w:"press",ipa:"pres",pos:"n.",cn:"新闻界;按",ch:["pr","ess"],ph:"e",tier:2,t:"69:32",en:"- I'm so nervous. - Okay, press conference 101.",zh:"-我好紧张。-没事,发布会入门第一课。",note:"the press = 媒体记者"},
{w:"smart",ipa:"smɑːrt",pos:"adj.",cn:"聪明的,精明的",ch:["sm","art"],ph:"ar",tier:2,t:"69:35",en:"You wanna look smart,",zh:"你想显得胸有成竹,"},
{w:"tough",ipa:"tʌf",pos:"adj.",cn:"艰难的;硬气的",ch:["t","ough"],ph:"gh-f",tier:2,t:"69:44",en:"\"Well, was this a tough case? Yes, yes it was. You see?\"",zh:"“这案子难吗?难,当然难。”看,就这么答。",note:"a tough case = 硬骨头案子"},
{w:"partner",ipa:"ˈpɑːrtnər",pos:"n.",cn:"搭档",ch:["part","ner"],ph:"ar",tier:2,t:"70:00",en:"It would be nice to have a partner.",zh:"要是有个搭档,还挺不错的。"},
];
