// 第六章 冰川镇教父 Tundratown(台词 44:14-52:39)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch6.js
const WORDS = [
{w:"limo",ipa:"ˈlɪmoʊ",pos:"n.",cn:"加长轿车",ch:["li","mo"],ph:"o",tier:3,t:"44:19",en:"It's registered to Tundratown Limo Service.",zh:"车登记在冰川镇加长轿车公司名下。",note:"limousine 的缩略"},
{w:"register",ipa:"ˈredʒɪstər",pos:"v.",cn:"登记,注册",ch:["re","gi","ster"],ph:"g-j",tier:3,t:"44:19",en:"It's registered to Tundratown Limo Service.",zh:"车登记在冰川镇加长轿车公司名下。",note:"registered to = 登记在…名下"},
{w:"owe",ipa:"oʊ",pos:"v.",cn:"欠",ch:["owe"],ph:"ow-o",tier:3,t:"44:25",en:"Way to hustle, bud. I love you. I owe you.",zh:"干得漂亮,兄弟,爱你,这人情我记下了。",note:"I owe you. = 我欠你个人情"},
{w:"rush",ipa:"rʌʃ",pos:"n.",cn:"高峰;冲",ch:["ru","sh"],ph:"sh",tier:2,t:"44:27",en:"Hurry! We gotta beat the rush hour and...",zh:"快!我们得赶在晚高峰前面……",note:"rush hour = 早晚高峰"},
{w:"warrant",ipa:"ˈwɔːrənt",pos:"n.",cn:"搜查令",ch:["war","rant"],ph:"war",tier:3,t:"44:34",en:"And I will betcha you don't have a warrant to get in, hmm?",zh:"而且我赌你没有搜查令进不去,嗯?",note:"朱迪接着用的 probable cause = 合理根据"},
{w:"bummer",ipa:"ˈbʌmər",pos:"n.",cn:"(口语)扫兴事",ch:["bum","mer"],ph:"er",tier:3,t:"44:38",en:"- Darn it. It's a bummer. - You wasted the day on purpose.",zh:"-哎呀,真扫兴。-你是故意浪费一整天的。",note:"What a bummer! = 真扫兴!"},
{w:"purpose",ipa:"ˈpɜːrpəs",pos:"n.",cn:"目的",ch:["pur","pose"],ph:"ur",tier:2,t:"44:38",en:"- Darn it. It's a bummer. - You wasted the day on purpose.",zh:"-哎呀,真扫兴。-你是故意浪费一整天的。",note:"on purpose = 故意"},
{w:"waste",ipa:"weɪst",pos:"v.",cn:"浪费",ch:["wa","ste"],ph:"magic-e",tier:2,t:"44:38",en:"- Darn it. It's a bummer. - You wasted the day on purpose.",zh:"-哎呀,真扫兴。-你是故意浪费一整天的。"},
{w:"fake",ipa:"feɪk",pos:"adj.",cn:"假的",ch:["f","ake"],ph:"magic-e",tier:3,t:"44:42",en:"Ma'am, I have a fake badge.",zh:"女士,我这警徽是假的。",note:"反义词 real(真的)"},
{w:"pretend",ipa:"prɪˈtend",pos:"adj.",cn:"假装(的)",ch:["pre","tend"],ph:"pre",tier:3,t:"44:44",en:"I would never impede your pretend investigation.",zh:"我绝不打扰你过家家式的调查。",note:"pretend+名词 = 过家家式的"},
{w:"investigation",ipa:"ɪnˌvestɪˈɡeɪʃn",pos:"n.",cn:"调查",ch:["in","ves","ti","ga","tion"],ph:"tion",tier:3,t:"44:44",en:"I would never impede your pretend investigation.",zh:"我绝不打扰你过家家式的调查。",note:"investigate(调查)+ion"},
{w:"problem",ipa:"ˈprɑːbləm",pos:"n.",cn:"问题",ch:["pro","blem"],ph:"CVC",tier:2,t:"44:55",en:"What is your problem? Does seeing me fail",zh:"你什么毛病?看我搞砸",note:"What is your problem? = 你什么毛病?"},
{w:"somehow",ipa:"ˈsʌmhaʊ",pos:"adv.",cn:"不知怎么地",ch:["some","how"],ph:"ow",tier:3,t:"44:57",en:"somehow make you feel better about your own sad, miserable life?",zh:"就能让你对自己惨兮兮的生活好受点?",note:"some+how"},
{w:"sad",ipa:"sæd",pos:"adj.",cn:"难过的;可悲的",ch:["s","ad"],ph:"CVC",tier:1,t:"44:57",en:"somehow make you feel better about your own sad, miserable life?",zh:"就能让你对自己惨兮兮的生活好受点?"},
{w:"miserable",ipa:"ˈmɪzrəbl",pos:"adj.",cn:"惨兮兮的",ch:["mi","se","ra","ble"],ph:"le",tier:3,t:"44:57",en:"somehow make you feel better about your own sad, miserable life?",zh:"就能让你对自己惨兮兮的生活好受点?"},
{w:"throw",ipa:"θroʊ",pos:"v.",cn:"扔",ch:["thr","ow"],ph:"ow-o",tier:2,t:"45:19",en:"First off, you throw like a bunny.",zh:"第一,你扔东西软得像兔子。",note:"过去式 threw"},
{w:"sore",ipa:"sɔːr",pos:"adj.",cn:"酸痛的;气不过的",ch:["s","ore"],ph:"or",tier:2,t:"45:21",en:"Second, you're a very sore loser.",zh:"第二,你特别输不起。",note:"sore loser = 输不起的人"},
{w:"later",ipa:"ˈleɪtər",pos:"adv.",cn:"稍后",ch:["la","ter"],ph:"a-l",tier:2,t:"45:23",en:"See you later, Officer Fluff. So sad this is over.",zh:"回头见啦,绒毛警官。真“舍不得”啊。",note:"See you later. = 回头见"},
{w:"climb",ipa:"klaɪm",pos:"v.",cn:"爬",ch:["clim","b"],ph:"mb",tier:2,t:"45:32",en:"shifty lowlife climbing the fence.",zh:"有个贼眉鼠眼的家伙在翻栅栏。",note:"b 不发音:/klaɪm/"},
{w:"fence",ipa:"fens",pos:"n.",cn:"栅栏",ch:["fen","ce"],ph:"c-s",tier:3,t:"45:32",en:"shifty lowlife climbing the fence.",zh:"有个贼眉鼠眼的家伙在翻栅栏。"},
{w:"shifty",ipa:"ˈʃɪfti",pos:"adj.",cn:"贼眉鼠眼的",ch:["shif","ty"],ph:"y",tier:3,t:"45:32",en:"shifty lowlife climbing the fence.",zh:"有个贼眉鼠眼的家伙在翻栅栏。",note:"shift(挪动)+y:眼神乱瞟"},
{w:"lowlife",ipa:"ˈloʊlaɪf",pos:"n.",cn:"下三滥",ch:["low","life"],ph:"ow-o",tier:3,t:"45:32",en:"shifty lowlife climbing the fence.",zh:"有个贼眉鼠眼的家伙在翻栅栏。",note:"low(低)+life(生活):不体面的人"},
{w:"fur",ipa:"fɜːr",pos:"n.",cn:"毛皮",ch:["f","ur"],ph:"ur",tier:3,t:"45:51",en:"Polar bear fur.",zh:"北极熊的毛。"},
{w:"use",ipa:"juːz",pos:"v.",cn:"使用",ch:["u","se"],ph:"magic-e",tier:1,t:"46:01",en:"But on CD. Who still uses CDs?",zh:"还是CD装的。现在谁还听CD啊?"},
{w:"claw",ipa:"klɔː",pos:"n.",cn:"爪(带尖甲)",ch:["cl","aw"],ph:"aw",tier:3,t:"46:16",en:"Those are claw marks.",zh:"这些是爪痕。",note:"paw 是肉垫爪,claw 是尖爪"},
{w:"mark",ipa:"mɑːrk",pos:"n.",cn:"痕迹;记号",ch:["m","ark"],ph:"ar",tier:2,t:"46:16",en:"Those are claw marks.",zh:"这些是爪痕。",note:"claw marks = 爪痕"},
{w:"definitely",ipa:"ˈdefɪnətli",pos:"adv.",cn:"肯定地",ch:["de","fi","nite","ly"],ph:"ly",tier:2,t:"46:26",en:"This is him. Emmitt Otterton. He was definitely here.",zh:"就是他,埃米特·奥特顿。他肯定来过这儿。",note:"口语超高频:绝对是"},
{w:"cup",ipa:"kʌp",pos:"n.",cn:"杯子",ch:["c","up"],ph:"CVC",tier:1,t:"46:39",en:"Rat-pack music. Fancy cup.",zh:"鼠帮老歌,讲究的杯子。"},
{w:"fancy",ipa:"ˈfænsi",pos:"adj.",cn:"花哨的,高档的",ch:["fan","cy"],ph:"cy",tier:3,t:"46:39",en:"Rat-pack music. Fancy cup.",zh:"鼠帮老歌,讲究的杯子。"},
{w:"pack",ipa:"pæk",pos:"n.",cn:"一伙;打包",ch:["pa","ck"],ph:"ck",tier:2,t:"46:39",en:"Rat-pack music. Fancy cup.",zh:"鼠帮老歌,讲究的杯子。",note:"the Rat Pack = 鼠帮(歌手组合);a pack of = 一伙"},
{w:"rat",ipa:"ræt",pos:"n.",cn:"大老鼠",ch:["r","at"],ph:"CVC",tier:3,t:"46:39",en:"Rat-pack music. Fancy cup.",zh:"鼠帮老歌,讲究的杯子。",note:"mouse 小家鼠,rat 大老鼠"},
{w:"whose",ipa:"huːz",pos:"pron.",cn:"谁的",ch:["wh","ose"],ph:"wh",tier:1,t:"46:42",en:"I know whose car this is, we gotta go!",zh:"我知道这是谁的车了,快撤!"},
{w:"crime",ipa:"kraɪm",pos:"n.",cn:"犯罪",ch:["cr","ime"],ph:"magic-e",tier:2,t:"46:44",en:"The most feared crime boss in Tundratown.",zh:"冰川镇最让人闻风丧胆的黑帮老大。",note:"crime boss = 黑帮头目"},
{w:"scene",ipa:"siːn",pos:"n.",cn:"现场;场景",ch:["s","cene"],ph:"c-s",tier:3,t:"46:50",en:"I'm not leaving, this is a crime scene.",zh:"我不走,这里是案发现场。",note:"crime scene = 案发现场"},
{w:"long time no see",ipa:"",pos:"短语",cn:"好久不见",ch:["long","time","no","see"],ph:"",tier:1,type:"chunk",t:"46:58",en:"Raymond! And is that Kevin? Long time, no see.",zh:"雷蒙德!那不是凯文吗?好久不见呐。"},
{w:"speaking of",ipa:"",pos:"短语",cn:"说到这个",ch:["speaking","of"],ph:"",tier:2,type:"chunk",t:"47:01",en:"And speaking of no see, how about you forget you saw me?",zh:"既然说到“不见”,不如你们就当没见过我?"},
{w:"sake",ipa:"seɪk",pos:"n.",cn:"缘故,份上",ch:["s","ake"],ph:"magic-e",tier:3,t:"47:06",en:"For old times sake?",zh:"看在老交情的份上?",note:"for old times' sake = 看在旧日情分"},
{w:"expensive",ipa:"ɪkˈspensɪv",pos:"adj.",cn:"昂贵的",ch:["ex","pen","sive"],ph:"x",tier:2,t:"47:25",en:"I, uh... I may have sold him a very expensive wall rug",zh:"我,呃……可能卖过他一块非常昂贵的挂毯",note:"expense(花费)+ive"},
{w:"rug",ipa:"rʌɡ",pos:"n.",cn:"地毯",ch:["r","ug"],ph:"CVC",tier:3,t:"47:25",en:"I, uh... I may have sold him a very expensive wall rug",zh:"我,呃……可能卖过他一块非常昂贵的挂毯",note:"wall rug = 挂毯"},
{w:"skunk",ipa:"skʌŋk",pos:"n.",cn:"臭鼬",ch:["sk","unk"],ph:"CVC",tier:3,t:"47:29",en:"that was made from the fur of a skunk's butt.",zh:"材料是……臭鼬屁股上的毛。"},
{w:"cheese",ipa:"tʃiːz",pos:"n.",cn:"奶酪",ch:["ch","eese"],ph:"ee",tier:2,t:"47:36",en:"Oh, sweet cheese 'n crackers.",zh:"哦,奶酪脆饼在上,我的天!",note:"sweet cheese 'n crackers = 天呐(感叹)"},
{w:"cracker",ipa:"ˈkrækər",pos:"n.",cn:"薄脆饼干",ch:["crack","er"],ph:"ck",tier:3,t:"47:36",en:"Oh, sweet cheese 'n crackers.",zh:"哦,奶酪脆饼在上,我的天!",note:"crack(咔嚓)+er:一咬就碎"},
{w:"simple",ipa:"ˈsɪmpl",pos:"adj.",cn:"简单的",ch:["sim","ple"],ph:"le",tier:2,t:"48:20",en:"This is a simple misunderstanding.",zh:"这只是个小小的误会。"},
{w:"misunderstanding",ipa:"ˌmɪsʌndərˈstændɪŋ",pos:"n.",cn:"误会",ch:["mis","un","der","stan","ding"],ph:"st",tier:3,t:"48:20",en:"This is a simple misunderstanding.",zh:"这只是个小小的误会。",note:"mis(错)+understand(理解)+ing"},
{w:"daughter",ipa:"ˈdɔːtər",pos:"n.",cn:"女儿",ch:["daugh","ter"],ph:"augh",tier:2,t:"48:25",en:"on the day my daughter is to be married.",zh:"还挑在我女儿出嫁的日子。",note:"gh 不发音"},
{w:"marry",ipa:"ˈmæri",pos:"v.",cn:"结婚",ch:["mar","ry"],ph:"y",tier:2,t:"48:25",en:"on the day my daughter is to be married.",zh:"还挑在我女儿出嫁的日子。",note:"get married = 结婚"},
{w:"against",ipa:"əˈɡenst",pos:"prep.",cn:"反对;违背",ch:["a","gainst"],ph:"st",tier:2,t:"48:27",en:"Well, actually, we were brought here against our will, so.",zh:"这个嘛,其实我们是被强行带来的。",note:"against our will = 违背我们的意愿"},
{w:"certainly",ipa:"ˈsɜːrtnli",pos:"adv.",cn:"当然,确实",ch:["cer","tain","ly"],ph:"er-s",tier:2,t:"48:33",en:"and I certainly did not know about your daughter's wedding.",zh:"我也真不知道今天是令嫒的婚礼。"},
{w:"wedding",ipa:"ˈwedɪŋ",pos:"n.",cn:"婚礼",ch:["wed","ding"],ph:"CVC",tier:2,t:"48:33",en:"and I certainly did not know about your daughter's wedding.",zh:"我也真不知道今天是令嫒的婚礼。",note:"wed(结婚)+ding"},
{w:"trust",ipa:"trʌst",pos:"v.",cn:"信任",ch:["tru","st"],ph:"st",tier:2,t:"48:37",en:"I trusted you, Nicky.",zh:"我那么信任你,小尼克。"},
{w:"bread",ipa:"bred",pos:"n.",cn:"面包",ch:["br","ead"],ph:"ea-e",tier:1,t:"48:41",en:"We broke bread together.",zh:"我们一起吃过饭。",note:"break bread = 掰面包同吃(交情深)"},
{w:"break",ipa:"breɪk",pos:"v.",cn:"打破;掰开",ch:["br","eak"],ph:"ea-a",tier:1,t:"48:41",en:"We broke bread together.",zh:"我们一起吃过饭。",note:"过去式 broke"},
{w:"repay",ipa:"rɪˈpeɪ",pos:"v.",cn:"报答,偿还",ch:["re","pay"],ph:"ay",tier:3,t:"48:46",en:"And how did you repay my generosity?",zh:"你又是怎么报答我的慷慨的?",note:"re(回)+pay(付)"},
{w:"generosity",ipa:"ˌdʒenəˈrɑːsəti",pos:"n.",cn:"慷慨",ch:["ge","ne","ro","si","ty"],ph:"g-j",tier:3,t:"48:46",en:"And how did you repay my generosity?",zh:"你又是怎么报答我的慷慨的?",note:"generous(大方)的名词"},
{w:"disrespect",ipa:"ˌdɪsrɪˈspekt",pos:"v.",cn:"不尊重",ch:["dis","re","spect"],ph:"CVC",tier:3,t:"48:55",en:"You disrespected me.",zh:"你不给我脸。",note:"dis(不)+respect(尊重)"},
{w:"bury",ipa:"ˈberi",pos:"v.",cn:"埋",ch:["bu","ry"],ph:"",tier:3,t:"48:59",en:"who I buried in that skunk-butt rug.",zh:"她就裹着那块臭鼬毯下的葬。",note:"u 例外读 /e/:bury 和 berry 同音;过去式 buried"},
{w:"show",ipa:"ʃoʊ",pos:"v.",cn:"给…看;露面",ch:["sh","ow"],ph:"ow-o",tier:1,t:"49:03",en:"I told you never to show your face here again,",zh:"我说过,不许你再在这儿露面,",note:"show your face = 露面"},
{w:"snoop",ipa:"snuːp",pos:"v.",cn:"打探,偷窥",ch:["sn","oop"],ph:"oo",tier:3,t:"49:07",en:"Snooping around with this...",zh:"还带着这玩意儿到处打探……",note:"snoop around = 到处打探"},
{w:"performer",ipa:"pərˈfɔːrmər",pos:"n.",cn:"表演者",ch:["per","for","mer"],ph:"or",tier:3,t:"49:09",en:"What are you? A performer? What's with the costume?",zh:"你是干嘛的?卖艺的?穿这身行头干啥?",note:"perform(表演)+er"},
{w:"costume",ipa:"ˈkɑːstuːm",pos:"n.",cn:"戏服,行头",ch:["cos","tume"],ph:"magic-e",tier:3,t:"49:09",en:"What are you? A performer? What's with the costume?",zh:"你是干嘛的?卖艺的?穿这身行头干啥?"},
{w:"mime",ipa:"maɪm",pos:"n.",cn:"哑剧演员",ch:["m","ime"],ph:"magic-e",tier:3,t:"49:12",en:"- Sir, I am a co... - Mime!",zh:"-先生,我是名警……-哑剧演员!",note:"mime 演戏不出声,所以“不能说话”"},
{w:"speak",ipa:"spiːk",pos:"v.",cn:"说话",ch:["sp","ea","k"],ph:"ea",tier:1,t:"49:14",en:"She's a mime. This mime can not speak.",zh:"她是哑剧演员。哑剧演员不能说话。",note:"过去式 spoke"},
{w:"evidence",ipa:"ˈevɪdəns",pos:"n.",cn:"证据",ch:["e","vi","dence"],ph:"c-s",tier:3,t:"49:22",en:"And my evidence puts him in your car!",zh:"我的证据显示,他上了你的车!"},
{w:"intimidate",ipa:"ɪnˈtɪmɪdeɪt",pos:"v.",cn:"恐吓",ch:["in","ti","mi","date"],ph:"magic-e",tier:3,t:"49:24",en:"So intimidate me all you want,",zh:"所以随你怎么吓唬我,",note:"all you want = 随你便"},
{w:"request",ipa:"rɪˈkwest",pos:"n.",cn:"请求",ch:["re","quest"],ph:"qu",tier:3,t:"49:33",en:"Then I have only one request.",zh:"那我只有一个请求。"},
{w:"dance",ipa:"dæns",pos:"n.",cn:"跳舞",ch:["dan","ce"],ph:"c-s",tier:1,t:"49:48",en:"Daddy! It's time for our dance!",zh:"爸爸!该我们跳舞啦!",note:"It's time for... = 到…时间了"},
{w:"save",ipa:"seɪv",pos:"v.",cn:"救;保存",ch:["s","ave"],ph:"magic-e",tier:1,t:"50:04",en:"She's the bunny that saved my life yesterday!",zh:"她就是昨天救了我命的那只兔子!",note:"save my life = 救了我的命"},
{w:"yesterday",ipa:"ˈjestərdeɪ",pos:"n.",cn:"昨天",ch:["yes","ter","day"],ph:"ay",tier:1,t:"50:04",en:"She's the bunny that saved my life yesterday!",zh:"她就是昨天救了我命的那只兔子!"},
{w:"dress",ipa:"dres",pos:"n.",cn:"连衣裙;礼服",ch:["dr","ess"],ph:"CVC",tier:1,t:"50:11",en:"- Hi. I love your dress. - Thank you.",zh:"-你好,你的婚纱真美。-谢谢。"},
{w:"forward",ipa:"ˈfɔːrwərd",pos:"adv.",cn:"向前",ch:["for","ward"],ph:"or",tier:2,t:"50:25",en:"I will take your kindness, and pay it forward.",zh:"你的善意我收下,也会把它传递下去。",note:"pay it forward = 把善意传下去"},
{w:"kindness",ipa:"ˈkaɪndnəs",pos:"n.",cn:"善意",ch:["kind","ness"],ph:"ind",tier:3,t:"50:25",en:"I will take your kindness, and pay it forward.",zh:"你的善意我收下,也会把它传递下去。",note:"kind(好心)+ness"},
{w:"discuss",ipa:"dɪˈskʌs",pos:"v.",cn:"讨论,商量",ch:["dis","cuss"],ph:"CVC",tier:2,t:"51:02",en:"He had something important he wanted to discuss.",zh:"他说有要紧事想跟我商量。"},
{w:"pick",ipa:"pɪk",pos:"v.",cn:"挑选;接(人)",ch:["pi","ck"],ph:"ck",tier:2,t:"51:05",en:"That's why I sent that car to pick him up.",zh:"所以我才派车去接他。",note:"pick sb up = 接某人"},
{w:"attack",ipa:"əˈtæk",pos:"v.",cn:"攻击",ch:["at","ta","ck"],ph:"ck",tier:2,t:"51:11",en:"Because he was attacked.",zh:"因为他被袭击了。"},
{w:"rip",ipa:"rɪp",pos:"v.",cn:"撕,扯烂",ch:["r","ip"],ph:"CVC",tier:3,t:"51:19",en:"He went crazy. Ripped up the car.",zh:"他疯了,把车都撕烂了。",note:"rip up = 撕烂;过去式 ripped"},
{w:"driver",ipa:"ˈdraɪvər",pos:"n.",cn:"司机",ch:["dri","ver"],ph:"er",tier:1,t:"51:22",en:"Scared my driver half to death.",zh:"把我的司机吓得半死。",note:"drive(开车)+r"},
{w:"half",ipa:"hæf",pos:"n.",cn:"一半",ch:["hal","f"],ph:"al",tier:1,t:"51:22",en:"Scared my driver half to death.",zh:"把我的司机吓得半死。",note:"scared half to death = 吓得半死"},
{w:"child",ipa:"tʃaɪld",pos:"n.",cn:"孩子",ch:["chil","d"],ph:"ch",tier:1,t:"51:31",en:"My child, we may be evolved,",zh:"孩子,我们虽然进化了,",note:"复数 children"},
{w:"evolve",ipa:"ɪˈvɑːlv",pos:"v.",cn:"进化",ch:["e","vol","ve"],ph:"CVC",tier:3,t:"51:31",en:"My child, we may be evolved,",zh:"孩子,我们虽然进化了,",note:"evolved = 进化了的"},
{w:"deep",ipa:"diːp",pos:"adj.",cn:"深的",ch:["d","eep"],ph:"ee",tier:2,t:"51:35",en:"but deep down we are still animals.",zh:"但骨子里,我们仍是动物。",note:"deep down = 骨子里"},
{w:"on all fours",ipa:"",pos:"短语",cn:"四肢着地",ch:["on","all","fours"],ph:"",tier:2,type:"chunk",t:"52:21",en:"Down on all fours.",zh:"四肢着地趴下。",note:"fours = 四只脚"},
];
