// 第十一章 夜嚎者实验室 The Lab(台词 83:42-90:33)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch11.js
const WORDS = [
{w:"corner",ipa:"ˈkɔːrnər",pos:"v.",cn:"角落;垄断",ch:["cor","ner"],ph:"or",tier:2,t:"83:44",en:"Yeah,it looks like old Doug's cornered the market on Night Howlers.",zh:"看来道格老兄把“午夜嚎叫”的买卖全包圆了。",note:"corner the market = 垄断市场"},
{w:"market",ipa:"ˈmɑːrkɪt",pos:"n.",cn:"市场",ch:["mar","ket"],ph:"ar",tier:2,t:"83:44",en:"Yeah,it looks like old Doug's cornered the market on Night Howlers.",zh:"看来道格老兄把“午夜嚎叫”的买卖全包圆了。"},
{w:"cheetah",ipa:"ˈtʃiːtə",pos:"n.",cn:"猎豹",ch:["chee","tah"],ph:"ee",tier:3,t:"84:34",en:"Cheetah in Sahara Square. Got it.",zh:"撒哈拉广场,目标猎豹。收到。",note:"洪金豹就是 cheetah"},
{w:"window",ipa:"ˈwɪndoʊ",pos:"n.",cn:"窗户",ch:["win","dow"],ph:"ow-o",tier:1,t:"84:44",en:"through the open window of a moving car.",zh:"隔着行驶汽车打开的车窗(射中目标)。"},
{w:"buzz",ipa:"bʌz",pos:"v.",cn:"蜂鸣;呼叫",ch:["b","uzz"],ph:"zz",tier:3,t:"85:00",en:"Yeah, I'll buzz you when it's done.",zh:"行,办完了我呼你。",note:"buzz sb = 给某人打个短讯/电话"},
{w:"whichever",ipa:"wɪtʃˈevər",pos:"pron.",cn:"无论哪个",ch:["which","e","ver"],ph:"wh",tier:3,t:"85:03",en:"You know, whichever comes first.",zh:"你懂的,哪个先来算哪个。",note:"which+ever,whatever 一家"},
{w:"latte",ipa:"ˈlɑːteɪ",pos:"n.",cn:"拿铁",ch:["lat","te"],ph:"",tier:3,t:"85:06",en:"Hey, Doug, open up! We've got your latte.",zh:"喂,道格,开门!你的拿铁到了。",note:"意大利语借词,读 /ˈlɑːteɪ/"},
{w:"extra",ipa:"ˈekstrə",pos:"adj.",cn:"额外的",ch:["ex","tra"],ph:"x",tier:2,t:"85:24",en:"You better have the extra foam this time.",zh:"这回最好多加了奶泡。",note:"extra+名词 = 多加的…"},
{w:"foam",ipa:"foʊm",pos:"n.",cn:"泡沫",ch:["f","oam"],ph:"oa",tier:3,t:"85:24",en:"You better have the extra foam this time.",zh:"这回最好多加了奶泡。",note:"extra foam = 多加奶泡"},
{w:"conductor",ipa:"kənˈdʌktər",pos:"n.",cn:"列车长;指挥",ch:["con","duc","tor"],ph:"or-er",tier:3,t:"85:42",en:"Oh, great, you're a conductor now, huh?",zh:"行啊,你这就当上列车长了?",note:"conduct(引导)+or"},
{w:"miracle",ipa:"ˈmɪrəkl",pos:"n.",cn:"奇迹",ch:["mi","ra","cle"],ph:"le",tier:3,t:"85:45",en:"It would take a miracle to get this rustbucket going.",zh:"要让这堆破铜烂铁跑起来,得靠奇迹。",note:"take a miracle = 得靠奇迹"},
{w:"lab",ipa:"læb",pos:"n.",cn:"实验室",ch:["l","ab"],ph:"CVC",tier:2,t:"85:52",en:"We kinda got a situation at the lab. It just got worse!",zh:"实验室这边出了点状况,而且越来越糟!",note:"laboratory 的缩略(同 app、info)"},
{w:"situation",ipa:"ˌsɪtʃuˈeɪʃn",pos:"n.",cn:"状况",ch:["si","tu","a","tion"],ph:"tion",tier:2,t:"85:52",en:"We kinda got a situation at the lab. It just got worse!",zh:"实验室这边出了点状况,而且越来越糟!",note:"got a situation = 出状况了"},
{w:"mission",ipa:"ˈmɪʃn",pos:"n.",cn:"任务",ch:["mis","sion"],ph:"sion",tier:2,t:"85:57",en:"Mission accomplished.",zh:"任务完成。",note:"Mission accomplished. = 大功告成"},
{w:"accomplish",ipa:"əˈkɑːmplɪʃ",pos:"v.",cn:"完成",ch:["ac","com","plish"],ph:"sh",tier:3,t:"85:57",en:"Mission accomplished.",zh:"任务完成。"},
{w:"premature",ipa:"ˌpriːməˈtʃʊr",pos:"adj.",cn:"为时过早的",ch:["pre","ma","ture"],ph:"pre",tier:3,t:"85:59",en:"Would it be premature for me to do a little victory toot-toot?",zh:"我现在来一段胜利嘟嘟,会不会早了点?",note:"pre(提前)+mature(成熟)"},
{w:"victory",ipa:"ˈvɪktəri",pos:"n.",cn:"胜利",ch:["vic","to","ry"],ph:"y",tier:2,t:"85:59",en:"Would it be premature for me to do a little victory toot-toot?",zh:"我现在来一段胜利嘟嘟,会不会早了点?",note:"victory toot-toot = 胜利嘟嘟"},
{w:"bucket",ipa:"ˈbʌkɪt",pos:"n.",cn:"桶;(bucket list)愿望清单",ch:["bu","cket"],ph:"ck",tier:3,t:"86:06",en:"Well, I can cross that off the bucket list.",zh:"好嘛,这件事能从愿望清单上划掉了。",note:"bucket list = 此生必做清单"},
{w:"cross",ipa:"krɔːs",pos:"v.",cn:"划掉;穿过",ch:["cr","oss"],ph:"CVC",tier:2,t:"86:06",en:"Well, I can cross that off the bucket list.",zh:"好嘛,这件事能从愿望清单上划掉了。",note:"cross off the list = 从清单划掉"},
{w:"list",ipa:"lɪst",pos:"n.",cn:"清单",ch:["li","st"],ph:"st",tier:2,t:"86:06",en:"Well, I can cross that off the bucket list.",zh:"好嘛,这件事能从愿望清单上划掉了。"},
{w:"hail",ipa:"heɪl",pos:"n.",cn:"冰雹",ch:["h","ai","l"],ph:"ai",tier:3,t:"86:24",en:"Maybe that's just hail.",zh:"也许只是下冰雹呢。",note:"其实是羊在开枪"},
{w:"incoming",ipa:"ˈɪnkʌmɪŋ",pos:"adj.",cn:"来袭的",ch:["in","co","ming"],ph:"i",tier:3,t:"86:35",en:"Incoming!",zh:"小心,来了!",note:"Incoming! = 有东西砸过来了!"},
{w:"speed",ipa:"spiːd",pos:"n.",cn:"速度;加速",ch:["sp","eed"],ph:"ee",tier:2,t:"87:08",en:"Speed up, Nick. Speed up!",zh:"加速,尼克,快加速!",note:"speed up = 加速"},
{w:"train",ipa:"treɪn",pos:"n.",cn:"火车",ch:["tr","ai","n"],ph:"ai",tier:2,t:"87:09",en:"There's another train coming!",zh:"对面又来了一列火车!"},
{w:"except",ipa:"ɪkˈsept",pos:"prep.",cn:"除了",ch:["ex","cept"],ph:"x",tier:2,t:"88:08",en:"Yeah. All, except for this.",zh:"是啊,全没了——除了这个。",note:"except for = 除了…"},
{w:"cut",ipa:"kʌt",pos:"v.",cn:"切;抄(近路)",ch:["c","ut"],ph:"CVC",tier:2,t:"88:16",en:"Cut through the Natural History Museum.",zh:"从自然历史博物馆抄近路穿过去。",note:"cut through = 抄近道穿过"},
{w:"history",ipa:"ˈhɪstəri",pos:"n.",cn:"历史",ch:["hi","sto","ry"],ph:"y",tier:2,t:"88:16",en:"Cut through the Natural History Museum.",zh:"从自然历史博物馆抄近路穿过去。"},
{w:"museum",ipa:"mjuˈziːəm",pos:"n.",cn:"博物馆",ch:["mu","se","um"],ph:"e-l",tier:2,t:"88:16",en:"Cut through the Natural History Museum.",zh:"从自然历史博物馆抄近路穿过去。"},
{w:"natural",ipa:"ˈnætʃrəl",pos:"adj.",cn:"自然的",ch:["na","tu","ral"],ph:"CVC",tier:2,t:"88:16",en:"Cut through the Natural History Museum.",zh:"从自然历史博物馆抄近路穿过去。",note:"nature(自然)+al"},
{w:"dart",ipa:"dɑːrt",pos:"v.",cn:"用镖射;飞镖",ch:["d","art"],ph:"ar",tier:3,t:"88:38",en:"Someone's darting predators with a serum.",zh:"有人在用药剂镖射捕食动物。",note:"dart sb with = 用镖射某人"},
{w:"serum",ipa:"ˈsɪrəm",pos:"n.",cn:"血清,药剂",ch:["se","rum"],ph:"",tier:3,t:"88:38",en:"Someone's darting predators with a serum.",zh:"有人在用药剂镖射捕食动物。",note:"读 /ˈsɪrəm/"},
{w:"ahead",ipa:"əˈhed",pos:"adv.",cn:"在前面",ch:["a","head"],ph:"ea-e",tier:2,t:"88:53",en:"I'll go ahead and I'll take that case now.",zh:"那我就却之不恭,把箱子收下啦。",note:"go ahead = 来吧,动手吧"},
{w:"relax",ipa:"rɪˈlæks",pos:"v.",cn:"放松",ch:["re","lax"],ph:"x",tier:2,t:"89:21",en:"Okay. Now, just relax.",zh:"好了,现在放松点。"},
{w:"blueberry",ipa:"ˈbluːberi",pos:"n.",cn:"蓝莓",ch:["blue","ber","ry"],ph:"ue",tier:3,t:"89:24",en:"- Blueberry? - Pass.",zh:"-来颗蓝莓?-免了。",note:"blue+berry(浆果)"},
{w:"pass",ipa:"pæs",pos:"v.",cn:"传递;(口语)不要",ch:["p","ass"],ph:"CVC",tier:2,t:"89:24",en:"- Blueberry? - Pass.",zh:"-来颗蓝莓?-免了。",note:"Pass. = 不用了,跳过"},
{w:"behind",ipa:"bɪˈhaɪnd",pos:"prep.",cn:"在后面",ch:["be","hind"],ph:"ind",tier:1,t:"89:33",en:"I'm not gonna leave you behind, that's not happening.",zh:"我不会丢下你的,想都别想。",note:"leave sb behind = 丢下某人"},
{w:"underestimate",ipa:"ˌʌndərˈestɪmeɪt",pos:"v.",cn:"低估",ch:["un","der","e","sti","mate"],ph:"magic-e",tier:3,t:"89:40",en:"Underestimated. Underappreciated.",zh:"被低估,被小瞧。",note:"under(低)+estimate(估计)"},
{w:"sick",ipa:"sɪk",pos:"adj.",cn:"生病的;烦透的",ch:["s","ick"],ph:"ck",tier:2,t:"89:45",en:"Aren't you sick of it?",zh:"你就不烦吗?",note:"sick of = 烦透了"},
{w:"outnumber",ipa:"ˌaʊtˈnʌmbər",pos:"v.",cn:"数量超过",ch:["out","num","ber"],ph:"ou",tier:3,t:"89:53",en:"But prey outnumber predators 10 to 1.",zh:"但猎物的数量是捕食动物的十倍。",note:"out+number:数量压过"},
{w:"common",ipa:"ˈkɑːmən",pos:"adj.",cn:"共同的;常见的",ch:["com","mon"],ph:"CVC",tier:2,t:"90:02",en:"90% of the population united against a common enemy.",zh:"全城九成的动物,联合对抗一个共同的敌人。",note:"common enemy = 共同的敌人"},
{w:"enemy",ipa:"ˈenəmi",pos:"n.",cn:"敌人",ch:["e","ne","my"],ph:"y",tier:2,t:"90:02",en:"90% of the population united against a common enemy.",zh:"全城九成的动物,联合对抗一个共同的敌人。"},
{w:"population",ipa:"ˌpɑːpjuˈleɪʃn",pos:"n.",cn:"人口",ch:["po","pu","la","tion"],ph:"tion",tier:2,t:"90:02",en:"90% of the population united against a common enemy.",zh:"全城九成的动物,联合对抗一个共同的敌人。"},
{w:"unite",ipa:"juˈnaɪt",pos:"v.",cn:"联合",ch:["u","nite"],ph:"magic-e",tier:2,t:"90:02",en:"90% of the population united against a common enemy.",zh:"全城九成的动物,联合对抗一个共同的敌人。",note:"united against = 联合对抗"},
{w:"unstoppable",ipa:"ʌnˈstɑːpəbl",pos:"adj.",cn:"挡不住的",ch:["un","stop","pa","ble"],ph:"le",tier:3,t:"90:07",en:"We'll be unstoppable.",zh:"我们将势不可挡。",note:"un+stop+able"},
];
