// 第九章 发布会风波 Press Conference(台词 70:09-76:01)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch9.js
const WORDS = [
{w:"different",ipa:"ˈdɪfrənt",pos:"adj.",cn:"不同的",ch:["dif","fe","rent"],ph:"i",tier:2,t:"70:46",en:"Are they all different species? Yes. Yes, they are.",zh:"它们是不同物种吗?是,是的。",note:"difference(第三章)的形容词"},
{w:"species",ipa:"ˈspiːʃiːz",pos:"n.",cn:"物种",ch:["spe","cies"],ph:"e-l",tier:3,t:"70:46",en:"Are they all different species? Yes. Yes, they are.",zh:"它们是不同物种吗?是,是的。",note:"单复数同形"},
{w:"connection",ipa:"kəˈnekʃn",pos:"n.",cn:"联系",ch:["con","nec","tion"],ph:"tion",tier:2,t:"70:52",en:"Okay, so what is the connection?",zh:"好,那它们之间有什么联系?",note:"connect(连接)+ion"},
{w:"member",ipa:"ˈmembər",pos:"n.",cn:"成员",ch:["mem","ber"],ph:"er",tier:2,t:"70:55",en:"they are all members of the predator family.",zh:"它们都属于捕食动物家族。"},
{w:"accurate",ipa:"ˈækjərət",pos:"adj.",cn:"准确的",ch:["ac","cu","rate"],ph:"ate-x",tier:3,t:"71:01",en:"That is accu.. Yes, that is accurate, yes.",zh:"这个说法很准……对,准确,是的。"},
{w:"component",ipa:"kəmˈpoʊnənt",pos:"n.",cn:"成分",ch:["com","po","nent"],ph:"o",tier:3,t:"71:15",en:"A biological component.",zh:"某种生物成分。",note:"闯下大祸的就是这句话"},
{w:"elaborate",ipa:"ɪˈlæbəreɪt",pos:"v.",cn:"详细说明",ch:["e","la","bo","rate"],ph:"magic-e",tier:3,t:"71:21",en:"In their DNA, can you elaborate on that, please?",zh:"在它们的DNA里?能展开讲讲吗?",note:"elaborate on = 展开讲讲"},
{w:"survive",ipa:"sərˈvaɪv",pos:"v.",cn:"存活下来",ch:["sur","vive"],ph:"magic-e",tier:2,t:"71:28",en:"Eh, predators survived through their...",zh:"呃,捕食动物能存活至今,靠的是……",note:"survive through = 靠…活下来"},
{w:"reason",ipa:"ˈriːzn",pos:"n.",cn:"原因",ch:["rea","son"],ph:"ea",tier:2,t:"71:36",en:"For whatever reason,",zh:"不知道出于什么原因,",note:"for whatever reason = 不知为什么"},
{w:"revert",ipa:"rɪˈvɜːrt",pos:"v.",cn:"退回,变回",ch:["re","vert"],ph:"er-s",tier:3,t:"71:37",en:"they seem to be reverting back to their primitive, savage ways.",zh:"它们似乎正退回原始野蛮的状态。",note:"revert back to = 退回到"},
{w:"possible",ipa:"ˈpɑːsəbl",pos:"adj.",cn:"可能的",ch:["pos","si","ble"],ph:"le",tier:2,t:"71:48",en:"It is possible. So, we must be vigilant.",zh:"有这个可能。所以我们必须保持警惕。",note:"impossible(第一章)去掉 im"},
{w:"vigilant",ipa:"ˈvɪdʒɪlənt",pos:"adj.",cn:"警觉的",ch:["vi","gi","lant"],ph:"g-j",tier:3,t:"71:48",en:"It is possible. So, we must be vigilant.",zh:"有这个可能。所以我们必须保持警惕。",note:"be vigilant = 提高警惕"},
{w:"mandatory",ipa:"ˈmændətɔːri",pos:"adj.",cn:"强制的",ch:["man","da","to","ry"],ph:"or",tier:3,t:"71:57",en:"Have you considered a mandatory quarantine on predators?",zh:"你们考虑过对捕食动物强制隔离吗?"},
{w:"quarantine",ipa:"ˈkwɔːrəntiːn",pos:"n.",cn:"隔离",ch:["qua","ran","tine"],ph:"qu",tier:3,t:"71:57",en:"Have you considered a mandatory quarantine on predators?",zh:"你们考虑过对捕食动物强制隔离吗?"},
{w:"chance",ipa:"tʃæns",pos:"n.",cn:"机会",ch:["chan","ce"],ph:"c-s",tier:2,t:"72:12",en:"That went so fast, I didn't get a chance to",zh:"刚才太快了,我都没来得及",note:"get a chance to = 有机会…"},
{w:"mention",ipa:"ˈmenʃn",pos:"v.",cn:"提到",ch:["men","tion"],ph:"tion",tier:2,t:"72:13",en:"mention you or say anything about how we...",zh:"提到你,也没说咱们是怎么……"},
{w:"clearly",ipa:"ˈklɪrli",pos:"adv.",cn:"清楚地;明摆着",ch:["clear","ly"],ph:"ear",tier:2,t:"72:19",en:"\"Clearly there's a biological component?\"",zh:"“明摆着有生物成分的作用”?",note:"clear(第七章)+ly"},
{w:"serious",ipa:"ˈsɪriəs",pos:"adj.",cn:"认真的;严重的",ch:["se","ri","ous"],ph:"i",tier:2,t:"72:27",en:"Are you serious?",zh:"你是认真的吗?",note:"Are you serious? = 你没开玩笑吧?"},
{w:"state",ipa:"steɪt",pos:"v.",cn:"陈述;州",ch:["st","ate"],ph:"magic-e",tier:3,t:"72:29",en:"I just stated the facts of the case.",zh:"我只是陈述了案件的事实。",note:"state the facts = 摆事实"},
{w:"fact",ipa:"fækt",pos:"n.",cn:"事实",ch:["f","act"],ph:"CVC",tier:2,t:"72:29",en:"I just stated the facts of the case.",zh:"我只是陈述了案件的事实。"},
{w:"carry",ipa:"ˈkæri",pos:"v.",cn:"携带",ch:["car","ry"],ph:"y",tier:2,t:"72:46",en:"you need to carry around fox repellant?",zh:"就得随身带着驱狐喷雾?",note:"carry around = 随身带着"},
{w:"notice",ipa:"ˈnoʊtɪs",pos:"v.",cn:"注意到",ch:["no","tice"],ph:"c-s",tier:2,t:"72:50",en:"notice that little item the first time we met.",zh:"咱们头回见面,我就注意到那小玩意了。"},
{w:"nuts",ipa:"nʌts",pos:"adj.",cn:"(口语)发疯的",ch:["n","uts"],ph:"CVC",tier:3,t:"72:58",en:"Do you think I might go nuts?",zh:"你觉得我也会发疯吗?",note:"go nuts = 发疯;本义坚果"},
{w:"believe in",ipa:"",pos:"短语",cn:"信任,信赖(某人)",ch:["believe","in"],ph:"",tier:1,type:"chunk",t:"73:13",en:"Just when I thought somebody actually believed in me, huh?",zh:"我还以为真有人信我呢,呵。",note:"believe sb = 信某句话;believe in sb = 信这个人"},
{w:"best",ipa:"best",pos:"adj.",cn:"最好的",ch:["be","st"],ph:"st",tier:1,t:"73:16",en:"Probably best if you don't have a predator as a partner.",zh:"搭档不是捕食动物,对你大概最好。",note:"good→better→best"},
{w:"threaten",ipa:"ˈθretn",pos:"v.",cn:"威胁",ch:["threa","ten"],ph:"ea-e",tier:3,t:"73:28",en:"Officer Hopps, were you just threatened by that predator?",zh:"霍普斯警官,那只捕食动物刚才威胁你了吗?",note:"threat(威胁)+en"},
{w:"grip",ipa:"ɡrɪp",pos:"v.",cn:"紧抓;笼罩",ch:["gr","ip"],ph:"CVC",tier:3,t:"73:39",en:"More bad news in this city gripped by fear.",zh:"被恐惧攥住的城市,又传来坏消息。",note:"gripped by fear = 被恐惧笼罩"},
{w:"condition",ipa:"kənˈdɪʃn",pos:"n.",cn:"状况",ch:["con","di","tion"],ph:"tion",tier:2,t:"73:41",en:"A caribou is in critical condition.",zh:"一头驯鹿伤势危重。",note:"in critical condition = 伤势危重"},
{w:"critical",ipa:"ˈkrɪtɪkl",pos:"adj.",cn:"危重的;关键的",ch:["cri","ti","cal"],ph:"i",tier:3,t:"73:41",en:"A caribou is in critical condition.",zh:"一头驯鹿伤势危重。"},
{w:"victim",ipa:"ˈvɪktɪm",pos:"n.",cn:"受害者",ch:["vic","tim"],ph:"i",tier:3,t:"73:43",en:"The victim of a mauling by a savage polar bear.",zh:"被一头发狂北极熊撕咬的受害者。",note:"maul(第一章“撕咬”)的受害人"},
{w:"violence",ipa:"ˈvaɪələns",pos:"n.",cn:"暴力",ch:["vi","o","lence"],ph:"i-l",tier:3,t:"73:52",en:"violence to traditionally predatory animals.",zh:"把暴力事件与传统捕食动物联系起来。",note:"violation(第二章)的兄弟词"},
{w:"meanwhile",ipa:"ˈmiːnwaɪl",pos:"adv.",cn:"与此同时",ch:["mean","while"],ph:"ea",tier:3,t:"73:56",en:"Meanwhile, a peace rally",zh:"与此同时,一场和平集会",note:"mean+while(其间)"},
{w:"rally",ipa:"ˈræli",pos:"n.",cn:"集会",ch:["ral","ly"],ph:"y",tier:3,t:"73:56",en:"Meanwhile, a peace rally",zh:"与此同时,一场和平集会",note:"peace rally = 和平集会"},
{w:"organize",ipa:"ˈɔːrɡənaɪz",pos:"v.",cn:"组织",ch:["or","ga","nize"],ph:"magic-e",tier:2,t:"73:57",en:"organized by popstar Gazelle was marred by protest.",zh:"由歌星羚羊天后发起,却被抗议搅了局。"},
{w:"protest",ipa:"ˈproʊtest",pos:"n.",cn:"抗议",ch:["pro","test"],ph:"o",tier:3,t:"73:57",en:"organized by popstar Gazelle was marred by protest.",zh:"由歌星羚羊天后发起,却被抗议搅了局。"},
{w:"forest",ipa:"ˈfɔːrɪst",pos:"n.",cn:"森林",ch:["fo","rest"],ph:"or",tier:2,t:"74:01",en:"- Go back to the forest, predator! - I am from the savannah!",zh:"-滚回森林去,捕食动物!-我是草原来的!",note:"rainforest = rain+forest"},
{w:"savannah",ipa:"səˈvænə",pos:"n.",cn:"稀树草原",ch:["sa","van","nah"],ph:"CVC",tier:3,t:"74:01",en:"- Go back to the forest, predator! - I am from the savannah!",zh:"-滚回森林去,捕食动物!-我是草原来的!",note:"第二章的 Savanna Central 就是它"},
{w:"diverse",ipa:"daɪˈvɜːrs",pos:"adj.",cn:"多元的",ch:["di","verse"],ph:"er-s",tier:3,t:"74:07",en:"It's a crazy, beautiful, diverse city.",zh:"这是座疯狂、美丽、多元的城市。",note:"名词 diversity = 多样性"},
{w:"celebrate",ipa:"ˈselɪbreɪt",pos:"v.",cn:"庆祝;赞美",ch:["ce","le","brate"],ph:"magic-e",tier:2,t:"74:10",en:"Where we celebrate our differences.",zh:"在这里,我们为彼此的不同喝彩。"},
{w:"blame",ipa:"bleɪm",pos:"n.",cn:"责怪",ch:["bl","ame"],ph:"magic-e",tier:3,t:"74:19",en:"We don't just blindly assign blame.",zh:"我们不会闭着眼睛乱扣帽子。",note:"assign blame = 归咎,把责任算到谁头上"},
{w:"blindly",ipa:"ˈblaɪndli",pos:"adv.",cn:"盲目地",ch:["blind","ly"],ph:"ind",tier:3,t:"74:19",en:"We don't just blindly assign blame.",zh:"我们不会闭着眼睛乱扣帽子。",note:"blind(瞎)+ly"},
{w:"irresponsible",ipa:"ˌɪrɪˈspɑːnsəbl",pos:"adj.",cn:"不负责任的",ch:["ir","re","spon","si","ble"],ph:"le",tier:3,t:"74:30",en:"But it's irresponsible to label all predators as savages.",zh:"但把所有捕食动物都打成野兽,是不负责任的。",note:"ir(不)+responsible(负责)"},
{w:"label",ipa:"ˈleɪbl",pos:"v.",cn:"贴标签",ch:["la","bel"],ph:"a-l",tier:3,t:"74:30",en:"But it's irresponsible to label all predators as savages.",zh:"但把所有捕食动物都打成野兽,是不负责任的。",note:"label A as B = 给 A 扣上 B 的帽子"},
{w:"divide",ipa:"dɪˈvaɪd",pos:"v.",cn:"分裂,分开",ch:["di","vide"],ph:"magic-e",tier:2,t:"74:45",en:"We cannot let fear divide us.",zh:"我们不能让恐惧分裂我们。",note:"羚羊天后的名句"},
{w:"record",ipa:"ˈrekərd",pos:"n.",cn:"档案;记录",ch:["re","cord"],ph:"e",tier:2,t:"75:23",en:"They're gonna move me to records. It's downstairs.",zh:"他们要把我调去档案科,在楼下。",note:"records = 档案科"},
{w:"downstairs",ipa:"ˌdaʊnˈsterz",pos:"adv.",cn:"楼下",ch:["down","stairs"],ph:"ow",tier:3,t:"75:23",en:"They're gonna move me to records. It's downstairs.",zh:"他们要把我调去档案科,在楼下。",note:"down+stairs(楼梯)"},
{w:"boiler",ipa:"ˈbɔɪlər",pos:"n.",cn:"锅炉",ch:["boi","ler"],ph:"oi",tier:3,t:"75:27",en:"It's by the boiler.",zh:"就挨着锅炉。",note:"boil(烧开)+er"},
];
