// 第十二章 博物馆决战 Natural History Museum(台词 90:33-片尾)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch12.js
const WORDS = [
{w:"stay",ipa:"steɪ",pos:"v.",cn:"待着,停留",ch:["st","ay"],ph:"ay",tier:2,t:"90:33",en:"Well, you should have just stayed on the carrot farm, huh?",zh:"你就该老老实实待在胡萝卜农场,不是吗?",note:"stay in power = 一直掌权"},
{w:"headline",ipa:"ˈhedlaɪn",pos:"n.",cn:"头条",ch:["head","line"],ph:"ea-e",tier:3,t:"91:18",en:"Gosh! Think of the headline!",zh:"老天,想想那头条标题!",note:"head+line:报纸大标题"},
{w:"power",ipa:"ˈpaʊər",pos:"n.",cn:"权力;力量",ch:["pow","er"],ph:"ow",tier:2,t:"91:26",en:"Prey fears predator, and you stay in power?",zh:"猎物怕捕食者,你就能一直掌权?",note:"in power = 掌权"},
{w:"milk",ipa:"mɪlk",pos:"v.",cn:"牛奶;演过头",ch:["m","ilk"],ph:"i",tier:1,t:"91:59",en:"All right, you know you're milking it.",zh:"行了,你自己知道你这是在飙演技。",note:"milk it = 把戏做足,演过头"},
{w:"lay",ipa:"leɪ",pos:"v.",cn:"摆放,铺陈",ch:["l","ay"],ph:"ay",tier:3,t:"92:04",en:"You laid it all out beautifully.",zh:"你全都交代得明明白白。",note:"laid it all out = 和盘托出;过去式 laid"},
{w:"delicious",ipa:"dɪˈlɪʃəs",pos:"adj.",cn:"美味的",ch:["de","li","cious"],ph:"cious",tier:2,t:"92:15",en:"They are delicious. You should try some.",zh:"味道好极了,你真该尝尝。"},
{w:"frame",ipa:"freɪm",pos:"v.",cn:"陷害;框",ch:["fr","ame"],ph:"magic-e",tier:2,t:"92:18",en:"I framed Lionheart, I can frame you too.",zh:"我能陷害狮市长,就能陷害你。",note:"frame sb = 栽赃陷害"},
{w:"boom",ipa:"buːm",pos:"int.",cn:"嘭!搞定!",ch:["b","oom"],ph:"oo",tier:3,t:"92:32",en:"It's called a hustle, Sweetheart. Boom!",zh:"这叫套路,小甜心。嘭,搞定!",note:"得意时的拟声词"},
{w:"bar",ipa:"bɑːr",pos:"n.",cn:"栏杆;条",ch:["b","ar"],ph:"ar",tier:3,t:"92:42",en:"Former mayor, Dawn Bellwether is behind bars today,",zh:"前市长道恩·羊咩咩今日锒铛入狱,",note:"behind bars = 蹲监狱(bar = 铁栏杆)"},
{w:"guilty",ipa:"ˈɡɪlti",pos:"adj.",cn:"有罪的",ch:["guil","ty"],ph:"gu",tier:2,t:"92:45",en:"guilty of masterminding the savage attacks",zh:"罪名是策划了这一连串发狂袭击,",note:"guilty of = 犯了…罪"},
{w:"mastermind",ipa:"ˈmæstərmaɪnd",pos:"v.",cn:"策划;主谋",ch:["ma","ster","mind"],ph:"ind",tier:3,t:"92:45",en:"guilty of masterminding the savage attacks",zh:"罪名是策划了这一连串发狂袭击,",note:"master+mind:幕后主脑"},
{w:"late",ipa:"leɪt",pos:"adj.",cn:"晚的;最近",ch:["l","ate"],ph:"magic-e",tier:1,t:"92:47",en:"that have plagued Zootopia of late.",zh:"近来这些案件搅得动物城不得安宁。",note:"of late = 最近(书面)"},
{w:"plague",ipa:"pleɪɡ",pos:"v.",cn:"折磨;瘟疫",ch:["pla","gue"],ph:"gu",tier:3,t:"92:47",en:"that have plagued Zootopia of late.",zh:"近来这些案件搅得动物城不得安宁。",note:"plague sb = 像瘟疫一样缠着"},
{w:"deny",ipa:"dɪˈnaɪ",pos:"v.",cn:"否认",ch:["de","ny"],ph:"y-i",tier:2,t:"92:51",en:"denies any knowledge of her plot,",zh:"否认对她的阴谋知情,",note:"deny knowledge of = 称不知情"},
{w:"knowledge",ipa:"ˈnɑːlɪdʒ",pos:"n.",cn:"知识;知情",ch:["know","ledge"],ph:"kn",tier:2,t:"92:51",en:"denies any knowledge of her plot,",zh:"否认对她的阴谋知情,",note:"know 一家;k 不发音"},
{w:"plot",ipa:"plɑːt",pos:"n.",cn:"阴谋;情节",ch:["pl","ot"],ph:"CVC",tier:3,t:"92:51",en:"denies any knowledge of her plot,",zh:"否认对她的阴谋知情,"},
{w:"claim",ipa:"kleɪm",pos:"v.",cn:"声称",ch:["cl","ai","m"],ph:"ai",tier:2,t:"92:53",en:"claiming he was just trying to protect the city.",zh:"声称自己只是想保护这座城市。"},
{w:"imprison",ipa:"ɪmˈprɪzn",pos:"v.",cn:"关押",ch:["im","pri","son"],ph:"i",tier:3,t:"92:56",en:"Did I falsely imprison those animals?",zh:"我是非法关押了那些动物吗?",note:"im(进)+prison(监狱,第四章)"},
{w:"classic",ipa:"ˈklæsɪk",pos:"adj.",cn:"经典的",ch:["clas","sic"],ph:"CVC",tier:2,t:"93:00",en:"It was a classic",zh:"这就是一出经典的……",note:"a classic ...doing-the-wrong-thing... = 经典的“好心办坏事”"},
{w:"antidote",ipa:"ˈæntɪdoʊt",pos:"n.",cn:"解药",ch:["an","ti","dote"],ph:"magic-e",tier:3,t:"93:05",en:"the Night Howlers' antidote is proving effective",zh:"针对“午夜嚎叫”的解药已证实有效,",note:"anti(反)+dote:解毒剂"},
{w:"prove",ipa:"pruːv",pos:"v.",cn:"证明",ch:["pr","ove"],ph:"o-oo",tier:2,t:"93:05",en:"the Night Howlers' antidote is proving effective",zh:"针对“午夜嚎叫”的解药已证实有效,",note:"is proving effective = 事实证明有效"},
{w:"effective",ipa:"ɪˈfektɪv",pos:"adj.",cn:"有效的",ch:["ef","fec","tive"],ph:"e",tier:2,t:"93:05",en:"the Night Howlers' antidote is proving effective",zh:"针对“午夜嚎叫”的解药已证实有效,",note:"effect(效果)+ive"},
{w:"perfect",ipa:"ˈpɜːrfɪkt",pos:"adj.",cn:"完美的",ch:["per","fect"],ph:"er-s",tier:2,t:"93:27",en:"I thought Zootopia was this perfect place.",zh:"我原以为动物城是个完美的地方。"},
{w:"complicated",ipa:"ˈkɑːmplɪkeɪtɪd",pos:"adj.",cn:"复杂的",ch:["com","pli","ca","ted"],ph:"magic-e",tier:2,t:"93:38",en:"real life is a little bit more complicated",zh:"真实的生活,总比一句口号复杂一点,"},
{w:"slogan",ipa:"ˈsloʊɡən",pos:"n.",cn:"口号",ch:["slo","gan"],ph:"o",tier:3,t:"93:40",en:"than a slogan on a bumper sticker.",zh:"比车尾贴上的口号复杂一点。"},
{w:"bumper",ipa:"ˈbʌmpər",pos:"n.",cn:"保险杠",ch:["bum","per"],ph:"er",tier:3,t:"93:40",en:"than a slogan on a bumper sticker.",zh:"比车尾贴上的口号复杂一点。",note:"bumper sticker = 车尾贴"},
{w:"sticker",ipa:"ˈstɪkər",pos:"n.",cn:"贴纸",ch:["sti","cker"],ph:"ck",tier:3,t:"93:40",en:"than a slogan on a bumper sticker.",zh:"比车尾贴上的口号复杂一点。",note:"stick(粘,第三章)+er"},
{w:"messy",ipa:"ˈmesi",pos:"adj.",cn:"乱糟糟的",ch:["mes","sy"],ph:"y",tier:2,t:"93:43",en:"Real life is messy.",zh:"真实的生活是一团乱麻。",note:"mess(乱)+y"},
{w:"limitation",ipa:"ˌlɪmɪˈteɪʃn",pos:"n.",cn:"局限",ch:["li","mi","ta","tion"],ph:"tion",tier:3,t:"93:46",en:"We all have limitations.",zh:"我们每个人都有自己的局限。",note:"limit(第一章)+ation"},
{w:"glass",ipa:"ɡlæs",pos:"n.",cn:"玻璃杯",ch:["gl","ass"],ph:"CVC",tier:1,t:"93:50",en:"Which means, hey, glass half full, we all have a lot in common.",zh:"也就是说——往好处想——我们其实有很多共同点。",note:"glass half full = 往好处看(杯里还有半杯水)"},
{w:"exceptional",ipa:"ɪkˈsepʃənl",pos:"adj.",cn:"出色的,超凡的",ch:["ex","cep","tio","nal"],ph:"tion",tier:3,t:"93:58",en:"The more exceptional each of us will be.",zh:"我们每个人就会越出色。",note:"exception(例外)+al:好得出格"},
{w:"matter",ipa:"ˈmætər",pos:"v.",cn:"要紧;事情",ch:["mat","ter"],ph:"er",tier:2,t:"94:04",en:"So no matter what type of animal you are.",zh:"所以,无论你是哪种动物。",note:"no matter what = 无论什么"},
{w:"type",ipa:"taɪp",pos:"n.",cn:"类型",ch:["t","ype"],ph:"magic-e",tier:2,t:"94:04",en:"So no matter what type of animal you are.",zh:"所以,无论你是哪种动物。"},
{w:"implore",ipa:"ɪmˈplɔːr",pos:"v.",cn:"恳求",ch:["im","plore"],ph:"or",tier:3,t:"94:14",en:"I implore you.",zh:"我恳请大家。",note:"比 please 重得多的“求你们”"},
{w:"inside",ipa:"ɪnˈsaɪd",pos:"adv.",cn:"里面",ch:["in","side"],ph:"magic-e",tier:2,t:"94:23",en:"Look inside yourself and recognize that change starts with you.",zh:"看看自己的内心,并且认识到:改变从你开始。",note:"look inside yourself = 审视内心"},
{w:"recognize",ipa:"ˈrekəɡnaɪz",pos:"v.",cn:"认出;认识到",ch:["re","cog","nize"],ph:"magic-e",tier:2,t:"94:23",en:"Look inside yourself and recognize that change starts with you.",zh:"看看自己的内心,并且认识到:改变从你开始。"},
{w:"morning",ipa:"ˈmɔːrnɪŋ",pos:"n.",cn:"早晨",ch:["mor","ning"],ph:"or",tier:1,t:"94:47",en:"We have some new recruits with us this morning.",zh:"今天早上,我们迎来几位新警员。"},
{w:"greeting",ipa:"ˈɡriːtɪŋ",pos:"n.",cn:"问候",ch:["gree","ting"],ph:"ee",tier:2,t:"94:55",en:"You should have your own line of inspirational greeting cards.",zh:"你都可以出一套自己的励志贺卡了。",note:"greeting card = 贺卡"},
{w:"inspirational",ipa:"ˌɪnspəˈreɪʃənl",pos:"adj.",cn:"励志的",ch:["in","spi","ra","tio","nal"],ph:"tion",tier:3,t:"94:55",en:"You should have your own line of inspirational greeting cards.",zh:"你都可以出一套自己的励志贺卡了。",note:"inspire(鼓舞)一家"},
{w:"undercover",ipa:"ˌʌndərˈkʌvər",pos:"adj.",cn:"卧底的",ch:["un","der","co","ver"],ph:"o-u2",tier:3,t:"95:05",en:"Snarlov, Higgins, Wolfard. Undercover.",zh:"斯纳洛夫、希金斯、沃尔法德,卧底任务。",note:"under+cover:藏在掩护之下"},
{w:"racer",ipa:"ˈreɪsər",pos:"n.",cn:"赛车手",ch:["ra","cer"],ph:"c-s",tier:3,t:"95:18",en:"We have reports of a street racer tearing up Savannah Central.",zh:"接到报案,有飙车族把市中心搅得天翻地覆。",note:"race(比赛)+r;street racer = 飙车族"},
{w:"per",ipa:"pər",pos:"prep.",cn:"每",ch:["p","er"],ph:"er",tier:3,t:"95:56",en:"Sir, you were going 115 miles per hour,",zh:"先生,您刚才的时速是115英里,",note:"miles per hour = 英里/小时(mph)"},
{w:"explanation",ipa:"ˌekspləˈneɪʃn",pos:"n.",cn:"解释",ch:["ex","pla","na","tion"],ph:"tion",tier:2,t:"95:58",en:"I hope you have a good explanation.",zh:"我希望你能给个好点的解释。",note:"explain 的名词"},
{w:"tonight",ipa:"təˈnaɪt",pos:"n.",cn:"今晚",ch:["to","night"],ph:"igh",tier:2,t:"96:18",en:"I messed up tonight, I lost another fight *",zh:"今晚我搞砸了,又输了一仗",note:"片尾曲 Try Everything 歌词"},
{w:"mess",ipa:"mes",pos:"v.",cn:"搞砸;乱",ch:["m","ess"],ph:"CVC",tier:2,t:"96:22",en:"I still mess up but I'll just start again *",zh:"我还是会搞砸,但我会重新再来",note:"mess up = 搞砸"},
{w:"ground",ipa:"ɡraʊnd",pos:"n.",cn:"地面",ch:["gr","ound"],ph:"ou",tier:2,t:"96:26",en:"I keep falling down, I keep on hitting the ground *",zh:"我一次次跌倒,一次次摔在地上",note:"hit the ground = 摔到地上"},
{w:"reach",ipa:"riːtʃ",pos:"v.",cn:"到达;够到",ch:["r","ea","ch"],ph:"ea",tier:2,t:"96:38",en:"'Til I reach the end and then I'll start again *",zh:"直到终点,然后我再重新出发",note:"reach the end = 到达终点"},
{w:"end",ipa:"end",pos:"n.",cn:"结尾,尽头",ch:["e","nd"],ph:"CVC",tier:1,t:"96:38",en:"'Til I reach the end and then I'll start again *",zh:"直到终点,然后我再重新出发",note:"'til = until 的缩略"},
{w:"air",ipa:"er",pos:"n.",cn:"空气;空中",ch:["air"],ph:"air",tier:2,t:"97:26",en:"Put your paws in the air, come on.",zh:"把爪子举到空中,来嘛!",note:"in the air = 举到空中"},
{w:"fill",ipa:"fɪl",pos:"v.",cn:"装满",ch:["f","ill"],ph:"i",tier:2,t:"97:33",en:"* Look how far you've come, you filled your heart with love *",zh:"看你走了多远,心里装满了爱",note:"fill A with B = 用 B 填满 A"},
{w:"sometimes",ipa:"ˈsʌmtaɪmz",pos:"adv.",cn:"有时",ch:["some","times"],ph:"o-u2",tier:1,t:"97:45",en:"Sometimes we come last, but we did our best *",zh:"有时我们垫底,但已拼尽全力",note:"come last = 最后一名"},
{w:"shake",ipa:"ʃeɪk",pos:"v.",cn:"摇",ch:["sh","ake"],ph:"magic-e",tier:2,t:"99:10",en:"Shake your tail with me come on",zh:"跟我一起摇起尾巴,来吧!",note:"过去式 shook"},
];
