// 第二章 初到动物城 Savanna Central(台词 12:42-22:50)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch2.js
const WORDS = [
{w:"welcome",ipa:"ˈwelkəm",pos:"v.",cn:"欢迎",ch:["wel","come"],ph:"CVC",tier:1,t:"12:42",en:"I'm Gazelle. Welcome to Zootopia.",zh:"我是羚羊天后。欢迎来到动物城。",note:"welcome to+地点 = 欢迎来到…"},
{w:"luxury",ipa:"ˈlʌkʃəri",pos:"n.",cn:"豪华",ch:["lux","u","ry"],ph:"y",tier:3,t:"12:48",en:"Luxury apartments with charm.",zh:"带情调的豪华公寓。"},
{w:"apartment",ipa:"əˈpɑːrtmənt",pos:"n.",cn:"公寓",ch:["a","part","ment"],ph:"ar",tier:2,t:"12:48",en:"Luxury apartments with charm.",zh:"带情调的豪华公寓。"},
{w:"charm",ipa:"tʃɑːrm",pos:"n.",cn:"魅力,情调",ch:["ch","arm"],ph:"ch",tier:3,t:"12:48",en:"Luxury apartments with charm.",zh:"带情调的豪华公寓。"},
{w:"month",ipa:"mʌnθ",pos:"n.",cn:"月,月份",ch:["mon","th"],ph:"th",tier:1,t:"12:51",en:"Complimentary delousing once a month. Don't lose your key!",zh:"每月免费除虱一次。别弄丢钥匙!",note:"once a month = 每月一次"},
{w:"lose",ipa:"luːz",pos:"v.",cn:"弄丢,失去",ch:["l","ose"],ph:"o-oo",tier:2,t:"12:51",en:"Complimentary delousing once a month. Don't lose your key!",zh:"每月免费除虱一次。别弄丢钥匙!",note:"过去式 lost"},
{w:"key",ipa:"kiː",pos:"n.",cn:"钥匙",ch:["k","ey"],ph:"ey-i",tier:2,t:"12:51",en:"Complimentary delousing once a month. Don't lose your key!",zh:"每月免费除虱一次。别弄丢钥匙!"},
{w:"loud",ipa:"laʊd",pos:"adj.",cn:"大声的,吵闹的",ch:["l","ou","d"],ph:"ou",tier:2,t:"12:57",en:"- Oh, hi! I'm Judy, your new neighbour! - Yeah? Well, we're loud.",zh:"-你好!我是朱迪,你们的新邻居!-是吗?我们很吵的。"},
{w:"expect",ipa:"ɪkˈspekt",pos:"v.",cn:"期待,指望",ch:["ex","pect"],ph:"x",tier:2,t:"13:00",en:"Don't expect us to apologize for it.",zh:"别指望我们会为此道歉。",note:"expect sb to do = 指望某人做某事"},
{w:"apologize",ipa:"əˈpɑːlədʒaɪz",pos:"v.",cn:"道歉",ch:["a","po","lo","gize"],ph:"magic-e",tier:3,t:"13:00",en:"Don't expect us to apologize for it.",zh:"别指望我们会为此道歉。",note:"apologize for... = 为…道歉"},
{w:"greasy",ipa:"ˈɡriːsi",pos:"adj.",cn:"油腻腻的",ch:["grea","sy"],ph:"ea",tier:3,t:"13:05",en:"Greasy walls.",zh:"油腻腻的墙。",note:"grease(油污)+y = 沾满油的"},
{w:"bed",ipa:"bed",pos:"n.",cn:"床",ch:["b","ed"],ph:"CVC",tier:1,t:"13:07",en:"Rickety bed.",zh:"摇摇晃晃的床。"},
{w:"rickety",ipa:"ˈrɪkəti",pos:"adj.",cn:"摇摇晃晃的",ch:["rick","e","ty"],ph:"ck",tier:3,t:"13:07",en:"Rickety bed.",zh:"摇摇晃晃的床。"},
{w:"neighbor",ipa:"ˈneɪbər",pos:"n.",cn:"邻居",ch:["neigh","bor"],ph:"eigh",tier:2,t:"13:12",en:"Crazy neighbors.",zh:"疯疯癫癫的邻居。",note:"英式拼作 neighbour"},
{w:"bare",ipa:"ber",pos:"v.",cn:"露出",ch:["b","are"],ph:"are",tier:3,t:"13:35",en:"Come on! He bared his teeth first!",zh:"拜托!是他先龇牙的!",note:"bare one's teeth = 龇牙"},
{w:"excuse",ipa:"ɪkˈskjuːz",pos:"v.",cn:"原谅",ch:["ex","cuse"],ph:"x",tier:2,t:"13:40",en:"Excuse me!",zh:"借过!",note:"excuse me:打招呼、借过、没听清都能用"},
{w:"hire",ipa:"ˈhaɪər",pos:"v.",cn:"雇用",ch:["h","ire"],ph:"magic-e",tier:3,t:"13:47",en:"They really did hire a bunny.",zh:"他们真的雇了只兔子。",note:"did hire 的 did = 强调“真的”"},
{w:"cute",ipa:"kjuːt",pos:"adj.",cn:"可爱的",ch:["c","ute"],ph:"magic-e",tier:1,t:"13:55",en:"but a bunny can call another bunny \"Cute\",",zh:"兔子可以叫另一只兔子“可爱”,"},
{w:"call",ipa:"kɔːl",pos:"v.",cn:"叫,称呼",ch:["c","all"],ph:"all",tier:1,t:"13:55",en:"but a bunny can call another bunny \"Cute\",",zh:"兔子可以叫另一只兔子“可爱”,",note:"call A B = 把 A 叫作 B"},
{w:"another",ipa:"əˈnʌðər",pos:"pron.",cn:"另一个",ch:["a","no","ther"],ph:"o-u2",tier:2,t:"13:55",en:"but a bunny can call another bunny \"Cute\",",zh:"兔子可以叫另一只兔子“可爱”,"},
{w:"animal",ipa:"ˈænɪml",pos:"n.",cn:"动物",ch:["a","ni","mal"],ph:"CVC",tier:1,t:"13:58",en:"but when other animals do it, that's a little...",zh:"但别的动物这么叫,就有点……"},
{w:"flabby",ipa:"ˈflæbi",pos:"adj.",cn:"松垮垮的,肉嘟嘟的",ch:["flab","by"],ph:"y",tier:3,t:"14:07",en:"just a flabby donut-loving cop, stereotyping you.",zh:"一个只会吃甜甜圈的胖警察,还给你贴标签。"},
{w:"donut",ipa:"ˈdoʊnʌt",pos:"n.",cn:"甜甜圈",ch:["do","nut"],ph:"o",tier:3,t:"14:07",en:"just a flabby donut-loving cop, stereotyping you.",zh:"一个只会吃甜甜圈的胖警察,还给你贴标签。",note:"也拼作 doughnut"},
{w:"stereotype",ipa:"ˈsteriətaɪp",pos:"v.",cn:"贴刻板标签",ch:["ste","re","o","type"],ph:"magic-e",tier:3,t:"14:07",en:"just a flabby donut-loving cop, stereotyping you.",zh:"一个只会吃甜甜圈的胖警察,还给你贴标签。",note:"把一类人想成一个样"},
{w:"neck",ipa:"nek",pos:"n.",cn:"脖子",ch:["n","eck"],ph:"ck",tier:2,t:"14:14",en:"- A what? - In your neck. The fold.",zh:"-什么?-在你脖子上。那道褶儿。"},
{w:"fold",ipa:"foʊld",pos:"n.",cn:"褶子;折叠",ch:["f","old"],ph:"old",tier:3,t:"14:14",en:"- A what? - In your neck. The fold.",zh:"-什么?-在你脖子上。那道褶儿。"},
{w:"roll call",ipa:"",pos:"短语",cn:"点名",ch:["roll","call"],ph:"",tier:2,type:"chunk",t:"14:22",en:"Hehehe, I should get to roll call, so which way do I...",zh:"嘿嘿,我该去点名了,请问往哪边走……",note:"roll=名册,call=喊:照名册喊人"},
{w:"bull",ipa:"bʊl",pos:"n.",cn:"公牛",ch:["b","ull"],ph:"u",tier:3,t:"14:25",en:"- Oh, bull pen's over there to the left. - Great. Thank you!",zh:"-哦,集合室在那边,往左。-太好了,谢谢!",note:"bull pen 字面“牛圈”,引申为警局的大开间/集合室"},
{w:"pen",ipa:"pen",pos:"n.",cn:"围栏;钢笔",ch:["p","en"],ph:"CVC",tier:1,t:"14:25",en:"- Oh, bull pen's over there to the left. - Great. Thank you!",zh:"-哦,集合室在那边,往左。-太好了,谢谢!",note:"这里是“围栏”:bull+pen 合成 bullpen"},
{w:"left",ipa:"left",pos:"n.",cn:"左边",ch:["l","eft"],ph:"CVC",tier:1,t:"14:25",en:"- Oh, bull pen's over there to the left. - Great. Thank you!",zh:"-哦,集合室在那边,往左。-太好了,谢谢!",note:"to the left = 在左手边"},
{w:"poor",ipa:"pʊr",pos:"adj.",cn:"可怜的;穷的",ch:["p","oor"],ph:"oo-u",tier:2,t:"14:29",en:"That poor little bunny's gonna get eaten alive.",zh:"那只可怜的小兔子会被活活生吞的。"},
{w:"alive",ipa:"əˈlaɪv",pos:"adj.",cn:"活着的",ch:["a","live"],ph:"magic-e",tier:2,t:"14:29",en:"That poor little bunny's gonna get eaten alive.",zh:"那只可怜的小兔子会被活活生吞的。",note:"get eaten alive = 被活吞(被欺负惨)"},
{w:"ready",ipa:"ˈredi",pos:"adj.",cn:"准备好的",ch:["rea","dy"],ph:"ea-e",tier:2,t:"14:44",en:"Officer Hopps. You ready to make the world a better place?",zh:"霍普斯警官,准备好让世界变得更好了吗?",note:"be ready to do = 准备好做…"},
{w:"attention",ipa:"əˈtenʃn",pos:"n.",cn:"注意;立正(口令)",ch:["at","ten","tion"],ph:"tion",tier:2,t:"14:52",en:"Attention!",zh:"立正!"},
{w:"sit",ipa:"sɪt",pos:"v.",cn:"坐",ch:["s","it"],ph:"CVC",tier:1,t:"14:57",en:"All right. All right. Everybody sit.",zh:"好了好了,都坐下。",note:"过去式 sat"},
{w:"item",ipa:"ˈaɪtəm",pos:"n.",cn:"一项,条目",ch:["i","tem"],ph:"i-l",tier:3,t:"15:02",en:"I've got three items on the docket.",zh:"我这儿有三件事要说。",note:"on the docket = 在待办清单上"},
{w:"acknowledge",ipa:"əkˈnɑːlɪdʒ",pos:"v.",cn:"正视,承认",ch:["ac","know","ledge"],ph:"dge",tier:3,t:"15:04",en:"First, we need to acknowledge the elephant in the room.",zh:"首先,我们得正视这个明摆着的问题。",note:"里面藏着 know:承认 = 表示知道了"},
{w:"the elephant in the room",ipa:"",pos:"短语",cn:"明摆着却没人提的事",ch:["the","elephant","in","the","room"],ph:"",tier:2,type:"chunk",t:"15:04",en:"First, we need to acknowledge the elephant in the room.",zh:"首先,我们得正视这个明摆着的问题。",note:"直译“房间里的大象”:都看见了,都不说"},
{w:"elephant",ipa:"ˈelɪfənt",pos:"n.",cn:"大象",ch:["e","le","phant"],ph:"ph",tier:1,t:"15:04",en:"First, we need to acknowledge the elephant in the room.",zh:"首先,我们得正视这个明摆着的问题。"},
{w:"birthday",ipa:"ˈbɜːrθdeɪ",pos:"n.",cn:"生日",ch:["birth","day"],ph:"ir",tier:1,t:"15:10",en:"Francine. Happy birthday.",zh:"弗朗辛,生日快乐。"},
{w:"number",ipa:"ˈnʌmbər",pos:"n.",cn:"数字,第…号",ch:["num","ber"],ph:"er",tier:2,t:"15:16",en:"Number two.",zh:"第二件事。"},
{w:"introduce",ipa:"ˌɪntrəˈduːs",pos:"v.",cn:"介绍",ch:["in","tro","duce"],ph:"magic-e",tier:2,t:"15:18",en:"There are some new recruits with us I should introduce,",zh:"队里来了几位新警员,我本该介绍一下,",note:"introduce A to B = 把 A 介绍给 B"},
{w:"recruit",ipa:"rɪˈkruːt",pos:"n.",cn:"新兵,新成员",ch:["re","cruit"],ph:"ui",tier:3,t:"15:18",en:"There are some new recruits with us I should introduce,",zh:"队里来了几位新警员,我本该介绍一下,"},
{w:"finally",ipa:"ˈfaɪnəli",pos:"adv.",cn:"最后,终于",ch:["fi","nal","ly"],ph:"ly",tier:2,t:"15:25",en:"Finally, we have 14 missing mammal cases.",zh:"最后,我们手上有14起哺乳动物失踪案。"},
{w:"missing",ipa:"ˈmɪsɪŋ",pos:"adj.",cn:"失踪的",ch:["miss","ing"],ph:"i",tier:1,t:"15:25",en:"Finally, we have 14 missing mammal cases.",zh:"最后,我们手上有14起哺乳动物失踪案。",note:"miss(错过)+ing:不见了的"},
{w:"giant",ipa:"ˈdʒaɪənt",pos:"adj.",cn:"巨大的",ch:["gi","ant"],ph:"g-j",tier:3,t:"15:29",en:"All predators. From a giant polar bear to a teensy little otter.",zh:"全是捕食动物。从巨大的北极熊,到一丁点大的水獭。"},
{w:"polar",ipa:"ˈpoʊlər",pos:"adj.",cn:"极地的",ch:["po","lar"],ph:"ar-er",tier:3,t:"15:29",en:"All predators. From a giant polar bear to a teensy little otter.",zh:"全是捕食动物。从巨大的北极熊,到一丁点大的水獭。",note:"polar bear = 北极熊"},
{w:"teensy",ipa:"ˈtiːnzi",pos:"adj.",cn:"(口语)一丁点大的",ch:["teen","sy"],ph:"ee",tier:3,t:"15:29",en:"All predators. From a giant polar bear to a teensy little otter.",zh:"全是捕食动物。从巨大的北极熊,到一丁点大的水獭。",note:"tiny 的更萌说法"},
{w:"otter",ipa:"ˈɑːtər",pos:"n.",cn:"水獭",ch:["ot","ter"],ph:"er",tier:3,t:"15:29",en:"All predators. From a giant polar bear to a teensy little otter.",zh:"全是捕食动物。从巨大的北极熊,到一丁点大的水獭。"},
{w:"hall",ipa:"hɔːl",pos:"n.",cn:"大厅;会堂",ch:["h","all"],ph:"all",tier:2,t:"15:34",en:"And City Hall is right up my tail to find them.",zh:"市政厅正催着我破案呢。",note:"City Hall = 市政厅"},
{w:"tail",ipa:"teɪl",pos:"n.",cn:"尾巴",ch:["t","ai","l"],ph:"ai",tier:1,t:"15:34",en:"And City Hall is right up my tail to find them.",zh:"市政厅正催着我破案呢。",note:"up my tail = 追在屁股后面催"},
{w:"find",ipa:"faɪnd",pos:"v.",cn:"找到,发现",ch:["f","ind"],ph:"ind",tier:1,t:"15:34",en:"And City Hall is right up my tail to find them.",zh:"市政厅正催着我破案呢。",note:"过去式 found"},
{w:"priority",ipa:"praɪˈɔːrəti",pos:"n.",cn:"优先事项",ch:["pri","o","ri","ty"],ph:"or",tier:3,t:"15:38",en:"This is priority number one. Assignments.",zh:"这是头号要务。下面分派任务。",note:"priority number one = 头等大事"},
{w:"assignment",ipa:"əˈsaɪnmənt",pos:"n.",cn:"任务",ch:["as","sign","ment"],ph:"ign",tier:3,t:"15:38",en:"This is priority number one. Assignments.",zh:"这是头号要务。下面分派任务。",note:"assign(分派)+ment = 派下来的活"},
{w:"team",ipa:"tiːm",pos:"n.",cn:"队,组",ch:["t","ea","m"],ph:"ea",tier:2,t:"15:45",en:"Your team take missing mammals from the Rainforest District.",zh:"你们队负责雨林区的哺乳动物失踪案。"},
{w:"parking",ipa:"ˈpɑːrkɪŋ",pos:"n.",cn:"停车",ch:["par","king"],ph:"ar",tier:1,t:"16:05",en:"Parking duty. Dismissed.",zh:"去贴违停罚单。解散。",note:"park(停车)+ing;parking duty = 违停执勤"},
{w:"duty",ipa:"ˈduːti",pos:"n.",cn:"职责,差事",ch:["du","ty"],ph:"u-l",tier:2,t:"16:05",en:"Parking duty. Dismissed.",zh:"去贴违停罚单。解散。",note:"on duty = 在值班"},
{w:"dismiss",ipa:"dɪsˈmɪs",pos:"v.",cn:"解散;打发走",ch:["dis","miss"],ph:"i",tier:3,t:"16:05",en:"Parking duty. Dismissed.",zh:"去贴违停罚单。解散。",note:"Dismissed! = 解散!(口令)"},
{w:"chief",ipa:"tʃiːf",pos:"n.",cn:"局长,首领",ch:["ch","ief"],ph:"ch",tier:3,t:"16:11",en:"Chief? Chief Bogo?",zh:"局长?博戈局长?"},
{w:"sir",ipa:"sɜːr",pos:"n.",cn:"长官,先生(尊称)",ch:["s","ir"],ph:"ir",tier:2,t:"16:15",en:"Sir. You said there were fourteen missing mammal cases.",zh:"长官,您说有14起哺乳动物失踪案。"},
{w:"fourteen",ipa:"ˌfɔːrˈtiːn",pos:"num.",cn:"十四",ch:["four","teen"],ph:"our",tier:2,t:"16:15",en:"Sir. You said there were fourteen missing mammal cases.",zh:"长官,您说有14起哺乳动物失踪案。",note:"four+teen;13-19 都带 teen"},
{w:"handle",ipa:"ˈhændl",pos:"v.",cn:"处理,应付",ch:["hand","le"],ph:"le",tier:3,t:"16:18",en:"- So? - So I can handle one.",zh:"-所以呢?-所以我能办一起。",note:"I can handle it = 我应付得来"},
{w:"top",ipa:"tɑːp",pos:"n.",cn:"顶部;第一名",ch:["t","op"],ph:"CVC",tier:1,t:"16:20",en:"You probably forgot but, I was top of my class at the academy.",zh:"您可能忘了,我可是警校全班第一。",note:"top of my class = 班里第一"},
{w:"probably",ipa:"ˈprɑːbəbli",pos:"adv.",cn:"很可能,大概",ch:["pro","bab","ly"],ph:"ly",tier:2,t:"16:20",en:"You probably forgot but, I was top of my class at the academy.",zh:"您可能忘了,我可是警校全班第一。"},
{w:"academy",ipa:"əˈkædəmi",pos:"n.",cn:"专科学校(警校/军校)",ch:["a","ca","de","my"],ph:"y",tier:3,t:"16:20",en:"You probably forgot but, I was top of my class at the academy.",zh:"您可能忘了,我可是警校全班第一。"},
{w:"forget",ipa:"fərˈɡet",pos:"v.",cn:"忘记",ch:["for","get"],ph:"CVC",tier:2,t:"16:23",en:"Didn't forget. Just don't care.",zh:"没忘。只是不在乎。",note:"过去式 forgot"},
{w:"token",ipa:"ˈtoʊkən",pos:"adj.",cn:"装点门面的",ch:["to","ken"],ph:"o",tier:3,t:"16:26",en:"Sir, I'm not just some token bunny.",zh:"长官,我不是拿来撑场面的吉祥物兔子。",note:"token+身份 = 为了好看才安排的"},
{w:"hundred",ipa:"ˈhʌndrəd",pos:"num.",cn:"一百",ch:["hun","dred"],ph:"CVC",tier:2,t:"16:28",en:"Well then, writing a hundred tickets a day should be easy.",zh:"那好,一天开一百张罚单应该很容易。"},
{w:"easy",ipa:"ˈiːzi",pos:"adj.",cn:"容易的",ch:["ea","sy"],ph:"ea",tier:1,t:"16:28",en:"Well then, writing a hundred tickets a day should be easy.",zh:"那好,一天开一百张罚单应该很容易。"},
{w:"write",ipa:"raɪt",pos:"v.",cn:"写",ch:["wr","ite"],ph:"wr",tier:1,t:"16:35",en:"100 tickets. I'm not gonna write 100 tickets.",zh:"一百张罚单?我可不止开一百张。",note:"过去式 wrote;和 right 同音"},
{w:"noon",ipa:"nuːn",pos:"n.",cn:"正午",ch:["n","oon"],ph:"oo",tier:2,t:"16:38",en:"I'm gonna write 200 tickets. Before noon.",zh:"我要开两百张。中午之前。",note:"afternoon = noon 之后 = 下午"},
{w:"watch",ipa:"wɑːtʃ",pos:"v.",cn:"当心;看",ch:["wa","tch"],ph:"tch",tier:1,t:"17:51",en:"Hey, watch where you're going, fox!",zh:"嘿,走路看着点,狐狸!",note:"watch where you're going = 看着路"},
{w:"skulk",ipa:"skʌlk",pos:"v.",cn:"鬼鬼祟祟地转悠",ch:["sk","ulk"],ph:"CVC",tier:3,t:"18:39",en:"skulking around during daylight hours,",zh:"大白天的在这儿鬼鬼祟祟,"},
{w:"daylight",ipa:"ˈdeɪlaɪt",pos:"n.",cn:"白昼,日光",ch:["day","light"],ph:"igh",tier:3,t:"18:39",en:"skulking around during daylight hours,",zh:"大白天的在这儿鬼鬼祟祟,",note:"day+light 合成词"},
{w:"during",ipa:"ˈdʊrɪŋ",pos:"prep.",cn:"在…期间",ch:["du","ring"],ph:"u",tier:2,t:"18:39",en:"skulking around during daylight hours,",zh:"大白天的在这儿鬼鬼祟祟,"},
{w:"hour",ipa:"ˈaʊər",pos:"n.",cn:"小时",ch:["h","our"],ph:"h-x",tier:1,t:"18:39",en:"skulking around during daylight hours,",zh:"大白天的在这儿鬼鬼祟祟,",note:"h 不发音,所以是 an hour"},
{w:"around",ipa:"əˈraʊnd",pos:"adv.",cn:"四处,周围",ch:["a","round"],ph:"ou",tier:2,t:"18:39",en:"skulking around during daylight hours,",zh:"大白天的在这儿鬼鬼祟祟,"},
{w:"trouble",ipa:"ˈtrʌbl",pos:"n.",cn:"麻烦",ch:["trou","ble"],ph:"ou-x",tier:2,t:"18:41",en:"but I don't want any trouble in here. So hit the road!",zh:"但我这儿不想惹麻烦。赶紧走人!"},
{w:"hit the road",ipa:"",pos:"短语",cn:"上路;(赶人)走人",ch:["hit","the","road"],ph:"",tier:2,type:"chunk",t:"18:41",en:"but I don't want any trouble in here. So hit the road!",zh:"但我这儿不想惹麻烦。赶紧走人!",note:"字面“脚踩上路”= 出发/走人"},
{w:"road",ipa:"roʊd",pos:"n.",cn:"路",ch:["r","oa","d"],ph:"oa",tier:2,t:"18:41",en:"but I don't want any trouble in here. So hit the road!",zh:"但我这儿不想惹麻烦。赶紧走人!"},
{w:"either",ipa:"ˈiːðər",pos:"adv.",cn:"也(用在否定句末)",ch:["ei","ther"],ph:"th",tier:2,t:"18:45",en:"I'm not looking for any trouble either, sir...",zh:"我也不想惹麻烦,先生……",note:"否定句的“也”用 either,不用 too"},
{w:"simply",ipa:"ˈsɪmpli",pos:"adv.",cn:"只是,仅仅",ch:["sim","ply"],ph:"ly",tier:2,t:"18:47",en:"I simply wanna buy a Jumbo-Pop. For my little boy.",zh:"我只想买支巨无霸冰棍。给我小儿子。"},
{w:"buy",ipa:"baɪ",pos:"v.",cn:"买",ch:["b","uy"],ph:"uy",tier:1,t:"18:47",en:"I simply wanna buy a Jumbo-Pop. For my little boy.",zh:"我只想买支巨无霸冰棍。给我小儿子。",note:"过去式 bought"},
{w:"jumbo",ipa:"ˈdʒʌmboʊ",pos:"adj.",cn:"巨大号的",ch:["jum","bo"],ph:"o",tier:3,t:"18:47",en:"I simply wanna buy a Jumbo-Pop. For my little boy.",zh:"我只想买支巨无霸冰棍。给我小儿子。",note:"Jumbo-Pop = 巨无霸冰棍"},
{w:"pop",ipa:"pɑːp",pos:"n.",cn:"冰棍;汽水",ch:["p","op"],ph:"CVC",tier:3,t:"18:47",en:"I simply wanna buy a Jumbo-Pop. For my little boy.",zh:"我只想买支巨无霸冰棍。给我小儿子。"},
{w:"red",ipa:"red",pos:"adj.",cn:"红色的",ch:["r","ed"],ph:"CVC",tier:1,t:"18:56",en:"You want the red, or the blue, pal?",zh:"你要红的还是蓝的,伙计?"},
{w:"blue",ipa:"bluː",pos:"adj.",cn:"蓝色的",ch:["bl","ue"],ph:"ue",tier:1,t:"18:56",en:"You want the red, or the blue, pal?",zh:"你要红的还是蓝的,伙计?"},
{w:"pal",ipa:"pæl",pos:"n.",cn:"(口语)朋友,伙计",ch:["p","al"],ph:"CVC",tier:3,t:"18:56",en:"You want the red, or the blue, pal?",zh:"你要红的还是蓝的,伙计?"},
{w:"buddy",ipa:"ˈbʌdi",pos:"n.",cn:"(口语)兄弟,哥们",ch:["bud","dy"],ph:"y",tier:3,t:"19:06",en:"- Listen, buddy. - What?",zh:"-听着,哥们。-咋?"},
{w:"cream",ipa:"kriːm",pos:"n.",cn:"奶油",ch:["cr","ea","m"],ph:"ea",tier:3,t:"19:07",en:"There aren't any fox ice cream joints in your part of town?",zh:"你们那片城区没有狐狸开的冰淇淋店吗?",note:"ice cream = 冰淇淋"},
{w:"joint",ipa:"dʒɔɪnt",pos:"n.",cn:"(口语)小店;关节",ch:["j","oint"],ph:"oi",tier:3,t:"19:07",en:"There aren't any fox ice cream joints in your part of town?",zh:"你们那片城区没有狐狸开的冰淇淋店吗?"},
{w:"part",ipa:"pɑːrt",pos:"n.",cn:"部分;地区",ch:["p","art"],ph:"ar",tier:2,t:"19:07",en:"There aren't any fox ice cream joints in your part of town?",zh:"你们那片城区没有狐狸开的冰淇淋店吗?",note:"your part of town = 你住的那片"},
{w:"town",ipa:"taʊn",pos:"n.",cn:"城镇",ch:["t","own"],ph:"ow",tier:2,t:"19:07",en:"There aren't any fox ice cream joints in your part of town?",zh:"你们那片城区没有狐狸开的冰淇淋店吗?"},
{w:"goofy",ipa:"ˈɡuːfi",pos:"adj.",cn:"傻乎乎的",ch:["goo","fy"],ph:"oo",tier:3,t:"19:14",en:"this goofy little stinker, he loves all things elephant.",zh:"这个傻乎乎的小捣蛋,什么都要大象款。"},
{w:"stinker",ipa:"ˈstɪŋkər",pos:"n.",cn:"(昵称)小捣蛋",ch:["stin","ker"],ph:"er",tier:3,t:"19:14",en:"this goofy little stinker, he loves all things elephant.",zh:"这个傻乎乎的小捣蛋,什么都要大象款。",note:"stink(臭)+er,爱称,像“小臭蛋”"},
{w:"grow up",ipa:"",pos:"短语",cn:"长大",ch:["grow","up"],ph:"",tier:1,type:"chunk",t:"19:17",en:"He wants to be one when he grows up.",zh:"他长大后想当一头大象。"},
{w:"grow",ipa:"ɡroʊ",pos:"v.",cn:"生长,变得",ch:["gr","ow"],ph:"ow-o",tier:2,t:"19:17",en:"He wants to be one when he grows up.",zh:"他长大后想当一头大象。",note:"过去式 grew"},
{w:"adorable",ipa:"əˈdɔːrəbl",pos:"adj.",cn:"可爱得不行的",ch:["a","dor","a","ble"],ph:"le",tier:3,t:"19:19",en:"Isn't that adorable?",zh:"是不是可爱死了?",note:"比 cute 程度更浓"},
{w:"crush",ipa:"krʌʃ",pos:"v.",cn:"压碎,碾碎",ch:["cr","ush"],ph:"sh",tier:3,t:"19:22",en:"Who the heck am I to crush his little dreams, huh? Right?",zh:"我算老几,凭什么碾碎他小小的梦想,对吧?",note:"crush sb's dream = 打碎梦想"},
{w:"read",ipa:"riːd",pos:"v.",cn:"读",ch:["r","ea","d"],ph:"ea",tier:1,t:"19:25",en:"Look, you probably can't read, fox, but the sign says",zh:"喂,狐狸,你大概不识字,可牌子上写着",note:"过去式也拼 read,读 /red/"},
{w:"sign",ipa:"saɪn",pos:"n.",cn:"牌子,标志",ch:["s","ign"],ph:"ign",tier:2,t:"19:25",en:"Look, you probably can't read, fox, but the sign says",zh:"喂,狐狸,你大概不识字,可牌子上写着",note:"the sign says = 牌子上写着"},
{w:"reserve",ipa:"rɪˈzɜːrv",pos:"v.",cn:"保留",ch:["re","serve"],ph:"er-s",tier:3,t:"19:29",en:"we reserve the right to refuse service to anyone!",zh:"本店有权拒绝为任何人服务!",note:"reserve the right = 保留权利"},
{w:"refuse",ipa:"rɪˈfjuːz",pos:"v.",cn:"拒绝",ch:["re","fuse"],ph:"magic-e",tier:2,t:"19:29",en:"we reserve the right to refuse service to anyone!",zh:"本店有权拒绝为任何人服务!"},
{w:"service",ipa:"ˈsɜːrvɪs",pos:"n.",cn:"服务",ch:["ser","vice"],ph:"er-s",tier:2,t:"19:29",en:"we reserve the right to refuse service to anyone!",zh:"本店有权拒绝为任何人服务!"},
{w:"beat it",ipa:"",pos:"短语",cn:"(俚语)走开",ch:["beat","it"],ph:"",tier:2,type:"chunk",t:"19:33",en:"So beat it.",zh:"所以,哪凉快哪待着去。",note:"赶人走的不客气说法"},
{w:"beat",ipa:"biːt",pos:"v.",cn:"打,击败",ch:["b","ea","t"],ph:"ea",tier:2,t:"19:33",en:"So beat it.",zh:"所以,哪凉快哪待着去。"},
{w:"line",ipa:"laɪn",pos:"n.",cn:"队伍;线",ch:["l","ine"],ph:"magic-e",tier:2,t:"19:34",en:"You're holding up the line.",zh:"你挡着后面排队的人了。",note:"hold up the line = 堵着队伍"},
{w:"maid",ipa:"meɪd",pos:"n.",cn:"女仆;女服务员",ch:["m","ai","d"],ph:"ai",tier:3,t:"19:41",en:"wait your turn like everyone else, meter maid.",zh:"跟别人一样排队去,抄表小妹。",note:"meter maid = 贴罚单的女交管(带嘲笑味)"},
{w:"meter",ipa:"ˈmiːtər",pos:"n.",cn:"计量表;米",ch:["me","ter"],ph:"er",tier:2,t:"19:41",en:"wait your turn like everyone else, meter maid.",zh:"跟别人一样排队去,抄表小妹。",note:"parking meter = 停车计时表"},
{w:"wait",ipa:"weɪt",pos:"v.",cn:"等",ch:["w","ai","t"],ph:"ai",tier:1,t:"19:41",en:"wait your turn like everyone else, meter maid.",zh:"跟别人一样排队去,抄表小妹。",note:"wait your turn = 等着轮到你"},
{w:"turn",ipa:"tɜːrn",pos:"n.",cn:"轮次;转",ch:["t","urn"],ph:"ur",tier:1,t:"19:41",en:"wait your turn like everyone else, meter maid.",zh:"跟别人一样排队去,抄表小妹。"},
{w:"else",ipa:"els",pos:"adv.",cn:"别的,其他",ch:["el","se"],ph:"CVC",tier:2,t:"19:41",en:"wait your turn like everyone else, meter maid.",zh:"跟别人一样排队去,抄表小妹。",note:"everyone else = 其他所有人"},
{w:"question",ipa:"ˈkwestʃən",pos:"n.",cn:"问题",ch:["ques","tion"],ph:"qu",tier:1,t:"19:46",en:"Just have a quick question.",zh:"就问一个小问题。"},
{w:"quick",ipa:"kwɪk",pos:"adj.",cn:"快的",ch:["qu","ick"],ph:"qu",tier:2,t:"19:46",en:"Just have a quick question.",zh:"就问一个小问题。"},
{w:"aware",ipa:"əˈwer",pos:"adj.",cn:"知道的,察觉的",ch:["a","ware"],ph:"are",tier:2,t:"19:48",en:"Are your customers aware they're getting",zh:"你的顾客们知道自己买到的是……",note:"be aware = 心里有数"},
{w:"customer",ipa:"ˈkʌstəmər",pos:"n.",cn:"顾客",ch:["cus","to","mer"],ph:"er",tier:2,t:"19:48",en:"Are your customers aware they're getting",zh:"你的顾客们知道自己买到的是……"},
{w:"snot",ipa:"snɑːt",pos:"n.",cn:"鼻涕",ch:["sn","ot"],ph:"CVC",tier:3,t:"19:50",en:"snot and mucus with their cookies and cream?",zh:"曲奇奶油冰淇淋里掺着鼻涕和黏液?"},
{w:"mucus",ipa:"ˈmjuːkəs",pos:"n.",cn:"黏液",ch:["mu","cus"],ph:"u-l",tier:3,t:"19:50",en:"snot and mucus with their cookies and cream?",zh:"曲奇奶油冰淇淋里掺着鼻涕和黏液?"},
{w:"cookie",ipa:"ˈkʊki",pos:"n.",cn:"曲奇饼干",ch:["coo","kie"],ph:"oo-u",tier:2,t:"19:50",en:"snot and mucus with their cookies and cream?",zh:"曲奇奶油冰淇淋里掺着鼻涕和黏液?",note:"cookies and cream = 曲奇奶油口味"},
{w:"scoop",ipa:"skuːp",pos:"v.",cn:"舀,挖(球)",ch:["sc","oop"],ph:"oo",tier:3,t:"19:58",en:"but I believe scooping ice cream with",zh:"但我确信,挖冰淇淋的时候……"},
{w:"trunk",ipa:"trʌŋk",pos:"n.",cn:"象鼻;后备箱",ch:["tr","unk"],ph:"CVC",tier:3,t:"19:59",en:"an ungloved trunk is a class 3 health code violation.",zh:"……用没戴手套的象鼻,属于三类卫生法规违规。",note:"大象的鼻子叫 trunk,不是 nose"},
{w:"glove",ipa:"ɡlʌv",pos:"n.",cn:"手套;戴上手套",ch:["gl","ove"],ph:"o-u2",tier:2,t:"20:07",en:"with a warning if you were to glove those trunks",zh:"……前提是你们把象鼻都套上手套",note:"ungloved = un+glove+d:没戴手套的"},
{w:"health",ipa:"helθ",pos:"n.",cn:"健康;卫生",ch:["heal","th"],ph:"ea-e",tier:2,t:"19:59",en:"an ungloved trunk is a class 3 health code violation.",zh:"……用没戴手套的象鼻,属于三类卫生法规违规。",note:"health code = 卫生法规"},
{w:"code",ipa:"koʊd",pos:"n.",cn:"法规;代码",ch:["c","ode"],ph:"magic-e",tier:3,t:"19:59",en:"an ungloved trunk is a class 3 health code violation.",zh:"……用没戴手套的象鼻,属于三类卫生法规违规。"},
{w:"violation",ipa:"ˌvaɪəˈleɪʃn",pos:"n.",cn:"违规",ch:["vi","o","la","tion"],ph:"tion",tier:3,t:"19:59",en:"an ungloved trunk is a class 3 health code violation.",zh:"……用没戴手套的象鼻,属于三类卫生法规违规。",note:"violate(违反)+ion"},
{w:"deal",ipa:"diːl",pos:"n.",cn:"大事;交易",ch:["d","ea","l"],ph:"ea",tier:2,t:"20:04",en:"Which is kind of a big deal.",zh:"这可算是个大事。",note:"a big deal = 了不得的事"},
{w:"course",ipa:"kɔːrs",pos:"n.",cn:"当然(of course);课程",ch:["c","our","se"],ph:"our",tier:2,t:"20:06",en:"Of course I could let you off",zh:"当然啦,我也可以放你一马",note:"of course = 当然"},
{w:"let you off",ipa:"",pos:"短语",cn:"放过你",ch:["let","you","off"],ph:"",tier:2,type:"chunk",t:"20:06",en:"Of course I could let you off",zh:"当然啦,我也可以放你一马",note:"let sb off = 放某人一马"},
{w:"warning",ipa:"ˈwɔːrnɪŋ",pos:"n.",cn:"警告",ch:["war","ning"],ph:"war",tier:2,t:"20:07",en:"with a warning if you were to glove those trunks",zh:"只给个警告就算了,前提是象鼻都戴上手套",note:"warn(警告)+ing"},
{w:"finish",ipa:"ˈfɪnɪʃ",pos:"v.",cn:"完成,做完",ch:["fi","nish"],ph:"sh",tier:2,t:"20:09",en:"and... I don't know... finish selling this...",zh:"然后……把这单生意做完……",note:"finish doing = 做完某事"},
{w:"sell",ipa:"sel",pos:"v.",cn:"卖",ch:["s","ell"],ph:"CVC",tier:1,t:"20:09",en:"and... I don't know... finish selling this...",zh:"然后……把这单生意做完……",note:"过去式 sold"},
{w:"son",ipa:"sʌn",pos:"n.",cn:"儿子",ch:["s","on"],ph:"o-u2",tier:2,t:"20:13",en:"nice dad and his son a... What was it?",zh:"……卖给这位好爸爸和他儿子,刚才要的是?",note:"和 sun(太阳)同音"},
{w:"wallet",ipa:"ˈwɑːlɪt",pos:"n.",cn:"钱包",ch:["wal","let"],ph:"CVC",tier:2,t:"20:29",en:"I don't have my wallet!",zh:"我钱包没带!"},
{w:"attach",ipa:"əˈtætʃ",pos:"v.",cn:"系上,连接",ch:["at","tach"],ph:"ch",tier:3,t:"20:32",en:"I'd lose my head if it weren't attached to my neck.",zh:"脑袋要不是长在脖子上,我都能弄丢。",note:"attached to = 连在…上"},
{w:"head",ipa:"hed",pos:"n.",cn:"头",ch:["h","ead"],ph:"ea-e",tier:1,t:"20:32",en:"I'd lose my head if it weren't attached to my neck.",zh:"脑袋要不是长在脖子上,我都能弄丢。"},
{w:"truth",ipa:"truːθ",pos:"n.",cn:"真相,实话",ch:["tru","th"],ph:"th",tier:2,t:"20:35",en:"That's the truth. Oh, boy. I'm sorry, pal.",zh:"真是这样。唉,抱歉了伙计。",note:"true(真的)→ truth(真相)"},
{w:"anyway",ipa:"ˈeniweɪ",pos:"adv.",cn:"不管怎样,还是",ch:["a","ny","way"],ph:"ay",tier:2,t:"20:39",en:"Please don't be mad at me. Thanks anyway.",zh:"请别生我的气。还是谢谢你。"},
{w:"mad",ipa:"mæd",pos:"adj.",cn:"生气的;疯的",ch:["m","ad"],ph:"CVC",tier:2,t:"20:39",en:"Please don't be mad at me. Thanks anyway.",zh:"请别生我的气。还是谢谢你。",note:"be mad at sb = 生某人的气"},
{w:"keep the change",ipa:"",pos:"短语",cn:"不用找零了",ch:["keep","the","change"],ph:"",tier:2,type:"chunk",t:"20:49",en:"Keep the change.",zh:"零钱不用找了。",note:"change 这里 = 找回的零钱"},
{w:"keep",ipa:"kiːp",pos:"v.",cn:"保留,保持",ch:["k","ee","p"],ph:"ee",tier:1,t:"20:49",en:"Keep the change.",zh:"零钱不用找了。",note:"过去式 kept"},
{w:"enough",ipa:"ɪˈnʌf",pos:"adv.",cn:"足够(地)",ch:["e","nough"],ph:"gh-f",tier:2,t:"20:51",en:"Officer, I can't thank you enough.",zh:"警官,真是感激不尽。",note:"can't thank you enough = 怎么谢都不够"},
{w:"pay you back",ipa:"",pos:"短语",cn:"报答你;还你钱",ch:["pay","you","back"],ph:"",tier:2,type:"chunk",t:"20:54",en:"So kind. Really. Can I pay you back?",zh:"太好心了。真的。我能报答你吗?",note:"pay back = 还钱/报答"},
{w:"pay",ipa:"peɪ",pos:"v.",cn:"付钱",ch:["p","ay"],ph:"ay",tier:2,t:"20:54",en:"So kind. Really. Can I pay you back?",zh:"太好心了。真的。我能报答你吗?",note:"过去式 paid"},
{w:"kind",ipa:"kaɪnd",pos:"adj.",cn:"好心的;种类",ch:["k","ind"],ph:"ind",tier:1,t:"20:54",en:"So kind. Really. Can I pay you back?",zh:"太好心了。真的。我能报答你吗?",note:"kind 作名词是“种类”(kind of)"},
{w:"treat",ipa:"triːt",pos:"n.",cn:"请客;款待",ch:["tr","ea","t"],ph:"ea",tier:2,t:"20:56",en:"Oh, no. My treat.",zh:"不用不用,我请客。",note:"My treat. = 这顿我请。"},
{w:"burn",ipa:"bɜːrn",pos:"v.",cn:"烧;让人恼火",ch:["b","urn"],ph:"ur",tier:2,t:"20:58",en:"It's just, you know it burns me up",zh:"只是,你知道吗,我真来气",note:"burn sb up = 把某人气坏"},
{w:"folk",ipa:"foʊk",pos:"n.",cn:"人们,乡亲们",ch:["f","olk"],ph:"olk",tier:2,t:"21:00",en:"to see folks with such backward attitudes towards foxes.",zh:"看到有人对狐狸抱着那么落后的成见。"},
{w:"backward",ipa:"ˈbækwərd",pos:"adj.",cn:"落后的;向后",ch:["back","ward"],ph:"ck",tier:3,t:"21:00",en:"to see folks with such backward attitudes towards foxes.",zh:"看到有人对狐狸抱着那么落后的成见。"},
{w:"attitude",ipa:"ˈætɪtuːd",pos:"n.",cn:"态度,观念",ch:["at","ti","tude"],ph:"magic-e",tier:2,t:"21:00",en:"to see folks with such backward attitudes towards foxes.",zh:"看到有人对狐狸抱着那么落后的成见。"},
{w:"toward",ipa:"təˈwɔːrd",pos:"prep.",cn:"对于,朝向",ch:["to","ward"],ph:"war",tier:2,t:"21:00",en:"to see folks with such backward attitudes towards foxes.",zh:"看到有人对狐狸抱着那么落后的成见。",note:"台词里是 towards,加不加 s 都对"},
{w:"articulate",ipa:"ɑːrˈtɪkjələt",pos:"adj.",cn:"口齿伶俐的",ch:["ar","ti","cu","late"],ph:"ar",tier:3,t:"21:04",en:"a great dad and just a real articulate fella.",zh:"一位好爸爸,还这么能说会道。"},
{w:"fella",ipa:"ˈfelə",pos:"n.",cn:"(口语)家伙",ch:["fel","la"],ph:"CVC",tier:3,t:"21:04",en:"a great dad and just a real articulate fella.",zh:"一位好爸爸,还这么能说会道。",note:"fellow 的口语缩略"},
{w:"high",ipa:"haɪ",pos:"adj.",cn:"高的",ch:["h","igh"],ph:"igh",tier:2,t:"21:08",en:"Well, that is high praise.",zh:"哎呀,这夸奖可真高。",note:"high praise = 高度赞扬"},
{w:"praise",ipa:"preɪz",pos:"n.",cn:"赞扬",ch:["pr","ai","se"],ph:"ai",tier:2,t:"21:08",en:"Well, that is high praise.",zh:"哎呀,这夸奖可真高。"},
{w:"rare",ipa:"rer",pos:"adj.",cn:"罕见的",ch:["r","are"],ph:"are",tier:3,t:"21:11",en:"It's rare that I find someone so non-patronizing.",zh:"很少能遇到不居高临下待人的。"},
{w:"someone",ipa:"ˈsʌmwʌn",pos:"pron.",cn:"某个人",ch:["some","one"],ph:"o-u2",tier:2,t:"21:11",en:"It's rare that I find someone so non-patronizing.",zh:"很少能遇到不居高临下待人的。"},
{w:"patronize",ipa:"ˈpeɪtrənaɪz",pos:"v.",cn:"居高临下地对待",ch:["pa","tro","nize"],ph:"magic-e",tier:3,t:"21:11",en:"It's rare that I find someone so non-patronizing.",zh:"很少能遇到不居高临下待人的。",note:"non- = 不:non-patronizing 不摆架子"},
{w:"paw",ipa:"pɔː",pos:"n.",cn:"爪子",ch:["p","aw"],ph:"aw",tier:3,t:"21:31",en:"All right, here you go. Two paws.",zh:"好嘞,给。两只爪子拿好。"},
{w:"smile",ipa:"smaɪl",pos:"n.",cn:"微笑",ch:["sm","ile"],ph:"magic-e",tier:2,t:"21:33",en:"Yeah. Oh, look at that smile, that's a happy birthday smile!",zh:"看这笑容,这才是过生日的笑脸嘛!"},
{w:"give",ipa:"ɡɪv",pos:"v.",cn:"给",ch:["g","ive"],ph:"i-e-x",tier:1,t:"21:37",en:"All right, give her a little bye-bye toot-toot.",zh:"来,给姐姐来个再见嘟嘟。",note:"过去式 gave"},
{w:"goodbye",ipa:"ˌɡʊdˈbaɪ",pos:"int.",cn:"再见",ch:["good","bye"],ph:"y-i",tier:1,t:"21:42",en:"- Bye, now! - Goodbye!",zh:"-回见!-再见!",note:"bye 是 goodbye 的短说法"},
];
