// 第五章 车管所与神秘泉 DMV(台词 37:26-44:14)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch5.js
const WORDS = [
{w:"pause",ipa:"pɔːz",pos:"n.",cn:"暂停",ch:["p","ause"],ph:"au",tier:3,t:"37:38",en:"You know, I'm gonna hit the pause button right there.",zh:"这样,我先给你按个暂停。",note:"hit the pause button = 按暂停键"},
{w:"button",ipa:"ˈbʌtn",pos:"n.",cn:"按钮;纽扣",ch:["but","ton"],ph:"CVC",tier:2,t:"37:38",en:"You know, I'm gonna hit the pause button right there.",zh:"这样,我先给你按个暂停。"},
{w:"scout",ipa:"skaʊt",pos:"n.",cn:"童子军",ch:["sc","out"],ph:"ou",tier:3,t:"37:41",en:"Cause we're all good on bunny scout cookies.",zh:"兔子军小饼干我们这儿真不缺。",note:"scout 本义侦察员;女童子军以卖饼干出名"},
{w:"old",ipa:"oʊld",pos:"adj.",cn:"老的;旧的",ch:["old"],ph:"old",tier:1,t:"37:59",en:"Yeah, old Emmitt!",zh:"对,老埃米特嘛!",note:"old+名字 = 熟络的叫法"},
{w:"couple",ipa:"ˈkʌpl",pos:"n.",cn:"两三个;一对",ch:["cou","ple"],ph:"ou-x",tier:2,t:"38:02",en:"Haven't seen him in a couple of weeks.",zh:"有两三个星期没见着他了。",note:"a couple of = 两三个"},
{w:"week",ipa:"wiːk",pos:"n.",cn:"星期",ch:["w","ee","k"],ph:"ee",tier:1,t:"38:02",en:"Haven't seen him in a couple of weeks.",zh:"有两三个星期没见着他了。"},
{w:"instructor",ipa:"ɪnˈstrʌktər",pos:"n.",cn:"教练",ch:["in","struc","tor"],ph:"or-er",tier:3,t:"38:05",en:"But hey, you should talk to his yoga instructor.",zh:"不过嘿,你们可以去问他的瑜伽教练。",note:"instruct(指导)+or"},
{w:"yoga",ipa:"ˈjoʊɡə",pos:"n.",cn:"瑜伽",ch:["yo","ga"],ph:"o",tier:3,t:"38:05",en:"But hey, you should talk to his yoga instructor.",zh:"不过嘿,你们可以去问他的瑜伽教练。"},
{w:"appreciate",ipa:"əˈpriːʃieɪt",pos:"v.",cn:"感激",ch:["ap","pre","ci","ate"],ph:"pre",tier:2,t:"38:11",en:"I'd appreciate that more than you can imagine, it'd be such...",zh:"那我可真是感激不尽,简直是……",note:"I'd appreciate that = 那就多谢了"},
{w:"imagine",ipa:"ɪˈmædʒɪn",pos:"v.",cn:"想象",ch:["i","ma","gine"],ph:"g-j",tier:2,t:"38:11",en:"I'd appreciate that more than you can imagine, it'd be such...",zh:"那我可真是感激不尽,简直是……",note:"more than you can imagine = 超乎你想象"},
{w:"naked",ipa:"ˈneɪkɪd",pos:"adj.",cn:"光溜溜的,裸的",ch:["na","ked"],ph:"a-l",tier:3,t:"38:13",en:"Oh! You are naked..",zh:"哦!你们没穿衣服……"},
{w:"club",ipa:"klʌb",pos:"n.",cn:"俱乐部",ch:["cl","ub"],ph:"CVC",tier:2,t:"38:15",en:"Oh, for sure. We're a naturalist club!",zh:"当然啦,我们是天体俱乐部!",note:"for sure = 那当然"},
{w:"naturalist",ipa:"ˈnætʃrəlɪst",pos:"n.",cn:"天体主义者(不穿衣派)",ch:["na","tu","ra","list"],ph:"st",tier:3,t:"38:15",en:"Oh, for sure. We're a naturalist club!",zh:"当然啦,我们是天体俱乐部!",note:"nature+al+ist:主张回归自然(不穿衣服)"},
{w:"pleasure",ipa:"ˈpleʒər",pos:"n.",cn:"愉快,乐趣",ch:["plea","sure"],ph:"ea-e",tier:2,t:"38:23",en:"Nangi's just on the other side of the Pleasure Pool.",zh:"南吉就在欢乐池那头。"},
{w:"pool",ipa:"puːl",pos:"n.",cn:"水池,泳池",ch:["p","ool"],ph:"oo",tier:2,t:"38:23",en:"Nangi's just on the other side of the Pleasure Pool.",zh:"南吉就在欢乐池那头。"},
{w:"side",ipa:"saɪd",pos:"n.",cn:"边,侧",ch:["s","ide"],ph:"magic-e",tier:2,t:"38:23",en:"Nangi's just on the other side of the Pleasure Pool.",zh:"南吉就在欢乐池那头。",note:"on the other side of = 在…另一边"},
{w:"uncomfortable",ipa:"ʌnˈkʌmftəbl",pos:"adj.",cn:"不自在的",ch:["un","com","for","ta","ble"],ph:"le",tier:3,t:"38:34",en:"Oh boy. Does this make you uncomfortable?",zh:"哎呀,这场面让你不自在了?",note:"un+comfort(舒服)+able"},
{w:"shame",ipa:"ʃeɪm",pos:"n.",cn:"羞愧,丢脸",ch:["sh","ame"],ph:"magic-e",tier:2,t:"38:37",en:"Because if so, there's no shame in calling it quits.",zh:"要是这样,现在收手也不丢人。",note:"no shame in... = …不丢人"},
{w:"call it quits",ipa:"",pos:"短语",cn:"就此收手,不干了",ch:["call","it","quits"],ph:"",tier:2,type:"chunk",t:"38:37",en:"Because if so, there's no shame in calling it quits.",zh:"要是这样,现在收手也不丢人。"},
{w:"spirit",ipa:"ˈspɪrɪt",pos:"n.",cn:"精神;劲头",ch:["spi","rit"],ph:"i",tier:2,t:"38:43",en:"Boy, that's the spirit.",zh:"嘿,这就对了,有这股劲!",note:"That's the spirit! = 就要这个劲头!"},
{w:"weird",ipa:"wɪrd",pos:"adj.",cn:"怪怪的",ch:["w","eird"],ph:"",tier:2,t:"38:46",en:"Yeah, some mammals say the naturalist life is weird.",zh:"是啊,有人说天体生活很怪。",note:"读 /wɪrd/;这词的拼法本身就很 weird"},
{w:"clothes",ipa:"kloʊðz",pos:"n.",cn:"衣服",ch:["cl","othes"],ph:"magic-e",tier:1,t:"38:52",en:"Clothes on animals! Here we go!",zh:"动物穿衣服才怪呢!跟我来!",note:"读 /kloʊz/ 也行,th 常吞掉"},
{w:"totally",ipa:"ˈtoʊtəli",pos:"adv.",cn:"完全地;(口语)绝对",ch:["to","tal","ly"],ph:"ly",tier:3,t:"38:58",en:"so she'll totally remember everything.",zh:"所以她绝对什么都记得。",note:"total(全部)+ly"},
{w:"beaver",ipa:"ˈbiːvər",pos:"n.",cn:"河狸",ch:["bea","ver"],ph:"ea",tier:3,t:"39:11",en:"I have no memory of this beaver.",zh:"这只河狸,我完全没印象。"},
{w:"memory",ipa:"ˈmeməri",pos:"n.",cn:"记忆",ch:["me","mo","ry"],ph:"y",tier:2,t:"39:11",en:"I have no memory of this beaver.",zh:"这只河狸,我完全没印象。",note:"have no memory of = 不记得"},
{w:"green",ipa:"ɡriːn",pos:"adj.",cn:"绿色的",ch:["gr","een"],ph:"ee",tier:1,t:"39:18",en:"Yeah, he was wearing a green cable knit sweater vest,",zh:"记得,他穿一件绿色麻花针织毛线背心,"},
{w:"cable",ipa:"ˈkeɪbl",pos:"n.",cn:"缆绳;电缆",ch:["ca","ble"],ph:"le",tier:3,t:"39:18",en:"Yeah, he was wearing a green cable knit sweater vest,",zh:"记得,他穿一件绿色麻花针织毛线背心,",note:"cable knit = 麻花织纹(像缆绳)"},
{w:"knit",ipa:"nɪt",pos:"v.",cn:"编织",ch:["kn","it"],ph:"kn",tier:3,t:"39:18",en:"Yeah, he was wearing a green cable knit sweater vest,",zh:"记得,他穿一件绿色麻花针织毛线背心,"},
{w:"sweater",ipa:"ˈswetər",pos:"n.",cn:"毛衣",ch:["swea","ter"],ph:"ea-e",tier:1,t:"39:18",en:"Yeah, he was wearing a green cable knit sweater vest,",zh:"记得,他穿一件绿色麻花针织毛线背心,"},
{w:"vest",ipa:"vest",pos:"n.",cn:"背心,马甲",ch:["v","est"],ph:"st",tier:3,t:"39:18",en:"Yeah, he was wearing a green cable knit sweater vest,",zh:"记得,他穿一件绿色麻花针织毛线背心,",note:"sweater vest = 毛线背心"},
{w:"wear",ipa:"wer",pos:"v.",cn:"穿,戴",ch:["w","ear"],ph:"ear-air",tier:1,t:"39:18",en:"Yeah, he was wearing a green cable knit sweater vest,",zh:"记得,他穿一件绿色麻花针织毛线背心,",note:"过去式 wore"},
{w:"pair",ipa:"per",pos:"n.",cn:"一双,一条",ch:["p","air"],ph:"air",tier:1,t:"39:21",en:"and a new pair of Quarterway slacks.",zh:"配一条新的休闲裤。",note:"a pair of = 一双/一条"},
{w:"tie",ipa:"taɪ",pos:"n.",cn:"领带;系",ch:["t","ie"],ph:"ie-i",tier:2,t:"39:24",en:"Oh, and a Paisley tie, sweet Windsor knot.",zh:"哦对,还打了条佩斯利花领带,标准温莎结。"},
{w:"knot",ipa:"nɑːt",pos:"n.",cn:"(打的)结",ch:["kn","ot"],ph:"kn",tier:3,t:"39:24",en:"Oh, and a Paisley tie, sweet Windsor knot.",zh:"哦对,还打了条佩斯利花领带,标准温莎结。",note:"Windsor knot = 温莎结(领带打法)"},
{w:"tight",ipa:"taɪt",pos:"adj.",cn:"紧的",ch:["t","ight"],ph:"igh",tier:3,t:"39:27",en:"- Real tight. Remember that, Nangi? - No.",zh:"-系得可紧了。记得吧,南吉?-不记得。"},
{w:"walk",ipa:"wɔːk",pos:"v.",cn:"走;送(人)",ch:["wal","k"],ph:"al",tier:1,t:"39:30",en:"Yeah, and we both walked him out,",zh:"记得,后来我俩一起送他出去,",note:"walk sb out = 送某人出门"},
{w:"white",ipa:"waɪt",pos:"adj.",cn:"白色的",ch:["wh","ite"],ph:"wh",tier:1,t:"39:32",en:"and he got into this big old white car with a silver trim.",zh:"他上了一辆带银边的白色大车。"},
{w:"silver",ipa:"ˈsɪlvər",pos:"n.",cn:"银色;银",ch:["sil","ver"],ph:"er",tier:2,t:"39:32",en:"and he got into this big old white car with a silver trim.",zh:"他上了一辆带银边的白色大车。"},
{w:"trim",ipa:"trɪm",pos:"n.",cn:"镶边,饰条",ch:["tr","im"],ph:"CVC",tier:3,t:"39:32",en:"and he got into this big old white car with a silver trim.",zh:"他上了一辆带银边的白色大车。",note:"silver trim = 银色镶条"},
{w:"tune",ipa:"tuːn",pos:"n.",cn:"曲调;调校",ch:["t","une"],ph:"magic-e",tier:3,t:"39:35",en:"Needed a tune up.",zh:"那车该保养了。",note:"tune up = (给车/乐器)调校"},
{w:"third",ipa:"θɜːrd",pos:"num.",cn:"第三",ch:["th","ird"],ph:"ir",tier:2,t:"39:37",en:"The third cylinder wasn't firing. Remember that, Nangi?",zh:"三号缸都不点火了。记得吧,南吉?",note:"three→third"},
{w:"cylinder",ipa:"ˈsɪlɪndər",pos:"n.",cn:"气缸;圆柱",ch:["cy","lin","der"],ph:"c-s",tier:3,t:"39:37",en:"The third cylinder wasn't firing. Remember that, Nangi?",zh:"三号缸都不点火了。记得吧,南吉?"},
{w:"licence",ipa:"ˈlaɪsns",pos:"n.",cn:"执照,牌照",ch:["li","cence"],ph:"c-s",tier:2,t:"39:41",en:"You didn't happen to catch the licence plate number?",zh:"你不会碰巧记下车牌号了吧?",note:"美式拼 license;licence plate = 车牌"},
{w:"plate",ipa:"pleɪt",pos:"n.",cn:"牌子;盘子",ch:["pl","ate"],ph:"magic-e",tier:2,t:"39:41",en:"You didn't happen to catch the licence plate number?",zh:"你不会碰巧记下车牌号了吧?",note:"run a plate = 查车牌"},
{w:"info",ipa:"ˈɪnfoʊ",pos:"n.",cn:"(口语)信息",ch:["in","fo"],ph:"o",tier:3,t:"39:52",en:"0-3. Wow, this is a lot of great info. Thank you.",zh:"0-3。哇,这信息量太够了,谢谢!",note:"information 的缩略"},
{w:"lot",ipa:"lɑːt",pos:"n.",cn:"许多(a lot)",ch:["l","ot"],ph:"CVC",tier:1,t:"39:52",en:"0-3. Wow, this is a lot of great info. Thank you.",zh:"0-3。哇,这信息量太够了,谢谢!",note:"a lot of = 许多"},
{w:"steel",ipa:"stiːl",pos:"n.",cn:"钢",ch:["st","eel"],ph:"ee",tier:3,t:"39:54",en:"Told you Nangi has a mind like a steel trap.",zh:"我就说吧,南吉的脑子像钢夹子,记住就不撒口。",note:"a mind like a steel trap = 过目不忘"},
{w:"trap",ipa:"træp",pos:"n.",cn:"夹子,陷阱",ch:["tr","ap"],ph:"CVC",tier:3,t:"39:54",en:"Told you Nangi has a mind like a steel trap.",zh:"我就说吧,南吉的脑子像钢夹子,记住就不撒口。"},
{w:"ball",ipa:"bɔːl",pos:"n.",cn:"球;痛快",ch:["b","all"],ph:"all",tier:1,t:"40:03",en:"Well, I had a ball. You are welcome for the clue.",zh:"我玩得挺痛快。线索送你了,不客气。",note:"have a ball = 玩得痛快(不是球!)"},
{w:"clue",ipa:"kluː",pos:"n.",cn:"线索",ch:["cl","ue"],ph:"ue",tier:3,t:"40:03",en:"Well, I had a ball. You are welcome for the clue.",zh:"我玩得挺痛快。线索送你了,不客气。",note:"和 lead 一样,破案线索"},
{w:"moron",ipa:"ˈmɔːrɑːn",pos:"n.",cn:"笨蛋",ch:["mo","ron"],ph:"or",tier:3,t:"40:06",en:"And seeing as any moron can run a plate,",zh:"再说了,查个车牌是个笨蛋都会,",note:"骂人词,比 dumb 重"},
{w:"run",ipa:"rʌn",pos:"v.",cn:"跑;查(数据)",ch:["r","un"],ph:"CVC",tier:1,t:"40:06",en:"And seeing as any moron can run a plate,",zh:"再说了,查个车牌是个笨蛋都会,",note:"run a plate = 查车牌;过去式 ran"},
{w:"task",ipa:"tæsk",pos:"n.",cn:"任务",ch:["ta","sk"],ph:"CVC",tier:2,t:"40:25",en:"who were up to the task.",zh:"又刚好能胜任这活儿的笨蛋。",note:"up to the task = 干得了这活"},
{w:"forever",ipa:"fərˈevər",pos:"adv.",cn:"永远",ch:["for","e","ver"],ph:"er",tier:2,t:"40:28",en:"You can't keep me on the hook forever.",zh:"你不能一直这么拿捏着我。"},
{w:"hook",ipa:"hʊk",pos:"n.",cn:"钩子",ch:["h","ook"],ph:"oo-u",tier:3,t:"40:28",en:"You can't keep me on the hook forever.",zh:"你不能一直这么拿捏着我。",note:"on the hook = 被拿捏,脱不了身"},
{w:"solve",ipa:"sɑːlv",pos:"v.",cn:"解决;破(案)",ch:["sol","ve"],ph:"CVC",tier:2,t:"40:31",en:"Well, I only have 36 hours left to solve this case.",zh:"这案子只剩36小时给我破了。",note:"solve the case = 破案"},
{w:"something",ipa:"ˈsʌmθɪŋ",pos:"pron.",cn:"某件事;某物",ch:["some","thing"],ph:"o-u2",tier:2,t:"40:45",en:"You need something done, he's on it.",zh:"有什么要办的,他包办。",note:"he's on it = 他这就去办"},
{w:"clock",ipa:"klɑːk",pos:"n.",cn:"钟",ch:["cl","ock"],ph:"ck",tier:1,t:"40:47",en:"We are really fighting the clock and every minute counts.",zh:"我们是在跟时间赛跑,一分钟都金贵。",note:"fight the clock = 抢时间"},
{w:"count",ipa:"kaʊnt",pos:"v.",cn:"数数;算数",ch:["c","ount"],ph:"ou",tier:2,t:"40:47",en:"We are really fighting the clock and every minute counts.",zh:"我们是在跟时间赛跑,一分钟都金贵。",note:"every minute counts = 分秒必争"},
{w:"fight",ipa:"faɪt",pos:"v.",cn:"战斗;对抗",ch:["f","ight"],ph:"igh",tier:2,t:"40:47",en:"We are really fighting the clock and every minute counts.",zh:"我们是在跟时间赛跑,一分钟都金贵。",note:"过去式 fought"},
{w:"sloth",ipa:"sloʊθ",pos:"n.",cn:"树懒",ch:["slo","th"],ph:"th",tier:3,t:"40:51",en:"Wait. They're all sloths?",zh:"等等,这里全是树懒?"},
{w:"fast",ipa:"fæst",pos:"adj.",cn:"快的",ch:["fa","st"],ph:"st",tier:1,t:"41:26",en:"he can't be fast?",zh:"难道他就不能手脚麻利?"},
{w:"dash",ipa:"dæʃ",pos:"n.",cn:"短跑,冲刺",ch:["da","sh"],ph:"sh",tier:3,t:"41:30",en:"Flash, Flash, Hundred Yard Dash!",zh:"闪电闪电,百码飞人!",note:"反着叫的外号:树懒版“飞毛腿”"},
{w:"yard",ipa:"jɑːrd",pos:"n.",cn:"码(约0.9米);院子",ch:["y","ard"],ph:"ar",tier:2,t:"41:30",en:"Flash, Flash, Hundred Yard Dash!",zh:"闪电闪电,百码飞人!"},
{w:"meet",ipa:"miːt",pos:"v.",cn:"遇见,认识",ch:["m","eet"],ph:"ee",tier:1,t:"41:41",en:"Hey, Flash, I'd love you to meet my friend.",zh:"嘿,闪电,来认识下我朋友。",note:"过去式 met"},
{w:"hurry",ipa:"ˈhɜːri",pos:"n.",cn:"赶时间",ch:["hur","ry"],ph:"ur",tier:1,t:"42:14",en:"We are in a really big hurry.",zh:"我们真的赶时间。",note:"in a hurry = 赶时间"},
{w:"joke",ipa:"dʒoʊk",pos:"n.",cn:"笑话",ch:["j","oke"],ph:"magic-e",tier:2,t:"43:02",en:"- Hey, Flash. Wanna hear a joke? - No!",zh:"-嘿,闪电,想听个笑话吗?-不想!"},
{w:"camel",ipa:"ˈkæml",pos:"n.",cn:"骆驼",ch:["ca","mel"],ph:"CVC",tier:3,t:"43:08",en:"What do you call a three-humped camel?",zh:"三个驼峰的骆驼,叫什么?"},
{w:"hump",ipa:"hʌmp",pos:"n.",cn:"驼峰",ch:["h","ump"],ph:"CVC",tier:3,t:"43:08",en:"What do you call a three-humped camel?",zh:"三个驼峰的骆驼,叫什么?",note:"three-humped = 长着仨驼峰的"},
{w:"pregnant",ipa:"ˈpreɡnənt",pos:"adj.",cn:"怀孕的",ch:["preg","nant"],ph:"e",tier:3,t:"43:25",en:"Pregnant.",zh:"叫“有喜了”。",note:"笑话谜底:第三个“峰”是肚子"},
{w:"funny",ipa:"ˈfʌni",pos:"adj.",cn:"好笑的",ch:["fun","ny"],ph:"y",tier:1,t:"43:41",en:"Ha ha. Yes, very funny, very funny!",zh:"哈哈,行,真好笑,真好笑!"},
{w:"focus",ipa:"ˈfoʊkəs",pos:"v.",cn:"专注",ch:["fo","cus"],ph:"o",tier:2,t:"43:43",en:"Can we please just focus on the task?",zh:"咱们能不能专心办正事?",note:"focus on = 专心于"},
];
