// 第十章 重返兔窝镇 Night Howlers(台词 76:01-83:42)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch10.js
const WORDS = [
{w:"credit",ipa:"ˈkredɪt",pos:"n.",cn:"功劳;信用",ch:["cre","dit"],ph:"e",tier:3,t:"76:13",en:"Don't give yourself so much credit, Hopps.",zh:"别把功劳都往自己身上揽,霍普斯。",note:"give sb credit = 把功劳记在某人头上"},
{w:"broken",ipa:"ˈbroʊkən",pos:"adj.",cn:"破碎的,坏了的",ch:["bro","ken"],ph:"o",tier:3,t:"76:17",en:"The world has always been broken, that's why we need good cops.",zh:"这世界从来就不完美,所以才需要好警察。",note:"break 的过去分词当形容词"},
{w:"respect",ipa:"rɪˈspekt",pos:"n.",cn:"尊重",ch:["re","spect"],ph:"e",tier:2,t:"76:25",en:"With all due respect, sir,",zh:"恕我直言,长官,",note:"with all due respect = 恕我直言"},
{w:"due",ipa:"duː",pos:"adj.",cn:"应有的;到期的",ch:["d","ue"],ph:"ue",tier:3,t:"76:25",en:"With all due respect, sir,",zh:"恕我直言,长官,",note:"复习“到期”就是 due"},
{w:"serve",ipa:"sɜːrv",pos:"v.",cn:"服务;供职",ch:["ser","ve"],ph:"er-s",tier:2,t:"76:28",en:"a good cop is supposed to serve and protect.",zh:"好警察本该保护和服务大家。",note:"To serve and protect = 美国警察的座右铭"},
{w:"suppose",ipa:"səˈpoʊz",pos:"v.",cn:"认为应该",ch:["sup","pose"],ph:"magic-e",tier:2,t:"76:28",en:"a good cop is supposed to serve and protect.",zh:"好警察本该保护和服务大家。",note:"be supposed to = 按理应该"},
{w:"tear",ipa:"ter",pos:"v.",cn:"撕裂",ch:["t","ear"],ph:"ear-air",tier:3,t:"76:34",en:"Help the city. Not tear it apart.",zh:"是帮这座城,不是把它撕碎。",note:"撕 tear 读 /ter/;眼泪 tear 读 /tɪr/"},
{w:"apart",ipa:"əˈpɑːrt",pos:"adv.",cn:"分开,碎开",ch:["a","part"],ph:"ar",tier:2,t:"76:34",en:"Help the city. Not tear it apart.",zh:"是帮这座城,不是把它撕碎。",note:"tear apart = 撕碎"},
{w:"deserve",ipa:"dɪˈzɜːrv",pos:"v.",cn:"配得上,该得",ch:["de","serve"],ph:"er-s",tier:2,t:"76:42",en:"- I don't deserve this badge. - Hopps.",zh:"-我配不上这枚警徽。-霍普斯。",note:"好的坏的都能“deserve”"},
{w:"ear",ipa:"ɪr",pos:"n.",cn:"耳朵",ch:["ear"],ph:"ear",tier:1,t:"77:31",en:"- I'm fine. - You are not fine, your ears are droopy.",zh:"-我没事。-你才不是没事,耳朵都耷拉了。"},
{w:"droopy",ipa:"ˈdruːpi",pos:"adj.",cn:"耷拉的",ch:["droo","py"],ph:"oo",tier:3,t:"77:31",en:"- I'm fine. - You are not fine, your ears are droopy.",zh:"-我没事。-你才不是没事,耳朵都耷拉了。",note:"droop(垂下)+y"},
{w:"trier",ipa:"ˈtraɪər",pos:"n.",cn:"肯拼的人",ch:["tri","er"],ph:"i-l",tier:3,t:"77:38",en:"Because you're a trier, that's why.",zh:"因为你是个遇事就上的孩子,这就是原因。",note:"try+er:爱尝试的人"},
{w:"innocent",ipa:"ˈɪnəsnt",pos:"adj.",cn:"无辜的",ch:["in","no","cent"],ph:"c-s",tier:2,t:"77:43",en:"And it made life so much worse for so many innocent predators.",zh:"还让那么多无辜的捕食动物日子更难过了。"},
{w:"speak of the devil",ipa:"",pos:"短语",cn:"说曹操,曹操到",ch:["speak","of","the","devil"],ph:"",tier:2,type:"chunk",t:"77:48",en:"not all of them, though. Speak of the devil. Right on time.",zh:"倒也不是全部。说曹操曹操到,来得正巧。",note:"right on time = 来得正是时候"},
{w:"devil",ipa:"ˈdevl",pos:"n.",cn:"魔鬼",ch:["de","vil"],ph:"e",tier:3,t:"77:48",en:"not all of them, though. Speak of the devil. Right on time.",zh:"倒也不是全部。说曹操曹操到,来得正巧。"},
{w:"grey",ipa:"ɡreɪ",pos:"adj.",cn:"灰色的",ch:["gr","ey"],ph:"ey",tier:2,t:"77:53",en:"Is that Gideon Grey?",zh:"那是吉丁·格雷?",note:"这里是姓氏 Grey,本义灰色;美式拼 gray"},
{w:"pastry",ipa:"ˈpeɪstri",pos:"n.",cn:"酥点,糕点",ch:["pa","stry"],ph:"a-l",tier:3,t:"78:04",en:"the top pastry chefs in the tri-burrows.",zh:"三区最好的糕点主厨。"},
{w:"chef",ipa:"ʃef",pos:"n.",cn:"主厨",ch:["ch","ef"],ph:"ch-sh",tier:3,t:"78:04",en:"the top pastry chefs in the tri-burrows.",zh:"三区最好的糕点主厨。",note:"法语来的词,ch 读 /ʃ/"},
{w:"cool",ipa:"kuːl",pos:"adj.",cn:"酷;凉的",ch:["c","ool"],ph:"oo",tier:1,t:"78:08",en:"That's... That's really cool, you guys.",zh:"这……这真的很棒,你们俩。",note:"That's cool. = 真棒"},
{w:"behave",ipa:"bɪˈheɪv",pos:"v.",cn:"表现,举止",ch:["be","have"],ph:"magic-e",tier:3,t:"78:18",en:"for the way I behaved in my youth.",zh:"为我年少时的所作所为道歉。",note:"behave yourself = 规矩点"},
{w:"youth",ipa:"juːθ",pos:"n.",cn:"年少时;青年",ch:["y","outh"],ph:"ou-u",tier:2,t:"78:18",en:"for the way I behaved in my youth.",zh:"为我年少时的所作所为道歉。",note:"in my youth = 我小时候"},
{w:"self",ipa:"self",pos:"n.",cn:"自我",ch:["s","elf"],ph:"CVC",tier:3,t:"78:20",en:"I had a lot of self-doubt, and it manifested itself",zh:"我那时特别不自信,这份自我怀疑",note:"self-doubt = 自我怀疑;myself 里的 self"},
{w:"rage",ipa:"reɪdʒ",pos:"n.",cn:"狂怒",ch:["r","age"],ph:"g-j",tier:3,t:"78:24",en:"in the form of unchecked rage and agression.",zh:"变成了收不住的火气和攻击性。",note:"unchecked rage = 没人管住的怒火"},
{w:"major",ipa:"ˈmeɪdʒər",pos:"adj.",cn:"大号的;主要的",ch:["ma","jor"],ph:"a-l",tier:2,t:"78:26",en:"I was a major jerk.",zh:"我那会儿是个十足的混蛋。",note:"a major jerk = 十足的混蛋"},
{w:"anyhow",ipa:"ˈenihaʊ",pos:"adv.",cn:"不管怎样",ch:["a","ny","how"],ph:"ow",tier:3,t:"78:34",en:"Anyhow, I brought you all these pies.",zh:"总之呢,我给你们带了这些派。",note:"= anyway(第二章)"},
{w:"pie",ipa:"paɪ",pos:"n.",cn:"派,馅饼",ch:["p","ie"],ph:"ie-i",tier:2,t:"78:34",en:"Anyhow, I brought you all these pies.",zh:"总之呢,我给你们带了这些派。"},
{w:"flower",ipa:"ˈflaʊər",pos:"n.",cn:"花",ch:["fl","ow","er"],ph:"ow",tier:1,t:"78:50",en:"Kid's talking about those flowers, Judy.",zh:"孩子说的是那些花,朱迪。",note:"florist(第四章)卖的就是 flower"},
{w:"bug",ipa:"bʌɡ",pos:"n.",cn:"虫子",ch:["b","ug"],ph:"CVC",tier:3,t:"78:52",en:"I use them to keep the bugs off the produce,",zh:"我种它们是为了给庄稼防虫,",note:"keep the bugs off = 防虫"},
{w:"produce",ipa:"ˈproʊduːs",pos:"n.",cn:"农产品;生产",ch:["pro","duce"],ph:"o",tier:3,t:"78:52",en:"I use them to keep the bugs off the produce,",zh:"我种它们是为了给庄稼防虫,",note:"作名词读 /ˈproʊduːs/ = 农产品"},
{w:"near",ipa:"nɪr",pos:"prep.",cn:"靠近",ch:["n","ear"],ph:"ear",tier:1,t:"78:54",en:"but I don't like the little ones going near them",zh:"但我不许小家伙们靠近它们",note:"go near = 靠近"},
{w:"uncle",ipa:"ˈʌŋkl",pos:"n.",cn:"叔叔,舅舅",ch:["un","cle"],ph:"le",tier:1,t:"78:55",en:"on account of what happened to your uncle Terry.",zh:"因为你们特里舅舅出过那档子事。"},
{w:"completely",ipa:"kəmˈpliːtli",pos:"adv.",cn:"完全地",ch:["com","plete","ly"],ph:"ly",tier:2,t:"78:59",en:"and went completely nuts.",zh:"然后就彻底疯了。",note:"complete(第四章)+ly"},
{w:"mother",ipa:"ˈmʌðər",pos:"n.",cn:"母亲",ch:["mo","ther"],ph:"o-u2",tier:1,t:"79:00",en:"He bit the dickens out of your mother.",zh:"把你们的妈妈咬得够呛。",note:"妈妈的正式说法;口语 mom"},
{w:"strong",ipa:"strɔːŋ",pos:"adj.",cn:"强壮的;(用词)重的",ch:["str","ong"],ph:"CVC",tier:1,t:"79:06",en:"Savage? Well, that's a strong word.",zh:"发狂?这个词可有点重。",note:"a strong word = 分量很重的字眼"},
{w:"arm",ipa:"ɑːrm",pos:"n.",cn:"手臂",ch:["ar","m"],ph:"ar",tier:1,t:"79:10",en:"There's a sizable divot in your arm. I'd call that savage.",zh:"你胳膊上缺了好大一块肉,我看这就叫发狂。"},
{w:"sizable",ipa:"ˈsaɪzəbl",pos:"adj.",cn:"相当大的",ch:["si","za","ble"],ph:"le",tier:3,t:"79:10",en:"There's a sizable divot in your arm. I'd call that savage.",zh:"你胳膊上缺了好大一块肉,我看这就叫发狂。",note:"size(尺寸)+able"},
{w:"toxic",ipa:"ˈtɑːksɪk",pos:"adj.",cn:"有毒的",ch:["to","xic"],ph:"x",tier:3,t:"80:10",en:"Night Howlers aren't wolves, they're toxic flowers.",zh:"“午夜嚎叫”不是狼,是有毒的花。"},
{w:"target",ipa:"ˈtɑːrɡɪt",pos:"v.",cn:"瞄准,针对",ch:["tar","get"],ph:"ar",tier:2,t:"80:14",en:"I think someone is targeting predators on purpose",zh:"我觉得有人在故意对捕食动物下手",note:"target sb = 专挑某人下手"},
{w:"interesting",ipa:"ˈɪntrəstɪŋ",pos:"adj.",cn:"有趣的",ch:["in","te","re","sting"],ph:"i",tier:1,t:"80:21",en:"Isn't that interesting?",zh:"是不是很有意思?"},
{w:"forgive",ipa:"fərˈɡɪv",pos:"v.",cn:"原谅",ch:["for","give"],ph:"i-e-x",tier:2,t:"80:25",en:"Wait, please don't.. I know you'll never forgive me.",zh:"等等,别……我知道你永远不会原谅我。",note:"过去式 forgave"},
{w:"ignorant",ipa:"ˈɪɡnərənt",pos:"adj.",cn:"无知的",ch:["ig","no","rant"],ph:"i",tier:3,t:"80:33",en:"It was ignorant, and irresponsible, and small-minded.",zh:"那样做无知、不负责任,还小心眼。",note:"ignore(无视)一家"},
{w:"mistake",ipa:"mɪˈsteɪk",pos:"n.",cn:"错误",ch:["mi","stake"],ph:"magic-e",tier:2,t:"80:40",en:"But predators shouldn't suffer because of my mistakes.",zh:"但捕食动物不该为我的错误遭罪。",note:"make a mistake = 犯错"},
{w:"suffer",ipa:"ˈsʌfər",pos:"v.",cn:"受苦",ch:["suf","fer"],ph:"er",tier:2,t:"80:40",en:"But predators shouldn't suffer because of my mistakes.",zh:"但捕食动物不该为我的错误遭罪。",note:"suffer because of = 因…遭罪"},
{w:"fix",ipa:"fɪks",pos:"v.",cn:"修理;弥补",ch:["f","ix"],ph:"x",tier:2,t:"80:43",en:"I have to fix this.",zh:"我必须弥补这一切。"},
{w:"horrible",ipa:"ˈhɔːrəbl",pos:"adj.",cn:"糟糕透的",ch:["hor","ri","ble"],ph:"le",tier:2,t:"80:58",en:"Because I was a horrible friend and I hurt you.",zh:"因为我是个糟糕透顶的朋友,还伤害了你。",note:"horror(恐怖)+ible"},
{w:"erase",ipa:"ɪˈreɪs",pos:"v.",cn:"擦掉",ch:["e","rase"],ph:"magic-e",tier:3,t:"81:26",en:"Don't worry, Carrots, I'll let you erase it. In 48 hours.",zh:"放心,胡萝卜妹,我会让你删的——48小时后。",note:"eraser = 橡皮"},
{w:"breath",ipa:"breθ",pos:"n.",cn:"呼吸",ch:["brea","th"],ph:"ea-e",tier:2,t:"81:41",en:"There we go, deep breath.",zh:"好了好了,深呼吸。",note:"deep breath = 深呼吸;动词是 breathe"},
{w:"plan",ipa:"plæn",pos:"n.",cn:"计划",ch:["pl","an"],ph:"CVC",tier:2,t:"82:00",en:"- What's your plan? - We are gonna follow the Night Howlers.",zh:"-你的计划是什么?-顺着“午夜嚎叫”查下去。"},
{w:"step",ipa:"step",pos:"v.",cn:"迈步;步子",ch:["st","ep"],ph:"st",tier:2,t:"82:09",en:"hello! Step right up.",zh:"来来来!走过路过别错过。",note:"Step right up! = 摊贩吆喝“快来看”"},
{w:"favorite",ipa:"ˈfeɪvərɪt",pos:"adj.",cn:"最喜欢的",ch:["fa","vo","rite"],ph:"a-l",tier:1,t:"82:13",en:"All your favorite movies.",zh:"你们爱看的电影这儿全有。"},
{w:"movie",ipa:"ˈmuːvi",pos:"n.",cn:"电影",ch:["mo","vie"],ph:"o-oo",tier:1,t:"82:13",en:"All your favorite movies.",zh:"你们爱看的电影这儿全有。",note:"美式 movie,英式 film"},
{w:"release",ipa:"rɪˈliːs",pos:"v.",cn:"发行;释放",ch:["re","lease"],ph:"ea",tier:3,t:"82:15",en:"I've got movies that haven't even been released yet.",zh:"还没上映的电影我这儿都有。",note:"hasn't been released = 还没上映"},
{w:"offer",ipa:"ˈɔːfər",pos:"n.",cn:"出价;提供",ch:["of","fer"],ph:"er",tier:2,t:"82:19",en:"Make me an offer. Come on!",zh:"开个价吧,来嘛!",note:"make an offer = 开价"},
{w:"bootleg",ipa:"ˈbuːtleɡ",pos:"n.",cn:"盗版",ch:["boot","leg"],ph:"oo",tier:3,t:"82:22",en:"look who it is, the Duke of Bootleg.",zh:"瞧瞧这是谁,盗版公爵驾到。",note:"boot(靴子)+leg:旧时把私货藏靴筒里"},
{w:"duke",ipa:"duːk",pos:"n.",cn:"公爵",ch:["d","uke"],ph:"magic-e",tier:3,t:"82:22",en:"look who it is, the Duke of Bootleg.",zh:"瞧瞧这是谁,盗版公爵驾到。"},
{w:"melt",ipa:"melt",pos:"v.",cn:"融化",ch:["m","elt"],ph:"CVC",tier:3,t:"82:26",en:"Shouldn't you be melting down a Pawpsicle or something?",zh:"你不是该去熔你的爪爪冰棍吗?",note:"melt down = 熔掉"},
{w:"dirty",ipa:"ˈdɜːrti",pos:"adj.",cn:"脏的;卑鄙的",ch:["dir","ty"],ph:"ir",tier:1,t:"82:49",en:"You dirty rat, why are you helping her? She's a cop!",zh:"你个卑鄙的老鼠,干嘛帮她?她是条子!",note:"dirty rat = 卑鄙小人"},
{w:"future",ipa:"ˈfjuːtʃər",pos:"n.",cn:"未来",ch:["fu","ture"],ph:"ture",tier:2,t:"82:51",en:"And the godmother to my future granddaughter.",zh:"她还是我未来外孙女的教母。"},
{w:"godmother",ipa:"ˈɡɑːdmʌðər",pos:"n.",cn:"教母",ch:["god","mo","ther"],ph:"o-u2",tier:3,t:"82:51",en:"And the godmother to my future granddaughter.",zh:"她还是我未来外孙女的教母。",note:"god+mother;godfather = 教父"},
{w:"granddaughter",ipa:"ˈɡrændɔːtər",pos:"n.",cn:"(外)孙女",ch:["grand","daugh","ter"],ph:"augh",tier:3,t:"82:51",en:"And the godmother to my future granddaughter.",zh:"她还是我未来外孙女的教母。",note:"grand+daughter(第六章)"},
{w:"whom",ipa:"huːm",pos:"pron.",cn:"谁(宾格)",ch:["wh","om"],ph:"wh",tier:2,t:"83:07",en:"And to whom did you sell them?",zh:"那你把花卖给谁了?",note:"who 的正式宾格,书面腔"},
{w:"ram",ipa:"ræm",pos:"n.",cn:"公羊",ch:["r","am"],ph:"CVC",tier:3,t:"83:09",en:"A ram named Doug.",zh:"一只叫道格的公羊。",note:"绵羊统称 sheep,公羊 ram"},
{w:"drop",ipa:"drɑːp",pos:"n.",cn:"投放;掉落",ch:["dr","op"],ph:"CVC",tier:2,t:"83:10",en:"We got a drop spot underground.",zh:"我们在地下有个交货点。",note:"drop spot = 交货点"},
{w:"spot",ipa:"spɑːt",pos:"n.",cn:"地点;斑点",ch:["sp","ot"],ph:"CVC",tier:2,t:"83:10",en:"We got a drop spot underground.",zh:"我们在地下有个交货点。"},
{w:"underground",ipa:"ˌʌndərˈɡraʊnd",pos:"adv.",cn:"地下",ch:["un","der","ground"],ph:"ou",tier:2,t:"83:10",en:"We got a drop spot underground.",zh:"我们在地下有个交货点。",note:"under+ground(地面)"},
{w:"opposite",ipa:"ˈɑːpəzɪt",pos:"n.",cn:"相反",ch:["op","po","site"],ph:"i",tier:2,t:"83:12",en:"Just watch it. Doug is the opposite of friendly.",zh:"当心点,道格这家伙跟“友好”正相反。",note:"the opposite of = …的反面"},
{w:"friendly",ipa:"ˈfrendli",pos:"adj.",cn:"友好的",ch:["friend","ly"],ph:"ie-e",tier:2,t:"83:12",en:"Just watch it. Doug is the opposite of friendly.",zh:"当心点,道格这家伙跟“友好”正相反。",note:"friend+ly;unfriendly = 不友好"},
];
