// 第四章 水獭失踪案 ZPD(台词 30:52-37:26)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch4.js
const WORDS = [
{w:"abandon",ipa:"əˈbændən",pos:"v.",cn:"抛下,擅离",ch:["a","ban","don"],ph:"CVC",tier:3,t:"30:57",en:"Abandoning your post. Inciting a scurry.",zh:"擅离职守。引发鼠群骚乱。",note:"abandon your post = 擅离岗位"},
{w:"post",ipa:"poʊst",pos:"n.",cn:"岗位;邮寄",ch:["p","ost"],ph:"ost",tier:2,t:"30:57",en:"Abandoning your post. Inciting a scurry.",zh:"擅离职守。引发鼠群骚乱。"},
{w:"reckless",ipa:"ˈrekləs",pos:"adj.",cn:"不管不顾的,鲁莽的",ch:["reck","less"],ph:"ck",tier:3,t:"31:01",en:"Reckless endangerment of rodents...",zh:"鲁莽危害鼠类安全……"},
{w:"rodent",ipa:"ˈroʊdnt",pos:"n.",cn:"啮齿动物(鼠类)",ch:["ro","dent"],ph:"o",tier:3,t:"31:01",en:"Reckless endangerment of rodents...",zh:"鲁莽危害鼠类安全……",note:"小鼠镇 Rodentia 的名字就从这来"},
{w:"fair",ipa:"fer",pos:"adj.",cn:"公平的",ch:["f","air"],ph:"air",tier:2,t:"31:03",en:"But, to be fair,",zh:"不过嘛,说句公道话,",note:"to be fair = 说句公道话"},
{w:"master",ipa:"ˈmæstər",pos:"n.",cn:"大师;主人",ch:["mas","ter"],ph:"er",tier:2,t:"31:05",en:"you did stop a master criminal",zh:"你确实拦下了一个“犯罪大师”",note:"master criminal = 惯犯高手(这里是挖苦)"},
{w:"dozen",ipa:"ˈdʌzn",pos:"n.",cn:"一打(12个)",ch:["do","zen"],ph:"o-u2",tier:3,t:"31:06",en:"from stealing two dozen moldy onions.",zh:"没让他偷走两打发霉的洋葱。",note:"a dozen = 12 个"},
{w:"moldy",ipa:"ˈmoʊldi",pos:"adj.",cn:"发霉的",ch:["mol","dy"],ph:"old",tier:3,t:"31:06",en:"from stealing two dozen moldy onions.",zh:"没让他偷走两打发霉的洋葱。",note:"mold(霉)+y"},
{w:"onion",ipa:"ˈʌnjən",pos:"n.",cn:"洋葱",ch:["o","nion"],ph:"o-u2",tier:2,t:"31:06",en:"from stealing two dozen moldy onions.",zh:"没让他偷走两打发霉的洋葱。"},
{w:"steal",ipa:"stiːl",pos:"v.",cn:"偷",ch:["st","ea","l"],ph:"ea",tier:2,t:"31:06",en:"from stealing two dozen moldy onions.",zh:"没让他偷走两打发霉的洋葱。",note:"过去式 stole"},
{w:"hate",ipa:"heɪt",pos:"v.",cn:"讨厌,恨",ch:["h","ate"],ph:"magic-e",tier:2,t:"31:09",en:"Hate to disagree with you, sir, but those aren't onions.",zh:"长官,恕我直言,那些不是洋葱。",note:"hate to disagree = 不想抬杠,但…"},
{w:"disagree",ipa:"ˌdɪsəˈɡriː",pos:"v.",cn:"不同意",ch:["dis","a","gree"],ph:"ee",tier:3,t:"31:09",en:"Hate to disagree with you, sir, but those aren't onions.",zh:"长官,恕我直言,那些不是洋葱。",note:"dis(不)+agree(同意)"},
{w:"variety",ipa:"vəˈraɪəti",pos:"n.",cn:"品种;多样",ch:["va","ri","e","ty"],ph:"i-l",tier:3,t:"31:12",en:"Those are a crocus variety called midnicampum holicithias.",zh:"那是一种番红花,学名“午夜嚎叫花”。",note:"a variety called... = 一个叫…的品种"},
{w:"botanical",ipa:"bəˈtænɪkl",pos:"adj.",cn:"植物的;植物制剂",ch:["bo","ta","ni","cal"],ph:"CVC",tier:3,t:"31:14",en:"They're a class C botanical, sir.",zh:"它属于丙类管制植物,长官。",note:"botany(植物学)一家子"},
{w:"family",ipa:"ˈfæməli",pos:"n.",cn:"家庭",ch:["fa","mi","ly"],ph:"y",tier:1,t:"31:16",en:"Well, I grew up in a family",zh:"这个嘛,我从小家里",note:"grow up in a family = 在…家庭长大"},
{w:"plant",ipa:"plænt",pos:"n.",cn:"植物;种植",ch:["pl","ant"],ph:"CVC",tier:1,t:"31:17",en:"where plant husbandry was kind of a thing...",zh:"就是种地的,对花花草草还算在行……",note:"plant husbandry = 栽培种植"},
{w:"mouth",ipa:"maʊθ",pos:"n.",cn:"嘴",ch:["m","outh"],ph:"ou",tier:1,t:"31:19",en:"- Shut your tiny mouth now! - Sir, I got the bad guy.",zh:"-闭上你的小嘴!-长官,我抓到坏蛋了啊。"},
{w:"tiny",ipa:"ˈtaɪni",pos:"adj.",cn:"极小的",ch:["ti","ny"],ph:"i-l",tier:2,t:"31:19",en:"- Shut your tiny mouth now! - Sir, I got the bad guy.",zh:"-闭上你的小嘴!-长官,我抓到坏蛋了啊。"},
{w:"car",ipa:"kɑːr",pos:"n.",cn:"汽车",ch:["c","ar"],ph:"ar",tier:1,t:"31:24",en:"Your job is putting tickets on parked cars!",zh:"你的工作是给违停车辆贴罚单!"},
{w:"upset",ipa:"ˌʌpˈset",pos:"adj.",cn:"心烦难过的",ch:["up","set"],ph:"CVC",tier:2,t:"31:33",en:"- take it this time she seems really upset... - Not now!",zh:"-这次她看起来真的很难过……-现在不行!"},
{w:"cartoon",ipa:"kɑːrˈtuːn",pos:"n.",cn:"动画片",ch:["car","toon"],ph:"oo",tier:2,t:"31:45",en:"Life isn't some cartoon musical",zh:"生活不是什么动画音乐剧",note:"重音在后:/kɑːrˈtuːn/"},
{w:"musical",ipa:"ˈmjuːzɪkl",pos:"n.",cn:"音乐剧",ch:["mu","si","cal"],ph:"u-l",tier:3,t:"31:45",en:"Life isn't some cartoon musical",zh:"生活不是什么动画音乐剧",note:"music+al"},
{w:"song",ipa:"sɔːŋ",pos:"n.",cn:"歌",ch:["s","ong"],ph:"CVC",tier:1,t:"31:47",en:"where you sing a little song, and your insipid dreams...",zh:"不是唱首小歌,那些天真的梦……"},
{w:"magically",ipa:"ˈmædʒɪkli",pos:"adv.",cn:"魔法般地",ch:["ma","gi","cal","ly"],ph:"g-j",tier:3,t:"31:51",en:"magically come true! So let it go.",zh:"就会魔法般成真!死了这条心吧。",note:"magic→magical→magically"},
{w:"come true",ipa:"",pos:"短语",cn:"(梦想)成真",ch:["come","true"],ph:"",tier:1,type:"chunk",t:"31:51",en:"magically come true! So let it go.",zh:"就会魔法般成真!死了这条心吧。",note:"dreams come true = 梦想成真"},
{w:"let it go",ipa:"",pos:"短语",cn:"放下吧,随它去",ch:["let","it","go"],ph:"",tier:2,type:"chunk",t:"31:51",en:"magically come true! So let it go.",zh:"就会魔法般成真!死了这条心吧。"},
{w:"true",ipa:"truː",pos:"adj.",cn:"真的",ch:["tr","ue"],ph:"ue",tier:2,t:"31:51",en:"magically come true! So let it go.",zh:"就会魔法般成真!死了这条心吧。",note:"true→truth(真相)"},
{w:"minute",ipa:"ˈmɪnɪt",pos:"n.",cn:"分钟",ch:["mi","nute"],ph:"i",tier:1,t:"31:56",en:"Chief Bogo, please! Five minutes of your time, please.",zh:"博戈局长,求您了!就占用五分钟。"},
{w:"slippery",ipa:"ˈslɪpəri",pos:"adj.",cn:"滑溜溜的",ch:["slip","pe","ry"],ph:"y",tier:3,t:"32:00",en:"I'm sorry sir. I tried to stop her, she's super slippery.",zh:"对不起长官,我拦了,可她滑不留手。",note:"slip(打滑)+ery"},
{w:"super",ipa:"ˈsuːpər",pos:"adv.",cn:"超级",ch:["su","per"],ph:"u-l",tier:3,t:"32:00",en:"I'm sorry sir. I tried to stop her, she's super slippery.",zh:"对不起长官,我拦了,可她滑不留手。",note:"super+形容词 = 超级…"},
{w:"ma'am",ipa:"mæm",pos:"n.",cn:"女士(敬称)",ch:["ma","am"],ph:"",tier:3,t:"32:05",en:"Ma'am, as I've told you, we're doing everything we can.",zh:"女士,我说过了,我们已经尽全力了。",note:"madam 的缩略,当面称呼用"},
{w:"husband",ipa:"ˈhʌzbənd",pos:"n.",cn:"丈夫",ch:["hus","band"],ph:"CVC",tier:2,t:"32:08",en:"My husband has been missing for ten days.",zh:"我丈夫已经失踪十天了。",note:"反义词 wife(妻子)"},
{w:"beautiful",ipa:"ˈbjuːtəfl",pos:"adj.",cn:"美丽的",ch:["beau","ti","ful"],ph:"eau",tier:1,t:"32:14",en:"He's a florist. We have 2 beautiful children.",zh:"他是花匠。我们有两个可爱的孩子。"},
{w:"children",ipa:"ˈtʃɪldrən",pos:"n.",cn:"孩子们",ch:["chil","dren"],ph:"ch",tier:1,t:"32:14",en:"He's a florist. We have 2 beautiful children.",zh:"他是花匠。我们有两个可爱的孩子。",note:"child 的复数"},
{w:"florist",ipa:"ˈflɔːrɪst",pos:"n.",cn:"花匠,花商",ch:["flo","rist"],ph:"or",tier:3,t:"32:14",en:"He's a florist. We have 2 beautiful children.",zh:"他是花匠。我们有两个可爱的孩子。",note:"flower 一家;-ist = 干…的人"},
{w:"disappear",ipa:"ˌdɪsəˈpɪr",pos:"v.",cn:"消失",ch:["dis","ap","pear"],ph:"ear",tier:3,t:"32:17",en:"He would never just disappear.",zh:"他绝不会就这么凭空消失。",note:"dis(不)+appear(出现)"},
{w:"busy",ipa:"ˈbɪzi",pos:"adj.",cn:"忙的",ch:["bu","sy"],ph:"u-i",tier:1,t:"32:19",en:"Ma'am, our detectives are very busy.",zh:"女士,我们的侦探都很忙。"},
{w:"detective",ipa:"dɪˈtektɪv",pos:"n.",cn:"侦探",ch:["de","tec","tive"],ph:"CVC",tier:3,t:"32:19",en:"Ma'am, our detectives are very busy.",zh:"女士,我们的侦探都很忙。",note:"detect(侦查)+ive"},
{w:"somebody",ipa:"ˈsʌmbɑːdi",pos:"pron.",cn:"某个人",ch:["some","bo","dy"],ph:"o-u2",tier:2,t:"32:22",en:"Please. There's gotta be somebody to find my Emmitt.",zh:"求求你们,总得有人去找我的埃米特。"},
{w:"bless",ipa:"bles",pos:"v.",cn:"保佑",ch:["bl","ess"],ph:"CVC",tier:3,t:"32:30",en:"Thank you! Bless you, bless you, little bunny!",zh:"谢谢你!好人有好报,小兔子!",note:"Bless you! 也用于别人打喷嚏时"},
{w:"bring",ipa:"brɪŋ",pos:"v.",cn:"带来",ch:["br","ing"],ph:"i",tier:1,t:"32:41",en:"Bring him home to me and my babies. Please.",zh:"把他带回家,还给我和孩子们。求你了。",note:"过去式 brought"},
{w:"fire",ipa:"ˈfaɪər",pos:"v.",cn:"开除;火",ch:["f","ire"],ph:"magic-e",tier:2,t:"32:51",en:"- You're fired. - What? Why?",zh:"-你被开除了。-什么?为什么?",note:"You're fired! = 你被解雇了"},
{w:"open",ipa:"ˈoʊpən",pos:"v.",cn:"打开",ch:["o","pen"],ph:"o",tier:1,t:"32:54",en:"Insubordination! Now. I'm going to open this door,",zh:"抗命!听着,我现在就打开这扇门,"},
{w:"door",ipa:"dɔːr",pos:"n.",cn:"门",ch:["d","oor"],ph:"oor",tier:1,t:"32:54",en:"Insubordination! Now. I'm going to open this door,",zh:"抗命!听着,我现在就打开这扇门,"},
{w:"former",ipa:"ˈfɔːrmər",pos:"adj.",cn:"以前的;前任的",ch:["for","mer"],ph:"or",tier:3,t:"32:59",en:"you're a former meter maid with delusion of grandeur,",zh:"你就是个自以为了不起的前抄表员,"},
{w:"pay off",ipa:"",pos:"短语",cn:"见效,有回报",ch:["pay","off"],ph:"",tier:2,type:"chunk",t:"33:09",en:"The Mammal Inclusion Initiative is really starting to pay off.",zh:"“哺乳动物包容计划”真的开始见效了。",note:"努力 pay off = 没白费"},
{w:"yet",ipa:"jet",pos:"adv.",cn:"还(没),尚未",ch:["y","et"],ph:"CVC",tier:2,t:"33:15",en:"No, let's not tell the mayor just yet.",zh:"先别,暂时还不用告诉市长。",note:"not...just yet = 先别急着"},
{w:"send",ipa:"send",pos:"v.",cn:"发送,寄",ch:["s","end"],ph:"CVC",tier:1,t:"33:16",en:"And I sent it, and it is done, so I did do that.",zh:"我已经发出去了,办完了,木已成舟。",note:"过去式 sent"},
{w:"hand",ipa:"hænd",pos:"n.",cn:"手",ch:["h","and"],ph:"CVC",tier:1,t:"33:19",en:"All right, well, I'd say the case is in good hands.",zh:"好啦,我看这案子交给可靠的人了。",note:"in good hands = 交给放心的人"},
{w:"together",ipa:"təˈɡeðər",pos:"adv.",cn:"一起",ch:["to","ge","ther"],ph:"th",tier:2,t:"33:22",en:"Us little guys really need to stick together, right?",zh:"咱们小个子就得抱团,对吧?",note:"stick together = 抱团"},
{w:"glue",ipa:"ɡluː",pos:"n.",cn:"胶水",ch:["gl","ue"],ph:"ue",tier:2,t:"33:24",en:"- Like glue. - Good one.",zh:"-粘得像胶水。-接得好。",note:"like glue = 形影不离"},
{w:"always",ipa:"ˈɔːlweɪz",pos:"adv.",cn:"总是,一直",ch:["al","ways"],ph:"al-o",tier:1,t:"33:29",en:"You've always got a friend at City Hall,",zh:"市政厅永远有你一个朋友,"},
{w:"strike out",ipa:"",pos:"短语",cn:"出局,搞砸",ch:["strike","out"],ph:"",tier:2,type:"chunk",t:"33:45",en:"But...you strike out, you resign.",zh:"但是……你要是搞砸了,就辞职走人。",note:"棒球用语:三振出局"},
{w:"resign",ipa:"rɪˈzaɪn",pos:"v.",cn:"辞职",ch:["re","sign"],ph:"ign",tier:3,t:"33:45",en:"But...you strike out, you resign.",zh:"但是……你要是搞砸了,就辞职走人。",note:"re+sign;g 不发音"},
{w:"splendid",ipa:"ˈsplendɪd",pos:"adj.",cn:"好极了",ch:["splen","did"],ph:"CVC",tier:3,t:"33:56",en:"Splendid. Clawhauser will give you the complete case file.",zh:"好极了。洪金豹会把完整案卷给你。",note:"长辈腔的“妙极了”"},
{w:"complete",ipa:"kəmˈpliːt",pos:"adj.",cn:"完整的",ch:["com","plete"],ph:"magic-e",tier:2,t:"33:56",en:"Splendid. Clawhauser will give you the complete case file.",zh:"好极了。洪金豹会把完整案卷给你。"},
{w:"file",ipa:"faɪl",pos:"n.",cn:"档案",ch:["f","ile"],ph:"magic-e",tier:3,t:"33:56",en:"Splendid. Clawhauser will give you the complete case file.",zh:"好极了。洪金豹会把完整案卷给你。",note:"case file = 案卷"},
{w:"none",ipa:"nʌn",pos:"pron.",cn:"一个也没有",ch:["n","one"],ph:"o-u2",tier:2,t:"34:07",en:"That is the smallest case file I've ever seen. Leads, none.",zh:"这是我见过最薄的案卷。线索,零。",note:"no+one 缩成 none"},
{w:"witness",ipa:"ˈwɪtnəs",pos:"n.",cn:"目击证人",ch:["wit","ness"],ph:"i",tier:3,t:"34:10",en:"Witnesses, none.",zh:"目击证人,零。"},
{w:"computer",ipa:"kəmˈpjuːtər",pos:"n.",cn:"电脑",ch:["com","pu","ter"],ph:"er",tier:1,t:"34:11",en:"And you're not in the computer system yet, so...",zh:"而且你还没录入电脑系统,所以……"},
{w:"system",ipa:"ˈsɪstəm",pos:"n.",cn:"系统",ch:["sys","tem"],ph:"y-i2",tier:2,t:"34:11",en:"And you're not in the computer system yet, so...",zh:"而且你还没录入电脑系统,所以……"},
{w:"resource",ipa:"ˈriːsɔːrs",pos:"n.",cn:"资源",ch:["re","source"],ph:"our",tier:3,t:"34:13",en:"Resources, none!",zh:"可用资源,零!"},
{w:"career",ipa:"kəˈrɪr",pos:"n.",cn:"职业生涯",ch:["ca","reer"],ph:"eer",tier:3,t:"34:15",en:"Hoo, I hope you didn't stake your career",zh:"呼,但愿你没把职业前途",note:"stake your career = 拿前途打赌"},
{w:"crack",ipa:"kræk",pos:"v.",cn:"破解;裂开",ch:["cr","ack"],ph:"ck",tier:3,t:"34:17",en:"on cracking this one.",zh:"都押在破这个案子上。",note:"crack a case = 破案"},
{w:"last",ipa:"læst",pos:"adj.",cn:"最后的;上一个",ch:["la","st"],ph:"st",tier:1,t:"34:19",en:"Okay. Last known sighting.",zh:"好,最后一次目击地点。"},
{w:"sighting",ipa:"ˈsaɪtɪŋ",pos:"n.",cn:"一次目击,目击记录",ch:["sigh","ting"],ph:"igh",tier:3,t:"34:19",en:"Okay. Last known sighting.",zh:"好,最后一次目击地点。",note:"sight(看见)+ing"},
{w:"borrow",ipa:"ˈbɑːroʊ",pos:"v.",cn:"借(进来)",ch:["bor","row"],ph:"ow-o",tier:2,t:"34:26",en:"Can I just borrow? Thank you.",zh:"借用一下行吗?谢啦。",note:"borrow 借进来,lend 借出去"},
{w:"murder",ipa:"ˈmɜːrdər",pos:"n.",cn:"谋杀",ch:["mur","der"],ph:"ur",tier:3,t:"34:32",en:"- Pawpsicle? - The murder weapon!",zh:"-爪爪冰棍?-这是凶器!"},
{w:"weapon",ipa:"ˈwepən",pos:"n.",cn:"武器",ch:["wea","pon"],ph:"ea-e",tier:3,t:"34:32",en:"- Pawpsicle? - The murder weapon!",zh:"-爪爪冰棍?-这是凶器!",note:"murder weapon = 凶器"},
{w:"lead",ipa:"liːd",pos:"n.",cn:"线索;带领",ch:["l","ea","d"],ph:"ea",tier:2,t:"34:41",en:"It means I have a lead.",zh:"意思是,我有线索了。",note:"破案的 lead = 线索"},
{w:"ask",ipa:"æsk",pos:"v.",cn:"问;请求",ch:["a","sk"],ph:"CVC",tier:1,t:"34:57",en:"and I'm here to ask you some questions about a case.",zh:"我是来问你几个跟案子有关的问题的。"},
{w:"cone",ipa:"koʊn",pos:"n.",cn:"锥筒;甜筒",ch:["c","one"],ph:"magic-e",tier:3,t:"35:01",en:"Did someone steal a traffic cone?",zh:"怎么,有人偷了路锥吗?",note:"traffic cone = 路锥;ice cream cone = 蛋筒"},
{w:"wake",ipa:"weɪk",pos:"v.",cn:"吵醒,醒来",ch:["w","ake"],ph:"magic-e",tier:1,t:"35:07",en:"Hey, Carrots, you're gonna wake the baby.",zh:"喂,胡萝卜妹,你要吵醒孩子了。",note:"过去式 woke"},
{w:"important",ipa:"ɪmˈpɔːrtnt",pos:"adj.",cn:"重要的",ch:["im","por","tant"],ph:"or",tier:2,t:"35:10",en:"This is important, sir.",zh:"这事很重要,先生。"},
{w:"worth",ipa:"wɜːrθ",pos:"adj.",cn:"值…的",ch:["w","orth"],ph:"or",tier:2,t:"35:11",en:"I think your ten dollars worth of Pawpsicles can wait.",zh:"我看你那十块钱的冰棍生意不急这一会儿。",note:"$10 worth of X = 值 10 刀的 X"},
{w:"buck",ipa:"bʌk",pos:"n.",cn:"(口语)美元",ch:["b","uck"],ph:"ck",tier:3,t:"35:15",en:"I make 200 bucks a day, fluff.",zh:"我一天挣两百刀,毛球。",note:"200 bucks = 200 刀"},
{w:"money",ipa:"ˈmʌni",pos:"n.",cn:"钱",ch:["mo","ney"],ph:"ey-i",tier:1,t:"35:21",en:"And time is money. Hop along.",zh:"时间就是金钱。蹦一边去吧。",note:"Time is money. = 时间就是金钱"},
{w:"hop",ipa:"hɑːp",pos:"v.",cn:"蹦跳",ch:["h","op"],ph:"CVC",tier:3,t:"35:21",en:"And time is money. Hop along.",zh:"时间就是金钱。蹦一边去吧。",note:"Hop along. = 蹦走吧(打发兔子)"},
{w:"picture",ipa:"ˈpɪktʃər",pos:"n.",cn:"照片,图画",ch:["pic","ture"],ph:"ture",tier:1,t:"35:23",en:"Please just look at the picture.",zh:"求你看一眼照片行吗。"},
{w:"somewhere",ipa:"ˈsʌmwer",pos:"adv.",cn:"某个地方",ch:["some","where"],ph:"o-u2",tier:2,t:"35:29",en:"And I also know that somewhere",zh:"我还知道,肯定有个地方"},
{w:"store",ipa:"stɔːr",pos:"n.",cn:"商店",ch:["st","ore"],ph:"or",tier:2,t:"35:31",en:"there's a toy store missing its stuffed animal,",zh:"有家玩具店丢了毛绒玩具,",note:"shop 和 store 都是店"},
{w:"toy",ipa:"tɔɪ",pos:"n.",cn:"玩具",ch:["t","oy"],ph:"oy",tier:1,t:"35:31",en:"there's a toy store missing its stuffed animal,",zh:"有家玩具店丢了毛绒玩具,"},
{w:"stuffed",ipa:"stʌft",pos:"adj.",cn:"毛绒的,填充的",ch:["stuf","fed"],ph:"ff",tier:3,t:"35:31",en:"there's a toy store missing its stuffed animal,",zh:"有家玩具店丢了毛绒玩具,",note:"stuffed animal = 毛绒玩具"},
{w:"fine",ipa:"faɪn",pos:"adj.",cn:"行吧;好的",ch:["f","ine"],ph:"magic-e",tier:1,t:"35:36",en:"Fine. Then we'll have to do this the hard way.",zh:"行。那咱们就来硬的。",note:"the hard way = 来硬的"},
{w:"boot",ipa:"buːt",pos:"v.",cn:"上车轮锁;靴子",ch:["b","oot"],ph:"oo",tier:3,t:"35:39",en:"Did you just boot my stroller?",zh:"你居然锁我的婴儿车?",note:"boot 作动词 = 给车轮上锁"},
{w:"stroller",ipa:"ˈstroʊlər",pos:"n.",cn:"婴儿车",ch:["strol","ler"],ph:"er",tier:3,t:"35:39",en:"Did you just boot my stroller?",zh:"你居然锁我的婴儿车?",note:"stroll(溜达)+er"},
{w:"hurt",ipa:"hɜːrt",pos:"v.",cn:"伤害,弄疼",ch:["h","urt"],ph:"ur",tier:1,t:"35:44",en:"For what? Hurting your feelings?",zh:"凭什么?就凭我伤了你的小心灵?",note:"hurt sb's feelings = 伤感情"},
{w:"felony",ipa:"ˈfeləni",pos:"n.",cn:"重罪",ch:["fe","lo","ny"],ph:"y",tier:3,t:"35:46",en:"Felony tax evasion.",zh:"逃税重罪。"},
{w:"evasion",ipa:"ɪˈveɪʒn",pos:"n.",cn:"逃避",ch:["e","va","sion"],ph:"sion",tier:3,t:"35:46",en:"Felony tax evasion.",zh:"逃税重罪。",note:"tax evasion = 逃税"},
{w:"decade",ipa:"ˈdekeɪd",pos:"n.",cn:"十年",ch:["de","cade"],ph:"magic-e",tier:3,t:"35:52",en:"that's two decades, so times twenty,",zh:"那就是二十年,所以再乘二十,",note:"two decades = 20 年"},
{w:"twenty",ipa:"ˈtwenti",pos:"num.",cn:"二十",ch:["twen","ty"],ph:"y",tier:2,t:"35:52",en:"that's two decades, so times twenty,",zh:"那就是二十年,所以再乘二十,",note:"times twenty = 乘以 20"},
{w:"multiply",ipa:"ˈmʌltɪplaɪ",pos:"v.",cn:"做乘法;繁殖",ch:["mul","ti","ply"],ph:"y-i",tier:3,t:"36:00",en:"but we are good at multiplying.",zh:"但我们兔子最会“乘”了。",note:"算乘法,也指大量繁殖(兔子梗)"},
{w:"according",ipa:"əˈkɔːrdɪŋ",pos:"prep.",cn:"根据(to)",ch:["ac","cor","ding"],ph:"or",tier:2,t:"36:01",en:"Anyway, according to your tax forms,",zh:"总之,根据你的报税表,",note:"according to = 根据"},
{w:"form",ipa:"fɔːrm",pos:"n.",cn:"表格;形式",ch:["f","orm"],ph:"or",tier:2,t:"36:01",en:"Anyway, according to your tax forms,",zh:"总之,根据你的报税表,",note:"tax form = 报税表"},
{w:"report",ipa:"rɪˈpɔːrt",pos:"v.",cn:"申报;报告",ch:["re","port"],ph:"or",tier:2,t:"36:03",en:"you reported, let me see here, zero!",zh:"你申报的收入是——我看看——零!"},
{w:"zero",ipa:"ˈzɪroʊ",pos:"num.",cn:"零",ch:["ze","ro"],ph:"o",tier:2,t:"36:03",en:"you reported, let me see here, zero!",zh:"你申报的收入是——我看看——零!"},
{w:"unfortunately",ipa:"ʌnˈfɔːrtʃənətli",pos:"adv.",cn:"不幸的是",ch:["un","for","tu","nate","ly"],ph:"ly",tier:2,t:"36:06",en:"Unfortunately,",zh:"不巧的是,",note:"un(不)+fortunate(走运)+ly"},
{w:"federal",ipa:"ˈfedərəl",pos:"adj.",cn:"联邦的",ch:["fe","de","ral"],ph:"e",tier:3,t:"36:08",en:"lying on a federal form is a punishable offense.",zh:"在联邦表格上撒谎,可是要被治罪的。"},
{w:"punish",ipa:"ˈpʌnɪʃ",pos:"v.",cn:"惩罚",ch:["pu","nish"],ph:"sh",tier:2,t:"36:08",en:"lying on a federal form is a punishable offense.",zh:"在联邦表格上撒谎,可是要被治罪的。",note:"punishable = punish+able:该罚的"},
{w:"offense",ipa:"əˈfens",pos:"n.",cn:"罪行;冒犯",ch:["of","fense"],ph:"e",tier:3,t:"36:08",en:"lying on a federal form is a punishable offense.",zh:"在联邦表格上撒谎,可是要被治罪的。"},
{w:"jail",ipa:"dʒeɪl",pos:"n.",cn:"监狱",ch:["j","ai","l"],ph:"ai",tier:3,t:"36:11",en:"- 5 years jail time. - Well, it's my word against yours.",zh:"-判五年。-哼,空口无凭,你说了不算。",note:"jail time = 牢狱时间"},
{w:"word",ipa:"wɜːrd",pos:"n.",cn:"词;说的话",ch:["w","ord"],ph:"or",tier:1,t:"36:11",en:"- 5 years jail time. - Well, it's my word against yours.",zh:"-判五年。-哼,空口无凭,你说了不算。",note:"my word against yours = 各说各话,没证据"},
{w:"twelve",ipa:"twelv",pos:"num.",cn:"十二",ch:["twel","ve"],ph:"CVC",tier:2,t:"36:17",en:"365 days a year, since I was twelve.",zh:"一年365天,从我12岁起就这样。"},
{w:"help",ipa:"help",pos:"v.",cn:"帮助",ch:["h","elp"],ph:"CVC",tier:1,t:"36:22",en:"And if you want this pen you're going to help me",zh:"你要想拿回这支录音笔,就得帮我",note:"help sb do = 帮某人做"},
{w:"prison",ipa:"ˈprɪzn",pos:"n.",cn:"监狱",ch:["pri","son"],ph:"i",tier:3,t:"36:26",en:"you'll be selling Pawpsicles is the prison cafeteria.",zh:"不然你以后卖冰棍的地方,就只有监狱食堂了。"},
{w:"cafeteria",ipa:"ˌkæfəˈtɪriə",pos:"n.",cn:"食堂",ch:["ca","fe","te","ri","a"],ph:"i",tier:3,t:"36:26",en:"you'll be selling Pawpsicles is the prison cafeteria.",zh:"不然你以后卖冰棍的地方,就只有监狱食堂了。"},
{w:"fun",ipa:"fʌn",pos:"n.",cn:"乐趣",ch:["f","un"],ph:"CVC",tier:2,t:"36:46",en:"Have fun working with the fuzz!",zh:"祝你跟条子共事愉快!",note:"have fun doing = 开心地做"},
{w:"fuzz",ipa:"fʌz",pos:"n.",cn:"(俚语)条子,警察",ch:["f","uzz"],ph:"zz",tier:3,t:"36:46",en:"Have fun working with the fuzz!",zh:"祝你跟条子共事愉快!",note:"本义绒毛;俚语指警察"},
{w:"start",ipa:"stɑːrt",pos:"v.",cn:"开始",ch:["st","art"],ph:"ar",tier:1,t:"36:51",en:"Start talking.",zh:"开始交代吧。",note:"start doing = 开始做"},
{w:"exactly",ipa:"ɪɡˈzæktli",pos:"adv.",cn:"确切地;正是",ch:["ex","act","ly"],ph:"ly",tier:2,t:"36:59",en:"It's not exactly a place for a cute little bunny.",zh:"那地方,可不太适合可爱的小兔子。",note:"not exactly = 不见得;这里 x 读 /ɡz/"},
{w:"boss",ipa:"bɔːs",pos:"n.",cn:"老板,头儿",ch:["b","oss"],ph:"CVC",tier:2,t:"37:02",en:"- Don't call me cute, get in the car. - Okay. You're the boss.",zh:"-不许叫我可爱,上车。-行,你说了算。",note:"You're the boss. = 听你的"},
];
