// 第三章 小鼠镇追捕 Little Rodentia(台词 22:50-30:52)词卡
// 拼读规律条目在 phonics.js;播放区间在 ends_ch3.js
const WORDS = [
{w:"pawpsicle",ipa:"ˈpɔːpsɪkl",pos:"n.",cn:"爪爪冰棍",ch:["pawp","si","cle"],ph:"aw",tier:3,t:"22:50",en:"Pawpsicles.",zh:"爪爪冰棍嘞。",note:"paw(爪)+popsicle(冰棍)造出来的词"},
{w:"lumber",ipa:"ˈlʌmbər",pos:"n.",cn:"木材",ch:["lum","ber"],ph:"er",tier:3,t:"23:18",en:"- Lumber delivery. - What's with the color?",zh:"-送木材的。-这颜色怎么回事?"},
{w:"delivery",ipa:"dɪˈlɪvəri",pos:"n.",cn:"送货",ch:["de","li","ve","ry"],ph:"y",tier:3,t:"23:18",en:"- Lumber delivery. - What's with the color?",zh:"-送木材的。-这颜色怎么回事?",note:"deliver(递送)+y"},
{w:"color",ipa:"ˈkʌlər",pos:"n.",cn:"颜色",ch:["co","lor"],ph:"o-u2",tier:1,t:"23:18",en:"- Lumber delivery. - What's with the color?",zh:"-送木材的。-这颜色怎么回事?",note:"英式拼作 colour"},
{w:"diaper",ipa:"ˈdaɪpər",pos:"n.",cn:"尿布",ch:["di","a","per"],ph:"i-l",tier:3,t:"23:28",en:"Way to work that diaper, big guy.",zh:"尿布造型不错啊,大兄弟。"},
{w:"kiss",ipa:"kɪs",pos:"n.",cn:"亲吻",ch:["k","iss"],ph:"i",tier:2,t:"23:31",en:"No kiss bye-bye for daddy?",zh:"不亲一口跟爸爸说拜拜吗?"},
{w:"daddy",ipa:"ˈdædi",pos:"n.",cn:"爸爸(儿语)",ch:["dad","dy"],ph:"y",tier:1,t:"23:31",en:"No kiss bye-bye for daddy?",zh:"不亲一口跟爸爸说拜拜吗?",note:"dad 的儿语版,像“爸比”"},
{w:"bite",ipa:"baɪt",pos:"v.",cn:"咬",ch:["b","ite"],ph:"magic-e",tier:3,t:"23:35",en:"You kiss me tomorrow, I'll bite your face off!",zh:"你明天敢亲我,我咬掉你的脸!",note:"过去式 bit"},
{w:"stand up for",ipa:"",pos:"短语",cn:"为…挺身而出",ch:["stand","up","for"],ph:"",tier:2,type:"chunk",t:"23:44",en:"Well, I stood up for you, and you lied to me.",zh:"我还替你说话,你却骗了我。",note:"stood 是 stand 的过去式"},
{w:"lie",ipa:"laɪ",pos:"v.",cn:"说谎",ch:["l","ie"],ph:"ie-i",tier:2,t:"23:44",en:"Well, I stood up for you, and you lied to me.",zh:"我还替你说话,你却骗了我。",note:"lie to sb = 对某人撒谎"},
{w:"liar",ipa:"ˈlaɪər",pos:"n.",cn:"骗子",ch:["li","ar"],ph:"ar-er",tier:3,t:"23:47",en:"You liar!",zh:"你个骗子!",note:"lie(说谎)+ar = 说谎的人"},
{w:"hustle",ipa:"ˈhʌsl",pos:"n.",cn:"骗局,坑蒙拐骗",ch:["hus","tle"],ph:"st-t",tier:3,t:"23:49",en:"It's called a hustle, Sweetheart.",zh:"这叫套路,小甜心。",note:"hustler = 老千,骗子"},
{w:"sweetheart",ipa:"ˈswiːthɑːrt",pos:"n.",cn:"甜心,亲爱的",ch:["sweet","heart"],ph:"ear-ar",tier:3,t:"23:49",en:"It's called a hustle, Sweetheart.",zh:"这叫套路,小甜心。",note:"sweet+heart;这里带挖苦味"},
{w:"arrest",ipa:"əˈrest",pos:"n.",cn:"逮捕",ch:["ar","rest"],ph:"st",tier:3,t:"23:57",en:"All right, Slick-Nick. You're under arrest.",zh:"好了,滑头尼克,你被捕了。",note:"under arrest = 被捕了"},
{w:"slick",ipa:"slɪk",pos:"adj.",cn:"油滑的,滑头的",ch:["sl","ick"],ph:"ck",tier:3,t:"23:57",en:"All right, Slick-Nick. You're under arrest.",zh:"好了,滑头尼克,你被捕了。"},
{w:"food",ipa:"fuːd",pos:"n.",cn:"食物",ch:["f","ood"],ph:"oo",tier:1,t:"24:02",en:"Gee, I don't know. How about selling food without a permit?",zh:"我想想,比如:无证卖食品?"},
{w:"permit",ipa:"ˈpɜːrmɪt",pos:"n.",cn:"许可证",ch:["per","mit"],ph:"er-s",tier:3,t:"24:02",en:"Gee, I don't know. How about selling food without a permit?",zh:"我想想,比如:无证卖食品?",note:"without a permit = 无证"},
{w:"without",ipa:"wɪˈðaʊt",pos:"prep.",cn:"没有,不带",ch:["with","out"],ph:"ou",tier:2,t:"24:02",en:"Gee, I don't know. How about selling food without a permit?",zh:"我想想,比如:无证卖食品?",note:"with(带着)的反面"},
{w:"transport",ipa:"trænsˈpɔːrt",pos:"v.",cn:"运输",ch:["trans","port"],ph:"or",tier:3,t:"24:04",en:"Transporting undeclared commerce across borough lines?",zh:"跨城区运输未申报的货物?"},
{w:"commerce",ipa:"ˈkɑːmərs",pos:"n.",cn:"买卖;货物",ch:["com","merce"],ph:"er",tier:3,t:"24:04",en:"Transporting undeclared commerce across borough lines?",zh:"跨城区运输未申报的货物?"},
{w:"across",ipa:"əˈkrɔːs",pos:"prep.",cn:"横穿,跨越",ch:["a","cross"],ph:"CVC",tier:2,t:"24:04",en:"Transporting undeclared commerce across borough lines?",zh:"跨城区运输未申报的货物?",note:"across borough lines = 跨城区"},
{w:"false",ipa:"fɔːls",pos:"adj.",cn:"虚假的",ch:["fal","se"],ph:"al-o",tier:2,t:"24:07",en:"- False advertizing. - Permit. Receipt of declared commerce.",zh:"-虚假宣传。-许可证。申报货物的收据。",note:"true(真)的反义词"},
{w:"receipt",ipa:"rɪˈsiːt",pos:"n.",cn:"收据",ch:["re","ceipt"],ph:"",tier:3,t:"24:07",en:"- False advertizing. - Permit. Receipt of declared commerce.",zh:"-虚假宣传。-许可证。申报货物的收据。",note:"p 不发音:读 /rɪˈsiːt/"},
{w:"advertise",ipa:"ˈædvərtaɪz",pos:"v.",cn:"做广告,宣传",ch:["ad","ver","tise"],ph:"magic-e",tier:3,t:"24:11",en:"And I didn't falsely advertize anything. Take care.",zh:"我可没做任何虚假宣传。回见。",note:"标准拼法 advertise,字幕作 advertize"},
{w:"mouse",ipa:"maʊs",pos:"n.",cn:"老鼠",ch:["m","ouse"],ph:"ou",tier:1,t:"24:13",en:"You told that mouse the Pawpsicle sticks were redwood!",zh:"你跟那只老鼠说,冰棍棍儿是红杉木!",note:"复数 mice"},
{w:"stick",ipa:"stɪk",pos:"n.",cn:"小棍;粘住",ch:["st","ick"],ph:"ck",tier:2,t:"24:13",en:"You told that mouse the Pawpsicle sticks were redwood!",zh:"你跟那只老鼠说,冰棍棍儿是红杉木!"},
{w:"middle",ipa:"ˈmɪdl",pos:"n.",cn:"中间",ch:["mid","dle"],ph:"le",tier:1,t:"24:15",en:"That's right. Red wood. With a space in the middle.",zh:"没错啊,“红-木”,中间带个空格。"},
{w:"space",ipa:"speɪs",pos:"n.",cn:"空格;空间;太空",ch:["sp","ace"],ph:"magic-e",tier:1,t:"24:15",en:"That's right. Red wood. With a space in the middle.",zh:"没错啊,“红-木”,中间带个空格。",note:"这里指“空格”:red wood 分开写就不是红杉"},
{w:"wood",ipa:"wʊd",pos:"n.",cn:"木头",ch:["w","ood"],ph:"oo-u",tier:2,t:"24:15",en:"That's right. Red wood. With a space in the middle.",zh:"没错啊,“红-木”,中间带个空格。",note:"redwood = 红杉(高级木材)"},
{w:"touch",ipa:"tʌtʃ",pos:"v.",cn:"碰,触摸",ch:["t","ouch"],ph:"ou-x",tier:2,t:"24:20",en:"You can't touch me, Carrots.",zh:"你动不了我,胡萝卜妹。",note:"can't touch me = 拿我没办法"},
{w:"born",ipa:"bɔːrn",pos:"adj.",cn:"出生",ch:["b","orn"],ph:"or",tier:2,t:"24:22",en:"I've been doing this since I was born.",zh:"我从生下来就干这行了。",note:"be born = 出生"},
{w:"refrain",ipa:"rɪˈfreɪn",pos:"v.",cn:"忍住不做",ch:["re","frain"],ph:"ai",tier:3,t:"24:24",en:"You're gonna wanna refrain from calling me Carrots.",zh:"劝你忍住,别叫我胡萝卜妹。",note:"refrain from doing = 克制着不做"},
{w:"assume",ipa:"əˈsuːm",pos:"v.",cn:"想当然以为",ch:["as","sume"],ph:"magic-e",tier:3,t:"24:26",en:"My bad. I just naturally assumed you came...",zh:"怪我,我就自然而然以为你是……",note:"My bad. = 怪我(口语)"},
{w:"naturally",ipa:"ˈnætʃrəli",pos:"adv.",cn:"自然而然地",ch:["na","tu","ral","ly"],ph:"ly",tier:3,t:"24:26",en:"My bad. I just naturally assumed you came...",zh:"怪我,我就自然而然以为你是……",note:"nature(自然)→natural→naturally"},
{w:"choke",ipa:"tʃoʊk",pos:"v.",cn:"噎住;塞满",ch:["ch","oke"],ph:"magic-e",tier:3,t:"24:28",en:"from some little carrot-choked Podunk. No?",zh:"……从哪个胡萝卜堆里的土窝窝来的,不是吗?",note:"carrot-choked = 被胡萝卜“塞满”的(挖苦乡下)"},
{w:"county",ipa:"ˈkaʊnti",pos:"n.",cn:"县",ch:["coun","ty"],ph:"ou",tier:3,t:"24:31",en:"Podunk is in Deerbrooke county and I grew up in Bunnyburrow.",zh:"土窝窝在鹿溪县,我家在兔窝镇,两码事。"},
{w:"story",ipa:"ˈstɔːri",pos:"n.",cn:"故事",ch:["sto","ry"],ph:"or",tier:1,t:"24:34",en:"Okay. Tell me if this story sounds familiar.",zh:"行,听听这故事耳不耳熟。"},
{w:"sound",ipa:"saʊnd",pos:"v.",cn:"听起来",ch:["s","ound"],ph:"ou",tier:2,t:"24:34",en:"Okay. Tell me if this story sounds familiar.",zh:"行,听听这故事耳不耳熟。",note:"sound familiar = 听着耳熟"},
{w:"familiar",ipa:"fəˈmɪliər",pos:"adj.",cn:"熟悉的",ch:["fa","mi","liar"],ph:"i",tier:2,t:"24:34",en:"Okay. Tell me if this story sounds familiar.",zh:"行,听听这故事耳不耳熟。"},
{w:"naive",ipa:"naɪˈiːv",pos:"adj.",cn:"天真的",ch:["na","ive"],ph:"",tier:3,t:"24:37",en:"Naive little hick with good grades and big ideas",zh:"天真的乡下娃,成绩好、理想大",note:"法语借词,读 /naɪˈiːv/"},
{w:"hick",ipa:"hɪk",pos:"n.",cn:"乡巴佬",ch:["h","ick"],ph:"ck",tier:3,t:"24:37",en:"Naive little hick with good grades and big ideas",zh:"天真的乡下娃,成绩好、理想大"},
{w:"grade",ipa:"ɡreɪd",pos:"n.",cn:"成绩;年级",ch:["gr","ade"],ph:"magic-e",tier:2,t:"24:37",en:"Naive little hick with good grades and big ideas",zh:"天真的乡下娃,成绩好、理想大",note:"good grades = 好成绩"},
{w:"idea",ipa:"aɪˈdiːə",pos:"n.",cn:"主意,想法",ch:["i","de","a"],ph:"i-l",tier:1,t:"24:37",en:"Naive little hick with good grades and big ideas",zh:"天真的乡下娃,成绩好、理想大",note:"big ideas = 远大抱负"},
{w:"decide",ipa:"dɪˈsaɪd",pos:"v.",cn:"决定",ch:["de","cide"],ph:"magic-e",tier:2,t:"24:40",en:"decides \"Hey, look at me, I'm gonna move to Zootopia...",zh:"于是决定:“看我的,我要搬去动物城……”",note:"decide to do = 决定做…"},
{w:"sing",ipa:"sɪŋ",pos:"v.",cn:"唱",ch:["s","ing"],ph:"i",tier:1,t:"24:43",en:"where predators and prey live in harmony and sing Kumbaya!\"",zh:"“在那儿猎手和猎物和睦相处,手拉手唱歌!”",note:"过去式 sang"},
{w:"get along",ipa:"",pos:"短语",cn:"处得来,合得来",ch:["get","along"],ph:"",tier:1,type:"chunk",t:"24:46",en:"Only to find, whoopsie, we don't all get along.",zh:"结果发现,哎呀,大家并不都合得来。"},
{w:"double",ipa:"ˈdʌbl",pos:"adj.",cn:"双倍的,双重的",ch:["dou","ble"],ph:"ou-x",tier:2,t:"24:51",en:"double whoopsie, she's a meter maid.",zh:"更糟的是,她成了抄表员。",note:"double+糟糕 = 糟上加糟"},
{w:"soon",ipa:"suːn",pos:"adv.",cn:"很快,不久",ch:["s","oon"],ph:"oo",tier:2,t:"24:57",en:"And soon enough those dreams die,",zh:"要不了多久,那些梦想就凉了,",note:"soon enough = 用不了多久"},
{w:"die",ipa:"daɪ",pos:"v.",cn:"死;熄灭",ch:["d","ie"],ph:"ie-i",tier:2,t:"24:57",en:"And soon enough those dreams die,",zh:"要不了多久,那些梦想就凉了,",note:"die→dead(死的)→death(死亡)"},
{w:"emotional",ipa:"ɪˈmoʊʃənl",pos:"adj.",cn:"情绪上的",ch:["e","mo","tion","al"],ph:"tion",tier:3,t:"24:59",en:"and our bunny sinks into emotional and literal squalor",zh:"我们的兔子就此陷进泥潭,心里身上都是",note:"emotion(情绪)+al"},
{w:"sink",ipa:"sɪŋk",pos:"v.",cn:"下沉,陷入",ch:["s","ink"],ph:"i",tier:3,t:"24:59",en:"and our bunny sinks into emotional and literal squalor",zh:"我们的兔子就此陷进泥潭,心里身上都是",note:"过去式 sank"},
{w:"box",ipa:"bɑːks",pos:"n.",cn:"箱子,盒子",ch:["b","ox"],ph:"x",tier:1,t:"25:02",en:"living in a box under a bridge.",zh:"住在桥洞下的纸箱里。"},
{w:"bridge",ipa:"brɪdʒ",pos:"n.",cn:"桥",ch:["bri","dge"],ph:"dge",tier:2,t:"25:02",en:"living in a box under a bridge.",zh:"住在桥洞下的纸箱里。"},
{w:"choice",ipa:"tʃɔɪs",pos:"n.",cn:"选择",ch:["ch","oice"],ph:"oi",tier:2,t:"25:03",en:"Till finally she has no choice but to go back home",zh:"直到最后,她别无选择,只能回老家",note:"have no choice but to = 只能"},
{w:"till",ipa:"tɪl",pos:"prep.",cn:"直到",ch:["t","ill"],ph:"i",tier:2,t:"25:03",en:"Till finally she has no choice but to go back home",zh:"直到最后,她别无选择,只能回老家",note:"till = until 的口语形"},
{w:"between",ipa:"bɪˈtwiːn",pos:"prep.",cn:"在…之间",ch:["be","tween"],ph:"ee",tier:1,t:"25:07",en:"little tail between her legs to become...",zh:"夹着尾巴,回去当一个……",note:"tail between one's legs = 夹着尾巴(灰溜溜)"},
{w:"leg",ipa:"leɡ",pos:"n.",cn:"腿",ch:["l","eg"],ph:"CVC",tier:1,t:"25:07",en:"little tail between her legs to become...",zh:"夹着尾巴,回去当一个……"},
{w:"careful",ipa:"ˈkerfl",pos:"adj.",cn:"小心的",ch:["care","ful"],ph:"are",tier:1,t:"25:18",en:"Be careful now, or it won't just be your dreams getting crushed.",zh:"当心点,不然碎的就不只是你的梦想了。",note:"care+ful = 满是小心"},
{w:"especially",ipa:"ɪˈspeʃəli",pos:"adv.",cn:"尤其,特别",ch:["e","spe","cial","ly"],ph:"cial",tier:2,t:"25:25",en:"Especially not some jerk who never had the guts to",zh:"尤其轮不到一个自己都没胆量……",note:"espeCIALly 里藏着 special"},
{w:"guts",ipa:"ɡʌts",pos:"n.",cn:"(口语)胆量",ch:["g","uts"],ph:"CVC",tier:3,t:"25:25",en:"Especially not some jerk who never had the guts to",zh:"尤其轮不到一个自己都没胆量……",note:"gut=肠子,guts 引申为胆量"},
{w:"sly",ipa:"slaɪ",pos:"adj.",cn:"狡猾的",ch:["sl","y"],ph:"y-i",tier:3,t:"25:42",en:"Sly fox. Dumb bunny.",zh:"狡猾的狐狸。愚蠢的兔子。"},
{w:"cement",ipa:"sɪˈment",pos:"n.",cn:"水泥",ch:["ce","ment"],ph:"e",tier:3,t:"25:47",en:"Right. And that's not wet cement.",zh:"是啊,那也不是没干的水泥。"},
{w:"wet",ipa:"wet",pos:"adj.",cn:"湿的",ch:["w","et"],ph:"CVC",tier:2,t:"25:47",en:"Right. And that's not wet cement.",zh:"是啊,那也不是没干的水泥。",note:"反义词 dry(干的)"},
{w:"though",ipa:"ðoʊ",pos:"adv.",cn:"不过(放句尾)",ch:["th","ough"],ph:"ough-o",tier:2,t:"25:54",en:"You're a cute meter maid, though.",zh:"不过嘛,你是个挺可爱的抄表员。",note:"句尾 though = 不过"},
{w:"maybe",ipa:"ˈmeɪbi",pos:"adv.",cn:"也许",ch:["may","be"],ph:"ay",tier:2,t:"25:56",en:"Maybe a supervisor one day. Hang in there.",zh:"没准哪天能混个主管当当。挺住啊。"},
{w:"supervisor",ipa:"ˈsuːpərvaɪzər",pos:"n.",cn:"主管",ch:["su","per","vi","sor"],ph:"or-er",tier:3,t:"25:56",en:"Maybe a supervisor one day. Hang in there.",zh:"没准哪天能混个主管当当。挺住啊。",note:"supervise(督导)+or"},
{w:"hang in there",ipa:"",pos:"短语",cn:"挺住,坚持住",ch:["hang","in","there"],ph:"",tier:2,type:"chunk",t:"25:56",en:"Maybe a supervisor one day. Hang in there.",zh:"没准哪天能混个主管当当。挺住啊。",note:"字面“挂在那儿别掉”= 撑住"},
{w:"hang",ipa:"hæŋ",pos:"v.",cn:"挂;悬",ch:["h","ang"],ph:"CVC",tier:2,t:"25:56",en:"Maybe a supervisor one day. Hang in there.",zh:"没准哪天能混个主管当当。挺住啊。",note:"过去式 hung"},
{w:"parent",ipa:"ˈperənt",pos:"n.",cn:"父/母",ch:["pa","rent"],ph:"are",tier:1,t:"26:52",en:"- Oh, hey, it's my parents! - Oh, there she is! Hi, Sweetheart!",zh:"-啊,是我爸妈!-她接了!嗨,宝贝!",note:"parents = 父母俩"},
{w:"everything",ipa:"ˈevriθɪŋ",pos:"pron.",cn:"一切,所有事",ch:["e","very","thing"],ph:"th",tier:2,t:"27:00",en:"- It was real great! - Yeah? Everything you ever hoped?",zh:"-真的挺棒的!-是吗?样样都如你所愿?"},
{w:"hope",ipa:"hoʊp",pos:"v.",cn:"希望",ch:["h","ope"],ph:"magic-e",tier:1,t:"27:00",en:"- It was real great! - Yeah? Everything you ever hoped?",zh:"-真的挺棒的!-是吗?样样都如你所愿?"},
{w:"feel",ipa:"fiːl",pos:"v.",cn:"感觉",ch:["f","eel"],ph:"ee",tier:1,t:"27:06",en:"Everyone's so nice, and I feel like...",zh:"大家都很好,我觉得自己……",note:"feel like = 感觉好像;过去式 felt"},
{w:"make a difference",ipa:"",pos:"短语",cn:"带来改变,起作用",ch:["make","a","difference"],ph:"",tier:1,type:"chunk",t:"27:09",en:"I'm really making a difference.",zh:"我真的在改变着什么。",note:"直译“做出一点不同”"},
{w:"difference",ipa:"ˈdɪfrəns",pos:"n.",cn:"不同,差别",ch:["dif","fe","rence"],ph:"i",tier:2,t:"27:09",en:"I'm really making a difference.",zh:"我真的在改变着什么。",note:"different(不同的)的名词"},
{w:"second",ipa:"ˈsekənd",pos:"n.",cn:"秒;第二",ch:["se","cond"],ph:"CVC",tier:2,t:"27:10",en:"Wait a second. Holy cranks, Bonnie.",zh:"等等。老天爷,邦妮,快看!",note:"Wait a second. = 等一下"},
{w:"heaven",ipa:"ˈhevn",pos:"n.",cn:"天堂;(感叹)老天",ch:["hea","ven"],ph:"ea-e",tier:3,t:"27:12",en:"- Look at that! - Oh, my sweet heaven!",zh:"-看呐!-我的老天爷!",note:"my heaven / good heavens = 我的天"},
{w:"temporary",ipa:"ˈtempəreri",pos:"adj.",cn:"临时的",ch:["tem","po","ra","ry"],ph:"e",tier:3,t:"27:16",en:"Oh, this.. No! Oh, no. This is just a temporary thing..",zh:"这个呀……不不,这只是临时干干……"},
{w:"job",ipa:"dʒɑːb",pos:"n.",cn:"工作",ch:["j","ob"],ph:"CVC",tier:1,t:"27:18",en:"- It's the safest job on the force! - She's not a real cop!",zh:"-这可是警队里最安全的岗位!-她不是真警察!",note:"on the force = 在警队"},
{w:"safe",ipa:"seɪf",pos:"adj.",cn:"安全的",ch:["s","afe"],ph:"magic-e",tier:1,t:"27:18",en:"- It's the safest job on the force! - She's not a real cop!",zh:"-这可是警队里最安全的岗位!-她不是真警察!",note:"最高级 safest = 最安全的"},
{w:"answer",ipa:"ˈænsər",pos:"v.",cn:"回答;回应",ch:["an","swer"],ph:"er",tier:1,t:"27:21",en:"- Our prayers have been answered! - Glorious day!",zh:"-咱们的祈祷显灵了!-大喜的日子!",note:"answer 的 w 不发音"},
{w:"prayer",ipa:"prer",pos:"n.",cn:"祈祷",ch:["pray","er"],ph:"",tier:3,t:"27:21",en:"- Our prayers have been answered! - Glorious day!",zh:"-咱们的祈祷显灵了!-大喜的日子!",note:"pray(祈祷)+er;整词读 /prer/ 一个音节"},
{w:"glorious",ipa:"ˈɡlɔːriəs",pos:"adj.",cn:"光辉灿烂的",ch:["glo","ri","ous"],ph:"or",tier:3,t:"27:21",en:"- Our prayers have been answered! - Glorious day!",zh:"-咱们的祈祷显灵了!-大喜的日子!",note:"glory(光荣)+ous"},
{w:"long",ipa:"lɔːŋ",pos:"adj.",cn:"长的;漫长的",ch:["l","ong"],ph:"CVC",tier:1,t:"27:28",en:"You know what, it's been a really long day, I should...",zh:"这么说吧,今天实在太累了,我先……",note:"a long day = 累了一整天"},
{w:"rest",ipa:"rest",pos:"n.",cn:"休息",ch:["r","est"],ph:"st",tier:2,t:"27:30",en:"- You get some rest. - Those meters aren't gonna maid themselves.",zh:"-好好歇歇。-那些停车表可不会自己贴罚单。",note:"get some rest = 歇一歇"},
{w:"turn down",ipa:"",pos:"短语",cn:"调小(音量);拒绝",ch:["turn","down"],ph:"",tier:2,type:"chunk",t:"27:40",en:"Hey, bunny! Turn down that depressing music!",zh:"喂,兔子!把那丧气音乐关小点!"},
{w:"depressing",ipa:"dɪˈpresɪŋ",pos:"adj.",cn:"令人郁闷的",ch:["de","pres","sing"],ph:"e",tier:3,t:"27:40",en:"Hey, bunny! Turn down that depressing music!",zh:"喂,兔子!把那丧气音乐关小点!",note:"depress(使沮丧)+ing"},
{w:"music",ipa:"ˈmjuːzɪk",pos:"n.",cn:"音乐",ch:["mu","sic"],ph:"u-l",tier:1,t:"27:40",en:"Hey, bunny! Turn down that depressing music!",zh:"喂,兔子!把那丧气音乐关小点!"},
{w:"leave",ipa:"liːv",pos:"v.",cn:"离开;留下",ch:["l","ea","ve"],ph:"ea",tier:2,t:"27:44",en:"Leave the meter maid alone, didn't you hear her conversation?",zh:"别烦人家抄表员了,没听见她打电话吗?",note:"过去式 left(和“左边”同形)"},
{w:"alone",ipa:"əˈloʊn",pos:"adj.",cn:"独自的",ch:["a","lone"],ph:"magic-e",tier:2,t:"27:44",en:"Leave the meter maid alone, didn't you hear her conversation?",zh:"别烦人家抄表员了,没听见她打电话吗?",note:"leave sb alone = 别烦某人"},
{w:"conversation",ipa:"ˌkɑːnvərˈseɪʃn",pos:"n.",cn:"交谈",ch:["con","ver","sa","tion"],ph:"tion",tier:2,t:"27:44",en:"Leave the meter maid alone, didn't you hear her conversation?",zh:"别烦人家抄表员了,没听见她打电话吗?"},
{w:"failure",ipa:"ˈfeɪljər",pos:"n.",cn:"失败者;失败",ch:["fail","ure"],ph:"ai",tier:3,t:"27:47",en:"- She feels like a failure! - Oh, shut up!",zh:"-她觉得自己很失败!-哦,闭嘴吧!",note:"fail(失败)+ure"},
{w:"shut",ipa:"ʃʌt",pos:"v.",cn:"关上",ch:["sh","ut"],ph:"sh",tier:2,t:"27:47",en:"- She feels like a failure! - Oh, shut up!",zh:"-她觉得自己很失败!-哦,闭嘴吧!",note:"shut up = 闭嘴(不礼貌)"},
{w:"worse",ipa:"wɜːrs",pos:"adj.",cn:"更糟的",ch:["w","orse"],ph:"or",tier:2,t:"27:55",en:"Yeah, but it might be worse!",zh:"是啊,但没准还会更糟!",note:"bad 的比较级;最高级 worst"},
{w:"hero",ipa:"ˈhɪroʊ",pos:"n.",cn:"英雄",ch:["he","ro"],ph:"o",tier:2,t:"28:02",en:"Yeah, you're a real hero, lady.",zh:"行啊,你可真是个大英雄,女士。"},
{w:"lady",ipa:"ˈleɪdi",pos:"n.",cn:"女士",ch:["la","dy"],ph:"y",tier:2,t:"28:02",en:"Yeah, you're a real hero, lady.",zh:"行啊,你可真是个大英雄,女士。"},
{w:"wish",ipa:"wɪʃ",pos:"v.",cn:"希望,巴不得",ch:["w","ish"],ph:"sh",tier:1,t:"28:06",en:"My mommy says she wishes you were dead.",zh:"我妈妈说,她巴不得你死掉。"},
{w:"mommy",ipa:"ˈmɑːmi",pos:"n.",cn:"妈妈(儿语)",ch:["mom","my"],ph:"y",tier:1,t:"28:06",en:"My mommy says she wishes you were dead.",zh:"我妈妈说,她巴不得你死掉。",note:"mom 的儿语版,像“妈咪”"},
{w:"tax",ipa:"tæks",pos:"n.",cn:"税",ch:["t","ax"],ph:"x",tier:3,t:"28:09",en:"Uncool rabbit, my tax dollars pay your salary.",zh:"没劲的兔子,我交的税养着你呢。"},
{w:"dollar",ipa:"ˈdɑːlər",pos:"n.",cn:"美元",ch:["dol","lar"],ph:"ar-er",tier:2,t:"28:09",en:"Uncool rabbit, my tax dollars pay your salary.",zh:"没劲的兔子,我交的税养着你呢。"},
{w:"salary",ipa:"ˈsæləri",pos:"n.",cn:"工资",ch:["sa","la","ry"],ph:"y",tier:3,t:"28:09",en:"Uncool rabbit, my tax dollars pay your salary.",zh:"没劲的兔子,我交的税养着你呢。",note:"tax dollars pay your salary = 纳税人养着你"},
{w:"contest",ipa:"kənˈtest",pos:"v.",cn:"提出异议;(n.)比赛",ch:["con","test"],ph:"st",tier:3,t:"28:23",en:"you may contest your citation in traffic court.",zh:"您可以去交通法庭对罚单提出申诉。"},
{w:"citation",ipa:"saɪˈteɪʃn",pos:"n.",cn:"罚单(正式)",ch:["ci","ta","tion"],ph:"c-s",tier:3,t:"28:23",en:"you may contest your citation in traffic court.",zh:"您可以去交通法庭对罚单提出申诉。",note:"ticket 的正式说法"},
{w:"traffic",ipa:"ˈtræfɪk",pos:"n.",cn:"交通",ch:["traf","fic"],ph:"CVC",tier:2,t:"28:23",en:"you may contest your citation in traffic court.",zh:"您可以去交通法庭对罚单提出申诉。"},
{w:"court",ipa:"kɔːrt",pos:"n.",cn:"法庭;球场",ch:["c","ourt"],ph:"our",tier:3,t:"28:23",en:"you may contest your citation in traffic court.",zh:"您可以去交通法庭对罚单提出申诉。",note:"traffic court = 交通法庭"},
{w:"shop",ipa:"ʃɑːp",pos:"n.",cn:"商店",ch:["sh","op"],ph:"sh",tier:1,t:"28:25",en:"What are you talking about?! My shop!",zh:"你说什么呢?!我的店!"},
{w:"rob",ipa:"rɑːb",pos:"v.",cn:"抢劫",ch:["r","ob"],ph:"CVC",tier:3,t:"28:27",en:"It was just robbed! Look, he's getting away!",zh:"刚被抢了!看,他要跑了!",note:"过去式 robbed(双写 b)"},
{w:"worry",ipa:"ˈwɜːri",pos:"v.",cn:"担心",ch:["wor","ry"],ph:"or",tier:1,t:"28:32",en:"Yes! Yes! Don't worry, sir, I got this!",zh:"来了来了!别担心,先生,交给我!",note:"I got this = 交给我"},
{w:"law",ipa:"lɔː",pos:"n.",cn:"法律",ch:["l","aw"],ph:"aw",tier:2,t:"28:41",en:"Stop in the name of the law!",zh:"以法律之名,站住!",note:"in the name of... = 以…之名"},
{w:"catch",ipa:"kætʃ",pos:"v.",cn:"抓住",ch:["ca","tch"],ph:"tch",tier:1,t:"28:42",en:"Catch me if ya' can, cottontail!",zh:"有本事来抓我呀,棉花尾!",note:"过去式 caught"},
{w:"cottontail",ipa:"ˈkɑːtnteɪl",pos:"n.",cn:"棉尾兔(外号)",ch:["cot","ton","tail"],ph:"ai",tier:3,t:"28:42",en:"Catch me if ya' can, cottontail!",zh:"有本事来抓我呀,棉花尾!",note:"cotton(棉花)+tail(尾巴)"},
{w:"through",ipa:"θruː",pos:"prep.",cn:"穿过",ch:["thr","ough"],ph:"ough-u",tier:2,t:"28:52",en:"Coming through!",zh:"借过借过!",note:"coming through = 借过!"},
{w:"pursuit",ipa:"pərˈsuːt",pos:"n.",cn:"追捕",ch:["pur","suit"],ph:"ui",tier:3,t:"28:55",en:"I got dibs! Officer Hopps, I am in pursuit!",zh:"这个归我!霍普斯警官正在追捕!",note:"in pursuit = 追捕中"},
{w:"dibs",ipa:"dɪbz",pos:"n.",cn:"(口语)先到先得",ch:["d","ibs"],ph:"CVC",tier:3,t:"28:55",en:"I got dibs! Officer Hopps, I am in pursuit!",zh:"这个归我!霍普斯警官正在追捕!",note:"got dibs = 我先抢到的"},
{w:"freeze",ipa:"friːz",pos:"v.",cn:"不许动;结冰",ch:["fr","eeze"],ph:"ee",tier:2,t:"29:14",en:"You! Freeze!",zh:"你!不许动!",note:"警察口令 Freeze! = 站住别动"},
{w:"pardon",ipa:"ˈpɑːrdn",pos:"int.",cn:"借过;请再说一遍",ch:["par","don"],ph:"ar",tier:2,t:"29:50",en:"Sorry! Coming through. Excuse me. Excuse me. Pardon.",zh:"抱歉!借过。不好意思,不好意思,劳驾。"},
{w:"voyage",ipa:"ˈvɔɪɪdʒ",pos:"n.",cn:"航行,远行",ch:["voy","age"],ph:"oy",tier:3,t:"29:58",en:"Bon voyage, flatfoot!",zh:"一路顺风啊,条子!",note:"Bon voyage(法语)= 一路顺风"},
{w:"flatfoot",ipa:"ˈflætfʊt",pos:"n.",cn:"(俚语)警察",ch:["flat","foot"],ph:"oo-u",tier:3,t:"29:58",en:"Bon voyage, flatfoot!",zh:"一路顺风啊,条子!",note:"flat(扁)+foot(脚):巡街巡到脚底板变平"},
{w:"leopard",ipa:"ˈlepərd",pos:"n.",cn:"豹",ch:["leo","pard"],ph:"",tier:3,t:"30:21",en:"Oh my god, did you see those leopard print jeggings?",zh:"天哪,你看见那条豹纹打底裤了吗?",note:"eo 读 /e/,o 不发音"},
{w:"print",ipa:"prɪnt",pos:"n.",cn:"印花;打印",ch:["pr","int"],ph:"i",tier:2,t:"30:21",en:"Oh my god, did you see those leopard print jeggings?",zh:"天哪,你看见那条豹纹打底裤了吗?",note:"leopard print = 豹纹"},
{w:"hair",ipa:"her",pos:"n.",cn:"头发",ch:["h","air"],ph:"air",tier:1,t:"30:31",en:"- I love your hair. - Thank you.",zh:"-我喜欢你的发型。-谢谢。"},
{w:"patient",ipa:"ˈpeɪʃnt",pos:"adj.",cn:"耐心的;(n.)病人",ch:["pa","tient"],ph:"ti-sh",tier:2,t:"30:39",en:"Okay. You're gonna have to be patient and wait in line",zh:"好了,您得耐心点,像大家一样排队",note:"be patient = 耐心点"},
];
